### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) :    duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by JordiPosthumus** [lrberge/fixest#10]
Hey Mr Berge !

Found another little bug.  Below is a minimal reproduceable example.

Peace
Jordi

+++++++

library(data.table)
library(fixest)

tmp <- data.table(x1 = 1:100,x2 = runif(100)*100)
tmp[, y := x1 + x2]

model <- feglm(y ~ x1 + x2, data = tmp) # works fine
model <- feglm(y ~ bs(x1) + bs(x2), data = tmp) # does not work

**Comment by lrberge** [comment]
Hmm, I see... that's because I didn't handle cases of functions in the formula returning matrices. Should be easy to fix. Thanks!
