### ISSUE TITLE
Support for Multiple Coefstat Types

### ISSUE THREAD

**Issue by cseveren** [lrberge/fixest#101]
Is it possible to export multiple coefstat types? Support I want both standard errors and confidence intervals. In etable it might be hard with the horizontal alignment of <coef coefstat>, but it would be a nice option for esttex. Alternatively, is there as easy to do this with table post-processing (it isn't immediately obvious to me)?

Thanks for the great package!

reprex:
```
library(datasets)
library(fixest)
data(iris)

esttex(feols(log(Sepal.Length) ~ log(Sepal.Width) | Species, iris), coefstat = "se")
esttex(feols(log(Sepal.Length) ~ log(Sepal.Width) | Species, iris), coefstat = "confint")
esttex(feols(log(Sepal.Length) ~ log(Sepal.Width) | Species, iris), coefstat = c("se", "confint"))
```

**Comment by lrberge** [comment]
Hi, no that's not possible to have the two at the same time. I've never thought about that honestly! :-)

That's very hard to implement with postprocessing. The easiest way is internally. One problem is that implementing it would mess up other parts (messages should be changed) and I'm not sure I want to go that road. 

So I don't think I'll implement it sorry!

**Comment by cseveren** [comment]
No worries, thanks for looking into it!

**Comment by okwon** [comment]
I have a related question/request. I woner if you could consider adding "p-value" as an option for coefstat. There are some journals that discourage reporting significance codes (e.g., stars). Many authors for these journals prefer p-values over standard errors for easier interpretation. This addition would be very helpful in such use case.

**Comment by kylebutts** [comment]
> I have a related question/request. I woner if you could consider adding "p-value" as an option for coefstat. There are some journals that discourage reporting significance codes (e.g., stars). Many authors for these journals prefer p-values over standard errors for easier interpretation. This addition would be very helpful in such use case.

Hi @okwon, could you open a separate issue for this? I think this is a reasonable request and might have additional benefits (e.g. when using a t-distribution to get a p-value, this information is not readily available via just the standard error)
