### ISSUE TITLE
Custom dependent variable labels in `etable`

### ISSUE THREAD

**Issue by apoorvalal** [lrberge/fixest#104]
I'm not sure if I'm missing this in the documentation, but is there a way to specify labels for outcome variables in similar to `dict` for covariates? 

my function call (inside a wrapper function that lets me pass a few arguments) is 
```
etable(models,
    style.tex = style.tex("aer"),
    fixef_sizes = FEsize,
    signifCode = NA, fitstat = ~ n, tex = TRUE,
    dict = treatmap,
    label = lab,
    title = glue::glue("{desc} Regression results"),
    notes = "robust SEs clustered by district",
    file = file.path(root, glue::glue("output/tables/{fn}.tex")), replace = T)
```

and because my regressions are for outcomes with abbreviated names, the table comes out with labels like `inc_vs` in them. I know I can set `depvar=F`, but that would suppress them entirely. Instead, i'd like to set it to `Incumbent Vote Share`. 

Thanks again for the great package! The new event study stuff is super useful.

**Comment by apoorvalal** [comment]
Never mind, i checked the documentation again and turns out this is possible by just adding pieces to `dict`. More fool me.

**Comment by pbaylis** [comment]
> and because my regressions are for outcomes with abbreviated names, the table comes out with labels like `inc_vs` in them. I know I can set `depvar=F`, but that would suppress them entirely.

I'm just following up on this issue because it's related to my (probably silly) question: does `depvar = F` actually suppress the outcome variable row for you when `tex = T`? According to the documentation and when I try it, doesn't work for TeX output. I can easily drop that row manually but am wondering if I'm missing something obvious.

**Comment by lrberge** [comment]
You're right @pbaylis, that's a bug, thanks!

@apoorvalal: glad you like the did stuff, so far that's not really user-friendly but I'll improve it soon!

**Comment by apoorvalal** [comment]
Oh yeah, i guess I was switching back and forth between formats during testing and didn't realise `depvar = F` didn't work w tex. i'm sure @lrberge will squash the bug in no time.

**Comment by lrberge** [comment]
Well, now with an extra baby at home I can't be quick, really. But this bug was easy enough :-)

**Comment by pbaylis** [comment]
Thank you and congrats on the new baby!!
