### ISSUE TITLE
Possible bugs in coefplot for models with interactions of a 2-level factor

### ISSUE THREAD

**Issue by colejharvey** [lrberge/fixest#106]
Really useful package, thanks for this! 

I'm working on models that interact a binary gender factor with a numeric variable.  However, I can reproduce the issue using the coefplot example code.

The example code works to create the following plot, with each of the interaction coefficients of treatment by month.
```
data(base_did)
base_inter = base_did

est_did = feols(y ~ x1 + i(treat, period, 5) | id+period, base_inter)
coefplot(est_did)
coefplot(est_did, only.inter = FALSE)

all_months = c("aug", "sept", "oct", "nov", "dec", "jan","feb", "mar", "apr", "may", "jun", "jul")
base_inter$period_month = all_months[base_inter$period]
est = feols(y ~ x1 + i(treat, period_month, "oct") | id+period, base_inter)
coefplot(est) 
```
![image](https://user-images.githubusercontent.com/51374678/109987081-4f489580-7cd4-11eb-9cf8-433ee6580b67.png)

However, when month is made into a 2-level factor (analogous to my gender variable), the same code produces a coefplot that includes the x1 variable, which is not included in the interaction.

```
all_months = c("oct", "nov")
base_inter$period_month = all_months[base_inter$period]
est = feols(y ~ x1 + i(treat, period_month, "oct") | id+period, base_inter)
coefplot(est)
```
![image](https://user-images.githubusercontent.com/51374678/109987574-c120df00-7cd4-11eb-80c6-8ac07e85ee36.png)

As you can see, the labeling of the month variable is also wonky, and this is also how the variable is described using `print`.

This is not a huge issue, since the extra variables can be excluded from the plot using drop. But if there are many variables to exclude, it can be a small inconvenience. It is also entirely possible that I am mistaken in the correct syntax for an interaction with a 2-level factor!

Thanks again!

**Comment by lrberge** [comment]
Oh that was a sneaky bug! I've never thought of `i()` leading to only one value being retained! Now fixed.

By the way you could have used the `keep` argument.

Thanks again for the report!
