### ISSUE TITLE
fepois() with full interactions not invariant to adding levels

### ISSUE THREAD

**Issue by gleb-roma** [lrberge/fixest#107]
Data explanation: data has units (expid) over time periods (period), no missing values. Some units are in the treatment group (Tr=1), others are not. All units are broken down by strata (strat), in each stratum there are Tr and Control units. I'm estimating treatment effect per period. 

I do the full interaction by period, and the intended behavior is that adding one more period does not change the coefficients for *the other periods*. This is what happens with feols(). But it doesn't happen with fepois(). 

Compare the coefficients on "Tr1 x period18" in the output of the code below. I expect the coefficient in the last column to also be 0.0584, the same as in the 3rd column. 

Bug? 

 ```
load(url("https://github.com/gleb-roma/FE/raw/main/panel.last2mo_debug.RData"))

o1 <- feols(fml = usage ~ Tr*period | expid + strat^period, data = panel.last2mo_debug)
o2 <- feols(fml = usage ~ Tr*period | expid + strat^period, data = panel.last2mo_debug %>% filter(period!='17')%>% droplevels())

o3 <- fepois(fml = usage ~ Tr*period | expid + strat^period, data = panel.last2mo_debug)
o4 <- fepois(fml = usage ~ Tr*period | expid + strat^period, data = panel.last2mo_debug %>% filter(period!='17')%>% droplevels())

etable(o1,o2,o3,o4)

```

**Comment by lrberge** [comment]
Hi, no there's no bug. It's just the Poisson estimator for this particular data set and estimation. You can cross check with alpaca or ppmlhdfe, it's the same.
