### ISSUE TITLE
output of etable() in R notebook not displayed

### ISSUE THREAD

**Issue by nikolassch** [lrberge/fixest#112]
Hi,

after I updated R (and the package?), the output of etable() command is not shown anymore when displayed in-line. 

Here a minimal example:
`cars %>% 
  fixest::feols(fml = dist ~ speed) %>% 
  etable()`

Any help would be much appreciated!

![imagen](https://user-images.githubusercontent.com/22914861/110610771-d7281700-818e-11eb-970b-344de71d2812.png)

**Comment by lrberge** [comment]
Hi, thanks it should be fixed now.

**Comment by nikolassch** [comment]
Thanks a lot!!!
