### ISSUE TITLE
Quantile Regression

### ISSUE THREAD

**Issue by Annyan2333** [lrberge/fixest#113]
Hi! I am wondering if you may include the function of quantile regression in your package in the future as the current r packages including quantile regression do not have options of clustering or fixed effect.
It could be really helpful if you would like to do so.

**Comment by lrberge** [comment]
Hi! Short answer: nope ;-)

As you can imagine, adding such new stuff is extremely time consuming and the only way I could do it is if I had a research project needing quantile regression, which is currently not the case (in such instances, I mentally put the time I spend in "package development" into the "it's for research" account so I don't feel bad! :-)).

So I'm sorry to disappoint. But thanks for the interest in the package!
