### ISSUE TITLE
Conley Standard Errors

### ISSUE THREAD

**Issue by ChristianDueben** [lrberge/fixest#114]
Do you plan on incorporating Conley standard errors into the package? Various users have written Conley standard error corrections that require regressions to be run via `lfe::felm` or `stats::lm` first (e.g. https://github.com/rbluhm/conley and https://github.com/darinchristensen/conley-se). Unfortunately, these implementations tend to throw errors when variables are dropped because of collinearity. As fixest is apparently the state-of-the-art regression package in R now, it would be nice, if it would also support Conley standard error corrections - e.g. via the `se` option in `feols`.

**Comment by lrberge** [comment]
Hi! Adding new built-in VCOVs in the package is not just about writing a new function, it entails changes in many places and so is quite some work, especially that I care a lot about quality control. 
Conclusion: So far it's out of scope and extending the existing functions to be compatible with `fixest` seems to be the easiest and faster way to achieve new VCOVs.

That said, I was thinking to implement a new, more convenient and general way to handle VCOVs in all `fixest` functions. So I may take the opportunity of this big overhaul to add new SEs... But this won't be before several months.

So, I'm closing the issue, but I'll update you if I implement it.
