### ISSUE TITLE
Small sample adjustments issues: Varying slope consistency

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#116]
Following the walkthrough introduction, I estimated varying slopes in the Iris dataset, in two different ways. 
I face several differences, and I'm a bit puzzled by it.
a. First issue is more general 
```
library(fixest)

base_vs = iris
names(base_vs) = c(paste0("x", 1:4), "species")

est_vs0 = feols(x1 ~ x2 | species[x3], base_vs)
est_vs1 = feols(x1 ~ x2 +species:as.numeric(x3)|species, base_vs)


setFixest_dof(dof(adj = FALSE))
etable(est_vs0,est_vs1,cluster ="species")

setFixest_dof()
etable(est_vs0,est_vs1,cluster ="species")
```

I find out that there are differences- in the standard error of our parameter of interest ```X2```, and in the within `Within R2`.

Using `setFixest_dof(dof(adj = FALSE)) ; etable(est_vs0,est_vs1,cluster ="species")` I understand that the changes in see is related to the small sample adjustment?

And I do not even know how should I think of the differences in the within R2, I guess that this is more of an econometric question...

b. Assume I want to allow  for speicies*country variation

```
base_vs$country<-factor(c("a","b","c"))
```

If this is the case, I don't want to add `species FE` as I use `species^country`, however, I do want to use a different slope for each species

```
est_vs0_b = feols(x1 ~ x2 |species^country+species[x3], base_vs)
est_vs1_b = feols(x1 ~ x2 +species:as.numeric(x3)|species^country, base_vs)
est_vs2_b = feols(x1 ~ x2 +species:as.numeric(x3)|species+species^country, base_vs)

setFixest_dof(dof(adj = FALSE))
etable(est_vs0_b,est_vs1_b,est_vs2_b,cluster ="species")

setFixest_dof()
etable(est_vs0_b,est_vs1_b,est_vs2_b,cluster ="species")
```

Here I understand that the changes between the first and second specification is that the first absorb both `species^country` and `species`, even though they are collinear. This, in turn, changes the SE. in the third specification when I add the main effect explicitly I get the same SE as the first specification, and within r2 as in the second.

**Comment by lrberge** [comment]
Hi, there are two questions, I start with the easy one.

#### Within R2

The within R2 is the R2 of the projected model. The projection is based only on the variables that are right of the pipe. Hence if you place the variables with varying slopes on the left of the pipe, the within R2 will be different from the model in which these are projected out.

#### Small sample adjustments

(In all honesty I have nightmares with small sample adjustments! It's really an ordeal to deal with that properly. )

That said, your examples helped to uncover two bugs, one minor and one medium, both for special cases.

*The minor bug.* When clustered SEs are requested, the degrees of freedom (DoF, but it's more exactly the number of parameters, I'll use the DoF term although it's not exact) related to nested fixed-effects are removed. If all fixed-effects DoFs are removed,  one should still be there to represent the constant. 
My internal algorithm was fooled when variables with varying slopes were present and all FEs were removed, leading to an under-adjustment of 1 (the constant was forgotten). 
So this was a bug that is now corrected. But it leads to an extremely minor error.

*The medium bug.* To save time, my internal algorithm does not formally check the nestedness of FEs when the variable on which to cluster is one of them. The fact that you had both `species` and `species^country` as fixed-effects fooled the algorithm and it wasn't able to spot that `species^country` was nested in `species` (just `species^country` would have been fine). 
This led to an error on the small sample ajustement whose relative importance is of order n_combined_FE/n_obs which can be large in some instances, but is usually moderate. 
The algorithm was corrected and is now robust to those special cases.

----

Your examples with these corrections:
```R
etable(est_vs0, est_vs1, cluster = "species")
#>                                            est_vs0           est_vs1
#> Dependent Var.:                                 x1                x1
#>                                                                     
#> x2                                 0.4500 (0.1567)   0.4500 (0.1567)
#> speciessetosa x as.numeric(x3)                      0.3677* (0.0608)
#> speciesversicolor x as.numeric(x3)                 0.6598** (0.0587)
#> speciesvirginica x as.numeric(x3)                  0.8903** (0.0367)
#> Fixed-Effects:                     --------------- -----------------
#> species                                        Yes               Yes
#> Varying Slopes:                    --------------- -----------------
#> x3 (species)                                   Yes                No
#> __________________________________ _______________ _________________
#> S.E.: Clustered                        by: species       by: species
#> Observations                                   150               150
#> R2                                         0.86900           0.86900
#> Within R2                                  0.17894           0.65644

etable(est_vs0_b, est_vs1_b, est_vs2_b, cluster = "species")
#>                                          est_vs0_b         est_vs1_b         est_vs2_b
#> Dependent Var.:                                 x1                x1                x1
#>                                                                                       
#> x2                                 0.4505 (0.1557)   0.4505 (0.1557)   0.4505 (0.1557)
#> speciessetosa x as.numeric(x3)                      0.3816* (0.0658)  0.3816* (0.0658)
#> speciesversicolor x as.numeric(x3)                 0.6556** (0.0554) 0.6556** (0.0554)
#> speciesvirginica x as.numeric(x3)                  0.8816** (0.0378) 0.8816** (0.0378)
#> Fixed-Effects:                     --------------- ----------------- -----------------
#> species^country                                Yes               Yes               Yes
#> species                                        Yes                No               Yes
#> Varying Slopes:                    --------------- ----------------- -----------------
#> x3 (species)                                   Yes                No                No
#> __________________________________ _______________ _________________ _________________
#> S.E.: Clustered                        by: species       by: species       by: species
#> Observations                                   150               150               150
#> R2                                         0.87813           0.87813           0.87813
#> Within R2                                  0.18386           0.66679           0.66679
```

**Comment by lrberge** [comment]
I forgot: one remark. To avoid having the `species` fixed effects in the second example, you can use double brackets:
`feols(x1 ~ x2 | species^country + species[[x3]], base_vs)`

Thanks again for the clear report with the super easy to replicate example!
