### ISSUE TITLE
Minor Bug: fix for negative values in the diagonal throws an error

### ISSUE THREAD

**Issue by joseph-richard-martinez** [lrberge/fixest#118]
Thanks for this super useful package! I wanted to point out one error I've come across when using `summary.fixest`

In the code chunk below from `fixest:::vcov.fixest`, it seems that the matrix algebra inside the call to `tcrossprod` will throw an error if there is a single regressor (i.e. vcov is 1x1). I believe that `diag(1e-8)` will create a 0x0 matrix and the subsequent matrix algebra will be non-conformable.

```
if(any(diag(vcov) < 0)){
	    # We 'fix' it
	    e = eigen(vcov)
	    dm = dimnames(vcov)
	    vcov = tcrossprod(e$vectors %*% diag(pmax(e$values, 1e-8)), e$vectors)
	    dimnames(vcov) = dm
	    message("Variance contained negative values in the diagonal and was 'fixed' (a la Cameron, Gelbach & Miller 2011).")
}
```

**Comment by lrberge** [comment]
Thanks for the report!

Gosh, a non defined variance for just one variable??? But when does it happen (real curiosity!)? 
My guess is that it was an indicator variable for which clustering was applied on same/or close dimension: is it? (Maybe I'm completely off! :-D)

Anyway, that's fixed now! Thanks for the debugging! :-)

**Comment by joseph-richard-martinez** [comment]
Great, thanks for the help! And yes, I encountered this with an indicator and (probably excessively) narrow clustering, though not at exactly the same dimension. Good guess!

**Comment by maswiebe** [comment]
To clarify, is the issue that a regressor corresponds to a singleton cluster? I'm getting this error while running an event study with restrictive clustering.
