### ISSUE TITLE
Rstudio aborting when running a regression

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#119]
I'm trying to estimate a regression , and face unexpected behavior.

In order to replicate the issue, I made this MWE.

```
library(foreign)
library(fixest)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta")

fe1<-feols(asinh(x3)~asinh(x1)+factor(year)|country[year]+opinion[year],data=Panel)
```

When I run this code over and over I get different errors, even though it is the same chunk of code:

1. `Error in slope_vars[[index_slope]] : subscript out of bounds `
2. `The variable 'factor(year)1999' has been removed because of collinearity (see $collin.var). `
3. `R session aborted`

**Comment by lrberge** [comment]
Thanks for the report and for the effort to make a tiny reproducible example, that's really really appreciated! :-)

That was a severe bug. Only happened when one identical variable with varying slope was associated to two different fixed-effects. 

It should be fixed now! :-)
