### ISSUE TITLE
Argument 'coefstat' must be a single character equal to 'se'

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#121]
My code used to work:

```
etable(model1, model2, model3,
       title = "xyz", drop = "Intercept", digits = "r3", digits.stats = "r3",
       coefstat = "tstat", fitstat = ~n + ar2,  
       tex = TRUE,
       style.tex = style.tex(main = "aer", yesNo = c("Yes", "No")))
```
but now produces an error message:

```
Argument 'coefstat' must be a single character equal to 'se'. Problem: no
match was found for 'tstat'.

```

**Comment by lrberge** [comment]
Thanks, fixed.

**Comment by waynelapierre** [comment]
So this fix has been added to the package?
When I tried to install the package in GitHub, the code:
`remotes::install_github("lrberge/fixest")`
produced an error message: Downloading GitHub repo lrberge/fixest@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/lrberge/fixest/tarball/HEAD' failed

**Comment by lrberge** [comment]
The commit is here: ad73bf5825a054a2208f413782c0ae54208ba416
Regarding the install problem: I don't know.

**Comment by waynelapierre** [comment]
This is very strange. I have never encountered this kind of installation issue before. I tried other GitHub R packages and no problems occurred.

**Comment by waynelapierre** [comment]
I managed to install the package from GitHub, but the same error message is still there. I still could not set coefstat to be "stat".

**Comment by lrberge** [comment]
I think there's a problem from your install. The current build works fine for me:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
est = feols(y ~ x1 + x2, base)
etable(est, coefstat = "tst")
#>                               est
#> Dependent Var.:                 y
#>                                  
#> (Intercept)      2.249*** (9.070)
#> x1              0.5955*** (8.590)
#> x2              0.4719*** (27.57)
#> _______________ _________________
#> VCOV type                Standard
#> Observations                  150
#> R2                        0.84018
#> Adj. R2                   0.83800
```
