### ISSUE TITLE
use robust SE and fixed effect & clustering at the same time

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#122]
I would like to ask whether it is OK to use robust SE and fixed effect & clustering at the same time. For example, is there any difference between the two models below:

```
model1 <- feols(Y ~ X|Group, cluster = ~Group, data = data)
model2 <- feols(Y ~ X|Group, se = "hetero", cluster = ~Group, data = data)
```

**Comment by lrberge** [comment]
Hi, no you cannot have both at the same time. What happens is that the `cluster` argument is ignored. I've just added a warning that will pop to make the behavior explicit. Thanks.

**Comment by waynelapierre** [comment]
Thanks for the clarification. How about 
`model1 <- feols(Y ~ X|Group, se = "standard", data = data)
`vs
`model2 <- feols(Y ~ X|Group, se = "hetero", data = data)`

can I use robust SE and fixed effect at the same time?

**Comment by lrberge** [comment]
For sure, and you should use it! 
It only uses a specific set of assumptions on the variance of the error term to compute the VCOV and is unrelated to the use of fixed-effects.

**Comment by waynelapierre** [comment]
thanks for the reply. is it normal that
model1 <- feols(Y ~ X|Group, se = "standard", data = data) 
and
model2 <- feols(Y ~ X|Group, se = "hetero", data = data)
produce the same p value?

**Comment by lrberge** [comment]
What do you mean by the same?

They can be close, sure but shouldn't be identical:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
est = feols(y ~ x1 + x2, base)
est_st = feols(y ~ x1 + x2 | species, base, se = "st")
est_he = feols(y ~ x1 + x2 | species, base, se = "het")

est_st
#> OLS estimation, Dep. Var.: y
#> Observations: 150 
#> Fixed-effects: species: 3
#> Standard-errors: Standard 
#>    Estimate Std. Error t value  Pr(>|t|)    
#> x1 0.432217   0.081390  5.3105  4.03e-07 ***
#> x2 0.775629   0.064246 12.0730 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 0.305129     Adj. R2: 0.859538
#>                  Within R2: 0.641507

est_he
#> OLS estimation, Dep. Var.: y
#> Observations: 150 
#> Fixed-effects: species: 3
#> Standard-errors: Heteroskedasticity-robust 
#>    Estimate Std. Error t value  Pr(>|t|)    
#> x1 0.432217   0.078545  5.5028  1.65e-07 ***
#> x2 0.775629   0.067330 11.5200 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 0.305129     Adj. R2: 0.859538
#>                  Within R2: 0.641507
```

Btw, please provide a small example each time that can be run (like the one I've just shown) so that I can quickly spot what you mean.

**Comment by waynelapierre** [comment]
Thanks for the clarification. I could not share my data because they are proprietary. I get the same p-value whether I use robust SE or not. I have never encountered this issue before. I think the issue may come from my data. I will dig into that.
