### ISSUE TITLE
Using weights with subset

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#131]
Hello!

I frequently estimate WLS, and occasionally estimate regression on a subset of the data.
The weights are a column in my data.frame
I couldn't find a natural way to do it from within `feols`  function, when I run it I get an error that the data and the vector of weights are not of the same size (`est_vs2a`). 
The solution I came up with is either to subset the data beforehand and store it as a new object (`est_vs2c `), or to subset explicitly the weights' vector using `data.table` and pass it to `feols` (`est_vs2b`). 

Am I missing something? Is there a better way of handle this issue?

I was not sure whether it is a minor bug or a feature request.

Thx

```
library(fixest)
library(data.table)
base_vs = as.data.table(iris)
names(base_vs) = c(paste0("x", 1:4), "species")

base_vs$w<-runif(nrow(base_vs),1,4)

#No subset
est_vs0 = feols(x1 ~ x2 | species, data = base_vs,weights =base_vs$w )

# Subset 
est_vs1a = feols(x1 ~ x2 | species, data = base_vs[species!="virginica",] )
est_vs1b = feols(x1 ~ x2 | species, data = base_vs,subset = base_vs$species!="virginica" )

# Add weights
est_vs2a = feols(x1 ~ x2 | species, data = base_vs,subset = base_vs$species!="virginica",weights =base_vs$w )
est_vs2b = feols(x1 ~ x2 | species, data = base_vs[species!="virginica",],weights =base_vs[species!="virginica",w] )

#Sanity check
base_vs1<-base_vs[species!="virginica",]
est_vs2c = feols(x1 ~ x2 | species, data = base_vs1,weights =base_vs1$w )

coef(est_vs2b)==coef(est_vs2c)
```

**Comment by lrberge** [comment]
Thanks for the report! That's a bug for sure.  

Actually this `subset` thing leads to many bugs down the road (one preventing you from using a formula for instance)... 
But now the cause is pretty clear (an optimization I made for `subset` backfired): I'll fix that soon.

**Comment by lrberge** [comment]
I've just fixed it. The code should work now.
