### ISSUE TITLE
can't change clustering variable when the dataset is missing

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#134]
I noticed that I can't change the clustering after I remove the dataset. 
I think that when I cluster on the interaction of variables I can't change the cluster to one of these variables after I remove the dataset.

In the MWE below, I managed to change to clustering of `est1` but failed to do so on other specification.

As a workaround, I could add the variables to the FE part of the formula, alongside the interaction (i.e `country+species+species^country`), obviously, I wish to avoid this practice. 

```
rm(list = ls())
library(fixest)

base_vs = iris
names(base_vs) = c(paste0("x", 1:4), "species")
base_vs$country<-factor(c("a","b","c"))

est = feols(x1 ~ x2 |species^country, data = base_vs,lean = FALSE)
est1 = feols(x1 ~ x2 |species+country, data = base_vs,lean = FALSE)
summary(est,cluster = "country")
summary(est1,cluster = "country")

rm(base_vs)
summary(est,cluster = "country")
summary(est1,cluster = "country")
```

**Comment by lrberge** [comment]
Well, the clustering variable must exist somewhere.... Adding extra variables to the returned object is off the table. Simply save your variable and feed it into the `cluster` argument or cluster at estimation time.  
There's nothing that can be done package-wise.

**Comment by lrberge** [comment]
Btw I have fixed the error message. Thanks.
