### ISSUE TITLE
Cannot predict when using many poly polynomial terms

### ISSUE THREAD

**Issue by XiangLiu-github** [lrberge/fixest#135]
Hi, thanks for your excellent packages! 

When I add three poly terms in the model, the predict function does not work anymore, the reproducible example:

```r
res = feols(Sepal.Length ~ poly(Petal.Length,2) + poly(Sepal.Width,2) + poly(Petal.Width,2) | Species, iris)
predict(res, iris)
```

This shows error:

```r
error in predict.fixest(res, data.frame(Petal.Length = seq...:
 Error when creating the linear matrix: <text>:2:0: unexpected end of input
1: y ~ Sepal.Length ~ (POLY__VAR1__1 + POLY__VAR1__2) + (POLY__VAR2__1 + POLY__VAR2__2) + 
   ^
```
ps, only use one or two poly terms worked for me.

Do you have any suggestions?

**Comment by lrberge** [comment]
Hi, thanks for the report!

I simply forgot a `_long` suffix somewhere in the code... It should be solved now. Thanks again!
