### ISSUE TITLE
Identify the sample used in a regression

### ISSUE THREAD

**Issue by vronizor** [lrberge/fixest#142]
Hi @lrberge, thanks a lot for the great package!

Disclaimer: I am new to R and this might be a more general question on regressions in R, sorry if it doesn't belong here.

Coming from Stata, I'm used to the `e(sample)` command which lets the user identify, post-estimation, the sample used to run the regression. This can be useful to then compute the average of the dependent variable for the control group included in the estimation, for example.

I haven't found a way to do that with `fixest`. I've tried [several](https://theesspreckelsen.wordpress.com/2016/08/10/estimation-sample-information-from-linear-regression-in-r-using-lm-aka-statas-esample/) proposed [solutions](https://stackoverflow.com/questions/38116796/identify-regression-sample-in-r) but always ended up with a `NULL` result for an estimation I knew used only part of the full sample.

Is this at all possible? Might it be that the objects returned by `lm` as given in the links above are not the same as the ones returned by `feols`?

**Comment by vronizor** [comment]
Here is a mwe:

```r
library(data.table)
library(fixest)

DT = as.data.table(airquality)

est = feols(Ozone ~ Solar.R + Wind + Temp | Month + Day, 
            DT, cluster = ~Day)

# Method 1
DT[, used := TRUE]
DT[na.action(est), used := FALSE]

# Method 2
esample = rownames(as.matrix(resid(est)))
DT[esample]
```

I noticed the `NOTE: 42 observations removed because of NA values (LHS: 37, RHS: 7).`, so there might be a way to retrieve that info :)

**Comment by 24thronin** [comment]
Hi vronizor, I am also new to R and I had to do this today. I found the "obsRemoved" entry in the est object returned by feols can be used to retrieve the sample as follows (retrieves all collumns):
sample <- DT[-est[["obsRemoved"]],]

or for just a list of rows used it should be 
sample <- setdiff(1:est[["nobs_origin"]], est[["obsRemoved"]])

**Comment by vronizor** [comment]
Thanks @24thronin, works perfectly! I need to get used to digging into these post-estimation objects, they are very handy!

**Comment by adamaltmejd** [comment]
Was just looking for this -- looking forward to `obs()` :), will it work even if `lean = TRUE`?

**Comment by lrberge** [comment]
@adamaltmejd: of course not! :-D The information is possibly of order n so it is removed.

But in the long run, any command will work even if `lean = TRUE`, it's only processing time that will be longer.
