### ISSUE TITLE
Fitstats and fixed effects indicators in modelsummary

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#145]
Hey

Is there any way to get modelsummary to see the available fitstats (eg. "ivwald"). Currently only defaults are included and setting `modelsummary(fit, gof_map = list(list("raw" = "ivwald", "clean" = "Wald", "fmt" = 0)))` does not work. 

When I run `broom::glance(fit)` it shows the following stats:

```
r.squared adj.r.squared within.r.squared pseudo.r.squared   sigma   nobs   AIC   BIC logLik
```

However, in the output there are also columns indicating existence of fixed effects and se clusters. What are the "raw" names of these rows needed to control them using the `gof_map` argument?

Edit: figured out i can find the raw names by running `modelsummary(fit[[1]], output = "modelsummary_list")`.

**Comment by adamaltmejd** [comment]
Not sure if this is an issue with fixest or modelsummary but tried to set up a `glance_custom.fixest` function to add the statistic as follows:

```
glance_custom.fixest <- function(x) {
        tibble("ivwald" = fitstat(x, "ivwald")[[1]]$stat)
}
```


Thinking it might a problem with fixest since also this example from modelsummary does not work:

```
library(fixest)
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv'
dat <- read.csv(url)
mod <- list()
mod[[1]] <- feols(emp ~ wage, dat)
mod[[2]] <- feols(emp ~ wage | firm, dat)
mod[[3]] <- feols(emp ~ wage | firm + year, dat)

glance_custom.fixest <- function(x) {
    out <- tibble::tibble(.rows = 1)
    for (n in x$fixef_vars) {
        out[[paste('TEST: ', n)]] <- 'Y'
    }
    return(out)
}

modelsummary(mod)

```

**Comment by adamaltmejd** [comment]
Getting close now :). I can use `output = "modelsummary_list"` and then att the statistics manually. No idea why glance_custom isn't working though.

```
mlist <- modelsummary(fit, output = "modelsummary_list")

for (i in seq_along(mlist)) {
    stat <- tryCatch(
        fitstat(fit[[i]], "ivwald1", simplify = TRUE, verbose = FALSE),
        error = function(e) e
    )
    if (inherits(stat, "error")) next
    mlist[[i]]$glance[["ivwald1.stat"]] <- stat$stat
    mlist[[i]]$glance[["ivwald1.p.value"]] <- stat$p
}
```

One problem is that `fitstat` throws a strange error if the statistic isn't available for the model so I had to wrap the thing in `tryCatch()`.

```
Error: in degrees_freedom(x, vars = x$iv_inst_nam...:
 Argument 'vars' must be a character vector. Problem: it is NULL.
```

**Comment by lrberge** [comment]
Hi Adam, well I'm not sure that overall this is a `fixest` problem. I really don't see what I can do ;-) Could you clarify the fixest-related issue?

By the way, regarding the `tryCatch`: this was a bug now corrected (not yet pushed [because the current master contains breaking changes {for once}, I'm waiting until it's finalized]).

**Comment by adamaltmejd** [comment]
Hey, neither am I :). But wanted to share my procedure in case you were interested or someone else was facing similar problems. It would be great if all the fitstats were automatically available in modelsummary() but perhaps that would require additional computations? The other thing is the fact that the `glance_custom.fixest` method isn't working. Was thinking it might be a bug with how fixest adds the FE indicators to the modelsummary default output even though they are not seen when running `broom::glance(fit)`?

**Comment by lrberge** [comment]
I agree I think that would be nice too but it's not on my side! The best would be to add `fitstat` in the `...` argument of `glance.fixest`.
On the fixed-effects thing: still not on my side...

**Comment by adamaltmejd** [comment]
:) I'll post the question there instead then! Thanks!

**Comment by lrberge** [comment]
Wow, lightning fast fix as usual @vincentarelbundock! 
**I** am the one sorry for causing you trouble!
