### ISSUE TITLE
estex drop coefficents in interactions when they are not in the same order

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#148]
Hi Laurent,  thanks again for this great package!

I encountered today what seems to be a minor bug (tho, it took me a couple of hours to identify),
When I estimate in one regression the interaction of two vars (i.e. `post:treat`), `esttex` prints only the first regression coefficient.
It is noteworthy that `etable` in "txt" mode works well.

Below I attached an MWE to make things more concrete

``` 
library(fixest)
data(base_did)

est_did1 = feols(y ~ post:treat| id + period, base_did)
est_did2 = feols(y ~ treat:post | id + period, base_did)

etable(est_did1,est_did2)
esttex(est_did1,est_did2)
```

**Comment by lrberge** [comment]
Ah, these interactions with same variables are tricky! Thanks, that's fixed (not pushed yet though).
