### ISSUE TITLE
Does F-test uses the "correct" df?

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#151]
Hi Laurent, 
Thank you again for this incredible package.

I followed the `reghdfe` quickstart guide and tried to replicate its results in `fixest`.
I followed the vignettes on standard errors but didn't find an answer there.

I ran this regression in Stata (Yuck!)
```
reghdfe price weight length foreign, absorb(turn) vce(cluster turn)
```

And this one in R 
```
feols(price~ weight+length+foreign |turn,fixef.rm="singleton",
           cluster="turn",data=auto)
``` 

Both estimations yield the same standard errors and p-values. Thus, I expected to find the same results in their F-test.
However, in Stata, the df is (3,13). Apparently, df1=k, and df2=G-1. In `feols,` on the other hand, I find the df used there are (3,53),
I guess that  53 is N-k-G.

What is the rationale for disregarding the change in df when clustering the standard error?
Can I replicate reghdfe behavior?

**Comment by lrberge** [comment]
Hi Or, and sorry for the very tardy reply! No you cannot replicate this behavior atm.
Dealing with dofs is a nightmare! :-D
I'll make the two software align in terms of results. I'll let you know!

**Comment by lrberge** [comment]
OK, finally :-)!

The way it's computed wan be directly modified with the `dof` argument:

```R
fitstat(a, "f")
#> F-test: stat = 7.7224, p = 0.003259, on 3 and 13 DoF.
fitstat(a, "f", dof = dof(t.df = "conv"))
#> F-test: stat = 39.2, p = 1.146e-14, on 3 and 66 DoF.
```

The `dof(t.df)` thing is not really explicit so I will make the argument name more general with `test.df` which corresponds to the way we compute the DoF for tests (and not only the t-test).

Thanks again for reporting!
