### ISSUE TITLE
Pseudo R2 with weighting

### ISSUE THREAD

**Issue by fostermeijer** [lrberge/fixest#155]
There appears to be a problem when computing the pseudo R2 when weights are included e.g.

```
# Default is a poisson model
res = feglm(Sepal.Length ~ Sepal.Width + Petal.Length | Species, iris)
# Add weight variable
iris$Weights <- iris$Sepal.Length / iris$Sepal.Width
res2 = feglm(Sepal.Length ~ Sepal.Width + Petal.Length | Species, iris, weights = iris$Weights)

```
The Pseudo R2 from res2 becomes negative:

> res2
GLM estimation, family = poisson, Dep. Var.: Sepal.Length
Observations: 150 
Fixed-effects: Species: 3
Standard-errors: Clustered (Species) 
             Estimate Std. Error z value  Pr(>|z|)    
Sepal.Width  0.067978   0.028717  2.3672  0.017923 *  
Petal.Length 0.126888   0.011281 11.2480 < 2.2e-16 ***
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood:  -536.1   Adj. Pseudo R2: -0.926401
           BIC: 1,097.2     Squared Cor.:  0.863215

**Comment by lrberge** [comment]
Hi, indeed there was a problem regarding the computation of the NULL likelihood for Poisson and logit models when weights were present.  Now fixed, thanks.
