### ISSUE TITLE
R crashes with fepois

### ISSUE THREAD

**Issue by ChristianDueben** [lrberge/fixest#157]
R crashes when using `fepois`. The error occurs with both the CRAN and the development version and multiple versions of R (we tested 4.0.4 and 4.1.0 on Windows 10). The data used is the regular [CEPII gravity data set](http://www.cepii.fr/cepii/en/bdd_modele/presentation.asp?id=8.). Consider the following example where the `cepii` object holds the mentioned data set:

```
require("tidyverse")
require("fixest")
cepii <- mutate(cepii, dist_var = runif(NROW(cepii), min = 0.95 * dist, max = 1.05 * dist), tradeflow_imf_d = ifelse(country_exists_d == 1 & country_exists_o == 1, replace_na(tradeflow_imf_d, 0), NA))
fepois(tradeflow_imf_d ~ log(dist_var) + rta | iso3_o^year + iso3_d^year + iso3_o^iso3_d, data = cepii, cluster= "iso3_o^iso3_d")
```

The estimation sometimes runs once, but then crashes R when running it a second or third time. The error aborts the entire R session, pointing to its source outside R, i.e. inside the C++ part of the package. Could a memory leak in the C++ code be the issue?

**Comment by lrberge** [comment]
Thanks, that's an important bug. Likely inked to #146 (which I couldn't replicate).
Could you dm me the full dataset that you use so that I can fully replicate ?

**Comment by lrberge** [comment]
Thanks, I'll try to solve the pblm asap.

**Comment by ChristianDueben** [comment]
Thanks.

**Comment by lrberge** [comment]
That was a very odd bug. But it should be fixed now. Thanks again.
