### ISSUE TITLE
An option to have t-stats below the coefficients instead of sd in esttex regression outputs

### ISSUE THREAD

**Issue by d712** [lrberge/fixest#16]
Hi Laurent,

This package has made everything (e.g. clustering, generating latex codes) much easier and faster! Thanks for making it. 

I was wondering, if the function esttex has an option that allows me to report t-stats (or z-stats) in the parentheses below the coefficients, instead of sd/se, in the regression output. 

And, if not, is there an easier way to customize the latex output so that it contains the t-stats , than manually copying the t-stats and replacing the standard deviations with them in the latex output?

I ask because some journals prefer t-statistics to standard errors. Thanks!

**Comment by lrberge** [comment]
Thanks for the kind words, I'm glad that it saves you time! 

Thanks for the suggestion! No, it's not there yet, but it's easy to implement, I'll do it within the coming month (I'll also add confidence intervals).

By the way, I am planning to improve quite a bit the utility functions for the next CRAN release. If you have any other suggestion, please let me know (even not concrete: like what you would ideally want).

**Comment by d712** [comment]
Awesome. Looking forward to the next release!

And sure, I'll let you know if anything comes up during the use.

**Comment by lrberge** [comment]
Hi, I've added the feature in the dev version. 

Thanks again for the suggestion!
