### ISSUE TITLE
coefstat in etable can only be set as "se"

### ISSUE THREAD

**Issue by zjz1206** [lrberge/fixest#163]
library(fixest)

df<-data.frame(a = c(1,2,3),b = c(2,3,4))

ols_result<-feols(a~b, df)

etable(ols_result, coefstat = "tstat")

Error: in etable(., coefstat = "tstat"):
 Argument 'coefstat' must be a single character equal to 'se'. Problem: no match was found for 'tstat'.

**Comment by lrberge** [comment]
Please have a look at past issues + use the last version of the package.

Identical to #121 which was fixed. Bug does not show up in current version.
