### ISSUE TITLE
iplot(), drop not functioning as described? 

### ISSUE THREAD

**Issue by roussanoff** [lrberge/fixest#164]
I only recently started using `fixest`. I use the most recent version 0.9.0.  I want to omit a (numerical) factor in the plot of the fixed effects generated by `iplot()`. 

```
library(fixest)
reg1 <- feols(mpg ~ disp + i(carb, ref = 8), data = mtcars)
fdict <-  c("2" = "two", "3" = "three")
etable(reg1, dict = fdict)
```

The summary replaces values 2 and 3 with the defined labels. However, no category is  dropped when I try to run any of the following

```
iplot(reg1, dict = fdict, drop = "two")
iplot(reg1, dict = fdict, drop = "^two")
iplot(reg1, dict = fdict, drop = "two|three")
iplot(reg1, dict = fdict, drop = "%2")
```

How do I omit the desired category/ies? Is this actually an issue or did I misread the syntax from the package documentation?

**Comment by lrberge** [comment]
No, that's currently not working. There are two things. 
First, the renaming of levels only (and not the full variable name) is not implemented in `coefplot`/`iplot`.
Second, drop/keep does not yet work in `iplot`. 
I'll let you know when it's fixed.

**Comment by lrberge** [comment]
Hi, `drop` now should work properly. 
The relabeling of vector values is actually very tricky because I have to deduce the intent of the user and it can't always be a win. So I still have to think about it!
