### ISSUE TITLE
increase distance between caption and table in latex output

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#165]
I feel like the distance between caption and table in the latex output of etable could be longer.  
I typically manually insert \vspace{5 mm} after the caption. What do you think?

**Comment by lrberge** [comment]
Well, that's up to anyone's taste :-)
I'm not really keen in having too many arguments in the function.
However, I will implement something in the (hopefully near) future to help inject tex code into the output very easily and intuitively (currently it's a bit difficult do it). I'll keep you updated!
