### ISSUE TITLE
Problem with feglm( ..., family = "logit")

### ISSUE THREAD

**Issue by gbiele** [lrberge/fixest#167]
Thanks for making this packages available!

I might simply overlook something in the documentation, but I can't seem to find what mistake I made, so here we go:

When I trying to run a logistic regression with the command

```
fe_fit = 
  feglm(y ~ x | id, 
    data = dt, 
    family = "logit")
````
 I am getting the error message: 

> Error in feglm(y ~ x | id, data = dt, family = "logit") : 
  Problem in the argument family:
object 'logit' of mode 'function' was not found

I can define
`logit = qlogis`

bu then I get just a different error message:

> Error in feglm(y ~ x | id, data = dt, family = "logit") : 
  Error in family() : argument "p" is missing, with no default
This error was unforeseen by the author of the function feglm. If you think your call to the function is legitimate, could you report?

Am I doing something wrong, or is this a bug?

Thanks in advance - Guido

### Reproducible example:

```
library(fixest)
dt = 
  data.frame(
    y = sample(0:1,1000, replace = T),
    id = factor(sample(1:5,1000, replace = T)),
    x = rnorm(1000))

fe_fit = 
  feglm(
    y ~ x | id, 
    data = dt, 
    family = "logit")

logit = qlogis

fe_fit = 
  feglm(
    y ~ x | id, 
    data = dt, 
    family = "logit")
```

**Comment by lrberge** [comment]
Hi, and thanks for using! 

Actually it's the same error as you would have with `glm`:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
base$y_01 = with(base, y > mean(y))

glm(y_01 ~ x1, base, family = "logit")
#> Error in get(family, mode = "function", envir = parent.frame()) : 
#>   object 'logit' of mode 'function' was not found
```

That's because you need to provide not just a density but a full family of functions. In your case, this is in `binomial()`. Note that you can also make a direct maximum likelihood estimation with `femlm` and (this time it works [bc it's a completely different approach]) `family = "logit"`:
```R
# Using GLM
feglm(y_01 ~ x1, base, family = binomial())
#> GLM estimation, family = binomial, Dep. Var.: y_01
#> Observations: 150 
#> Standard-errors: Standard 
#>              Estimate Std. Error t value Pr(>|t|))    
#> (Intercept)  2.628000   1.233800  2.1300  0.033175 *  
#> x1          -0.905326   0.401809 -2.2531  0.024251 *  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> Log-Likelihood: -100.9   Adj. Pseudo R2: 0.016507
#>            BIC:  211.9     Squared Cor.: 0.033441

# Using ML approach
femlm(y_01 ~ x1, base, family = "logit")
#> ML estimation, family = Logit, Dep. Var.: y_01
#> Observations: 150 
#> Standard-errors: Standard 
#>              Estimate Std. Error t value Pr(>|t|))    
#> (Intercept)  2.628000   1.233800  2.1300  0.033175 *  
#> x1          -0.905326   0.401809 -2.2531  0.024251 *  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> Log-Likelihood: -100.9   Adj. Pseudo R2: 0.016507
#>            BIC:  211.9     Squared Cor.: 0.033441
```

But having "logit"/"probit" shortcuts may be handy, so I'll add these aliases in the future. Thanks!

**Comment by gbiele** [comment]
Thanks.
I am aware that binomial is the right family for the a logistic regression.
I just got thrown off because this section on page 72 of the[ fixest documentation](https://cran.r-project.org/web/packages/fixest/fixest.pdf) (my highlighting):

> family:
 Character scalar. It should provide the family. **The possible values are** "poisson" (Poisson model with log-link, the default), "negbin" (Negative Binomial model with log-link), "logit" (LOGIT model with log-link), "gaussian" (Gaussian model).

Of course I should have just tried the standard `family = binomial()`-

**Comment by lrberge** [comment]
It's not the right function: it was the doc of `femlm` that you looked at, and not the doc of `feglm` which states (p60):

> Family to be used for the estimation. Defaults to gaussian(). See family[link] for details of family functions.

The two functions `femlm` and `feglm` are really different, not in the results, but in the estimation procedure and the former does not use conventional families.

**Comment by lrberge** [comment]
> leads nowhere? 

That's normal because it's a link to another R documentation section and these don't render in the pdf doc. 
It simply leads to the [family section of the stats package](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/family) (so nothing fancy ;-)).

> Anyhow, thanks for your prompt responses and clarifications!

You're welcome :-)
