### ISSUE TITLE
logit and probit models

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#170]
Just want to ensure that I am using this package correctly. Based on the syntax of R's base glm, a logit model using fixest should be `feglm(y ~ x, data, family = binomial(link = "logit"))` and a probit model should be `feglm(y ~ x, data, family = binomial(link = "probit"))`. Am I doing it correctly? Thanks.

**Comment by lrberge** [comment]
Yes, that's correct! :-)
Btw I've just added aliases to logit/probit so that `feglm(y ~ x, data, family = "logit")` and `feglm(y ~ x, data, family = "probit")` would also work as expected.

**Comment by waynelapierre** [comment]
great! that would my the syntax more concise
