### ISSUE TITLE
Issue with `model.matrix.fixest` with "fixef" type

### ISSUE THREAD

**Issue by kylebutts** [lrberge/fixest#172]
Hi Laurent, I'm reporting a bug with the `model.matrix.fixest` function. It reports that there are no fixed effects, but there  is. Here is the reprex

``` r
library(fixest)
#> fixest 0.9.0, BREAKING changes! (Permanently remove this message with fixest_startup_msg(FALSE).) 
#> - In i():
#>     + the first two arguments have been swapped! Now it's i(factor_var, continuous_var) for interactions. 
#>     + argument 'drop' has been removed (put everything in 'ref' now).
#> - In feglm(): 
#>     + the default family becomes 'gaussian' to be in line with glm(). Hence, for Poisson estimations, please use fepois() instead.
data(trade)
# OLS estimation
gravity = feols(log(Euros) ~ log(dist_km) | Destination + Origin + Product + Year, trade)

model.matrix(gravity, type = "fixef")
#> Error in model.matrix.fixest(gravity, type = "fixef"): In model.matrix, the type 'fixef' is only valid for models with fixed-effects. This estimation does not contain fixed-effects.
```

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by kylebutts** [comment]
Here is where the relevant error is from: 
https://github.com/lrberge/fixest/blob/6c99dfef2653871c9e0f0ed16047b5f7900c828f/R/MiscFuns.R#L7899-L7920

**Comment by lrberge** [comment]
Thanks a lot Kyle!!! Fixed + test file duly updated :-)

**Comment by gsaabogado** [comment]
Hi Laurent, I am using the latest package version, and the problem with the model.matrix.fixest function persists. 

I solved the issue by modifying the function manually. However, I thought about sharing.

**Comment by lrberge** [comment]
It works on my machine. Could you please share a minimum reproducible example?

**Comment by scottloring** [comment]
I believe the issue is with the function `extralines_register` and not with the `model.matrix.fixest`. Your testing `feols` object (line 4690) doesn't contain any fixed effects, so it can't confirm any extralines macros which reference fixed effects.


https://github.com/lrberge/fixest/blob/0706b64ebb8bccc1e7f8b19752128eadd466d745/R/etable.R#L4670-L4706
