### ISSUE TITLE
Standard Error things

### ISSUE THREAD

**Issue by kylebutts** [lrberge/fixest#177]
As it's definitely standard error time in fixest development, two ideas :-)

1. For my `did2s` function, I pass custom standard errors and was wondering if it would be possible to pass a named object to vcov, e.g. vcov(fixest, vcov = list("Two-stage Corrected Standard Errors" = vcov)) and replace "Custom" with "Two-stage Corrected Standard Errors". Would improve summary and esttab as it currently puts "Standard Errors: Custom". :-)

Relevant line: https://github.com/lrberge/fixest/blob/3e5bb4273e104a3152cc24311daa4d221523e509/R/MiscFuns.R#L156

2. Really cool that you're adding Conley standard errors. In panel settings, it's common to have a Spatial HAC where you allow spatial correlation up to some distance and a Newey-West style autocorrelation (Ferman, 2020 for example). 

It's should be pretty easy to do as Spatial HAC = Spatial + HAC - robust, which you can do all three, see e.g. https://gist.github.com/kylebutts/c289044c3233f9f0c3edfd14bee164e4

Thanks Laurent!

**Comment by lrberge** [comment]
Hi Kyle!

 1. Good idea! Same comment applies when passing functions. Actually I just thought nobody would use that functionality  ;-)
 2. Yeah I know! I knew someone would eventually come up with this comment, I just didn't expect it would be so fast! 😄
Although it's easy, I really don't have the time at the moment. But it's next on the VCOV list!

Thanks for the suggestions!

**Comment by kylebutts** [comment]
Thanks! For future reference (and for other users), it's really easy and matches almost spot on to the Stata Spatial HAC function. Only if we had the option to change the standard error name from "Custom" to "Spatial HAC"... ;)

``` r
library(fixest)
library(tidyverse)

# https://darinchristensen.com/post/conley-correction/
df <- haven::read_dta("https://github.com/darinchristensen/conley-se/blob/master/data/new_testspatial.dta?raw=true") %>% 
    drop_na(EmpClean00) %>%
    mutate(
        latitude = latitude + 90
    )

m <- fixest::feols(EmpClean00 ~ HDD + CDD | year + FIPS, data = df, demeaned = TRUE)

## Manually using fixest

conley <- fixest::vcov_conley(
    m, lat = ~latitude, lon = ~longitude, 
    cutoff = "500mi", distance = "spherical"
)

hac <- fixest::vcov_NW(
    m, unit = ~FIPS, time = ~time, 
    lag = 5
)

robust <- vcov(m, vcov = "hetero")

sqrt(diag(conley + hac - robust))
#>      HDD      CDD 
#> 0.722557 3.559286

## Stata output with cutoff 500mi and 5 year lag:
#       Spatial_HAC
# HDD   0.721
# CDD   3.631


# Plugging back into fixest to store vcov
m <- summary(m, vcov = conley + hac - robust)
summary(m)
#> OLS estimation, Dep. Var.: EmpClean00
#> Observations: 5,361 
#> Fixed-effects: year: 15,  FIPS: 362
#> Standard-errors: Custom 
#>     Estimate Std. Error   t value Pr(>|t|)) 
#> HDD -0.28341   0.722557 -0.392232  0.694903 
#> CDD  2.49660   3.559300  0.701444  0.483059 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 5,541.1     Adj. R2: 0.995243
#>                 Within R2: 8.039e-4
```

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by kylebutts** [comment]
By the way, the above example data is from [Fetzer (2014)](http://www.trfetzer.com/wp-content/uploads/fracking-local.pdf). 

Would be happy to add to the standard error vignette a section for Conley, HAC, and Conley + HAC with potentially discussion on combining standard errors if you would like!

**Comment by lrberge** [comment]
Thanks for writing the thing up! I think it will be useful for sure!

OK, now point 1 is fixed:
```R
library(fixest)

# https://darinchristensen.com/post/conley-correction/
df <- haven::read_dta("https://github.com/darinchristensen/conley-se/blob/master/data/new_testspatial.dta?raw=true")

m <- fixest::feols(EmpClean00 ~ HDD + CDD | year + FIPS, data = df)

## Manually using fixest

conley <- fixest::vcov_conley(
    m, cutoff = "500mi", distance = "spherical"
)

hac <- fixest::vcov_NW(
    m, unit = ~FIPS, time = ~time,
    lag = 5
)

robust <- vcov(m, vcov = "hetero")

sqrt(diag(conley + hac - robust))
#>      HDD      CDD 
#> 0.722557 3.559286 

# Plugging back into fixest to store vcov
m <- summary(m, vcov = list("Conley-HAC" = conley + hac - robust))
summary(m)
#> OLS estimation, Dep. Var.: EmpClean00
#> Observations: 5,361 
#> Fixed-effects: year: 15,  FIPS: 362
#> Standard-errors: Conley-HAC 
#>     Estimate Std. Error   t value Pr(>|t|)) 
#> HDD -0.28341   0.722557 -0.392232  0.694903 
#> CDD  2.49660   3.559300  0.701444  0.483059 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 5,541.1     Adj. R2: 0.995243
#>                 Within R2: 8.039e-4
```

I also took the opportunity to automatically rescale the latitude.

For point 2, as the code can attest, I had anticipated it a bit :-D -- so it will be there!
https://github.com/lrberge/fixest/blob/d42a3be94972de46f582c35b9e9e840345f7bd70/R/VCOV.R#L1637

**Comment by lrberge** [comment]
On the writing, that's very generous of you! 

In the vignette, tbh I don't know. One reason is that I don't really know what I want this vignette to be. So far I prefer to focus it mostly on the point of contention between different software: the small sample correction. Hence I described the way we compute the clustered SEs but only because it was necessary to understand on what the SSC is based.
So on the detailed description of the Conley, etc... I'm not sure. 
However, regarding the combination of different SEs, I think it can be a nice addition. Especially that the way we adjust for SSC is a problem on its own for these cases (since the SSC can be applied differently for each of the VCOV that we combine).

And you're more than welcome to contribute to the help pages of the VCOVs if you still want! :-)

**Comment by lrberge** [comment]
Hmm, if I'm not mistaken I don't think the current code is really Conley-HAC.

The problem is that Conley HAC should be:
SUM_*t*   SUM_*i*   SUM_*j*   X' *it*   e_*it*   e_*jt*   X*jt*   K(d_*ij*)

But currently it is:
SUM_*t*   SUM_*i* SUM_*u*   SUM_*j*   X'*it*   e_*it*   e_*ju*   X*ju*   K(d_*ij*)

**Comment by tbaldenius** [comment]
Hi everyone!

Any news on this issue? What code is (potentially) not Conley-HAC? The one suggested by Kyle?

A lot of applications of Conley standard errors, at least in climate econometrics, do actually prefer using a triangular (Bartlett) kernel instead of the uniform one originally suggested by Conley. I was wondering if that would be something that could be implemented quite quickly. Basically, compared with a uniform kernel you'd just replace

(dist[i,j] <= cutoff)

with

(dist[i,j] <= cutoff) * (1 - dist[i,j]/cutoff),

right?

I think the package is amazing and it allows me to perform estimations quickly that would otherwise take ages. Thank you for considering my comment!

**Comment by mmeleseg** [comment]
Hi @lrberge and @kylebutts, 

First of all, thank you both for your work on fixest and dids2s. 

Apologies if this is already available in the fixest package. Does "vcov_conley" allow one to account for BOTH spatial and serial correlation, or would it be possible to add that in it is not already available? There is another package "conleyreg" that implements this (based on distance and temporal lag cutoffs), but I was wondering whether it would be possible to also do this using "feols" since feols has other advantages over "conleyreg".  Thanks!

**Comment by kylebutts** [comment]
@mmeleseg you can compute it by adding the vcov_conley and vcov_serial and subtracting one robust. It's just like with two-way clustering:

``` r
library(fixest)
set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10))-50, each = 20)
lon <- rep(matrix(runif(10))+40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon)*500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y,X,unit,time,lat,lon) 

fe_model <- fixest::feols(
  y ~ X1 + X2 | unit, data = df
)

vcov_spatial_hac = 
  vcov_conley(fe_model, lat = ~lat, lon = ~lon, cutoff = 10) + 
  vcov_NW(fe_model, time = ~time, unit = ~unit) - 
  vcov(fe_model, "hc1")

fe_model <- summary(fe_model, .vcov = vcov_spatial_hac)

vcov(fe_model)
#>            X1         X2
#> X1 0.11728009 0.01933524
#> X2 0.01933524 0.49097437
vcov_spatial_hac
#>            X1         X2
#> X1 0.11728009 0.01933524
#> X2 0.01933524 0.49097437
```

**Comment by kylebutts** [comment]
@mmeleseg, the `vcov` argument of `feols` accepts a function argument. So you can do this easily (I call the function ``Spatial HAC`` just so it prints better):

``` r
library(fixest)
set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10)) - 50, each = 20)
lon <- rep(matrix(runif(10)) + 40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon) * 500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y, X, unit, time, lat, lon)

`Spatial HAC` <- function(x, ...) {
  vcov_conley(x, lat = ~lat, lon = ~lon, cutoff = 10) +
    vcov_NW(x, time = ~time, unit = ~unit) -
    vcov(x, "hc1")
}

# Estimation
fe_model <- feols(
  y ~ X1 + X2 | unit,
  data = df, vcov = `Spatial HAC`
)
fe_model
#> OLS estimation, Dep. Var.: y
#> Observations: 200
#> Fixed-effects: unit: 10
#> Standard-errors: Spatial HAC 
#>    Estimate Std. Error  t value   Pr(>|t|)    
#> X1 -2.17279   0.342462 -6.34461 1.6237e-09 ***
#> X2  2.07009   0.700696  2.95434 3.5340e-03 ** 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 6.39587     Adj. R2: 0.998886
#>                 Within R2: 0.165189
```

<sup>Created on 2025-02-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mmeleseg** [comment]
This is great. Thank you!

**Comment by mmeleseg** [comment]
Hi @kylebutts,

Sorry to bother you again. I was comparing the SEs generated using fixest as you recommended above and the conleyreg packages, and it seems like the two output different results. 


library(fixest)
library(conleyreg)

set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10)) - 50, each = 20)
lon <- rep(matrix(runif(10)) + 40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon) * 500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y, X, unit, time, lat, lon)

`Spatial HAC` <- function(x, ...) {
  vcov_conley(x, lat = ~lat, lon = ~lon, cutoff = 10) +
    vcov_NW(x, time = ~time, unit = ~unit, lag=5) -
    vcov(x, "hc1")
}

# fixest
fixest_model <- feols(y ~ X1 + X2 | unit, data = df, vcov = `Spatial HAC`)
fixest_model

# conleyreg
conleyreg_model <-  conleyreg(y ~ X1 + X2 | unit, data = df, 
          dist_cutoff=10,lag_cutoff=5,unit = "unit", time = "time",lat="lat",lon="lon")
conleyreg_model


I understand there are potential `differences` between the two packages in the kernels used or how distance is calculated.  Do you think the above differences in the SEs between the two packages are likely due to those factors?

**Comment by kylebutts** [comment]
Hi @mmeleseg, doing some digging, the results match for Newey-West and HC1 estimators. But, they differ greatly for conley. I'm not sure why the results are so different


``` r
library(fixest)
library(conleyreg)
set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10)) - 50, each = 20)
lon <- rep(matrix(runif(10)) + 40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon) * 500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y, X, unit, time, lat, lon)

# Conley does not match: 
conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 10, 
  lag_cutoff = 0,
  unit = "unit", time = "time",
  lat = "lat", lon = "lon",
  verbose = FALSE
)
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Not addressing serial correlation because lag_cutoff is zero
#> 
#> t test of coefficients:
#> 
#>    Estimate Std. Error t value  Pr(>|t|)    
#> X1 -2.17279    0.50288 -4.3207 2.517e-05 ***
#> X2  2.07009    0.44139  4.6899 5.244e-06 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

feols(
  y ~ X1 + X2 | unit,
  data = df, 
  vcov = conley(cutoff = 10),
  ssc = ssc(adj = FALSE, cluster.adj = FALSE)
)
#> OLS estimation, Dep. Var.: y
#> Observations: 200
#> Fixed-effects: unit: 10
#> Standard-errors: Conley (10km) 
#>    Estimate Std. Error  t value   Pr(>|t|)    
#> X1 -2.17279   0.392600 -5.53436 9.8771e-08 ***
#> X2  2.07009   0.688008  3.00882 2.9652e-03 ** 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 6.39587     Adj. R2: 0.998886
#>                 Within R2: 0.165189

# Newey-West matches:
conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 0, 
  lag_cutoff = 1,
  unit = "unit", time = "time",
  lat = "lat", lon = "lon",
  verbose = FALSE
)
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> 
#> t test of coefficients:
#> 
#>    Estimate Std. Error t value  Pr(>|t|)    
#> X1 -2.17279    0.48098 -4.5174 1.104e-05 ***
#> X2  2.07009    0.44559  4.6458 6.356e-06 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

feols(
  y ~ X1 + X2 | unit,
  data = df, 
  panel.id = ~ unit + time,
  vcov = NW(1),
  ssc = ssc(adj = FALSE, cluster.adj = FALSE)
)
#> OLS estimation, Dep. Var.: y
#> Observations: 200
#> Fixed-effects: unit: 10
#> Standard-errors: Newey-West (L=1) 
#>    Estimate Std. Error  t value   Pr(>|t|)    
#> X1 -2.17279   0.480981 -4.51740 0.00023569 ***
#> X2  2.07009   0.445586  4.64577 0.00017624 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 6.39587     Adj. R2: 0.998886
#>                 Within R2: 0.165189

# HC1 matches:
conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 0, 
  lag_cutoff = 0,
  unit = "unit", time = "time",
  lat = "lat", lon = "lon",
  verbose = FALSE
)
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Not addressing serial correlation because lag_cutoff is zero
#> 
#> t test of coefficients:
#> 
#>    Estimate Std. Error t value  Pr(>|t|)    
#> X1 -2.17279    0.50311 -4.3187 2.537e-05 ***
#> X2  2.07009    0.44177  4.6859 5.337e-06 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

feols(
  y ~ X1 + X2 | unit,
  data = df, 
  panel.id = ~ unit + time,
  vcov = "HC1",
  ssc = ssc(adj = FALSE, cluster.adj = FALSE)
)
#> OLS estimation, Dep. Var.: y
#> Observations: 200
#> Fixed-effects: unit: 10
#> Standard-errors: Heteroskedasticity-robust 
#>    Estimate Std. Error  t value   Pr(>|t|)    
#> X1 -2.17279   0.503109 -4.31872 2.5375e-05 ***
#> X2  2.07009   0.441774  4.68586 5.3374e-06 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 6.39587     Adj. R2: 0.998886
#>                 Within R2: 0.165189
```

<sup>Created on 2025-02-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mmeleseg** [comment]
Hi @kylebutts , thanks for looking into this. I find similar patterns using actual data (the fixest conley standard errors are smaller than those obtained from conleyreg). In addition, for some regressions, fixest returns "NA" for the conley standard errors while the conleyreg package produces them. 

I am not sure which package is producing the correct SEs. @lrberge, would it be possible to look into this to confirm that fixest is producing the correct SEs?

**Comment by lrberge** [comment]
From what I remember, I had found an issue in the way the package `conleyreg` computed the SEs. But _mea culpa_, I didn't report... The issue was a double counting of the diagonal in `conleyreg` (again: from what I remember).

When writing the conley function in c++, I took a lot of time ensuring it was the exact mathematical formula that was computed. So I hope this is correct!

To check it it is right or wrong, one good way is to look at equivalences. 

Below I create a data set where you have three groups of 50 observations, call the groups A, B and C. Each observation in group A is close (geographically) to the others of group A, but far from the observations in groups B and C. The maximum distance between two observations of group A is 111km. Same for the other groups. 

This means that with a cutoff of 200km, the conley SEs allow a correlation between each pair of observation in group A, but no correlation with the observations from groups B and C. Same for groups B and C. In other words, with a 200km cutoff, Conley SEs are identical to clustered SEs (with clusters A, B and C).

Maybe it's just an SSC problem in conleyreg, but at least this sanity check works for fixest:
```R
# Checking the value of Conley SEs with equivalences
# we generate data that leads to simple values
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

# scattered along 111km
base$lat = rep(seq(-0.5, 0.5, length.out = 50), 3)

# scattered across very long distances
base$lon = rep(c(0, 80, 160), each = 50)

est = feols(y ~ x1, base)

# Equivalence 1 -- clustered SEs
se_clu = se(est, ~lon + ssc(adj = FALSE, cluster.adj = FALSE))
se_conley_fixext = se(est, conley(200) ~ ssc(adj = FALSE))
se_conley_conleyreg = conleyreg(y ~ x1, base, 200,  lat = "lat", lon = "lon")[, 2]
cbind(se_clu, se_conley_fixext, se_conley_conleyreg)
#>                se_clu se_conley_fixext se_conley_conleyreg
#> (Intercept) 0.7643668        0.7643668           0.6872362
#> x1          0.3309842        0.3309842           0.2977460
````

**Comment by kylebutts** [comment]
Clever example @lrberge!! The difference is just based on the kernel (they default to Bartlett, not uniform).

``` r
library(fixest)
library(conleyreg)
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

# scattered along 111km
base$lat = rep(seq(-0.5, 0.5, length.out = 50), 3)

# scattered across very long distances
base$lon = rep(c(0, 80, 160), each = 50)

est = feols(y ~ x1, base)

# Equivalence 1 -- clustered SEs
vcov(est, ~ lon + ssc(adj = FALSE, cluster.adj = FALSE))
#>             (Intercept)         x1
#> (Intercept)   0.5842566 -0.2430770
#> x1           -0.2430770  0.1095505

vcov(est, conley(200) ~ ssc(adj = FALSE))
#>             (Intercept)         x1
#> (Intercept)   0.5842566 -0.2430770
#> x1           -0.2430770  0.1095505

conleyreg(
  y ~ x1,
  base,
  200,
  lat = "lat",
  lon = "lon",
  kernel = "uniform"
)
#> Checking spatial attributes
#> Estimating model
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Estimating distance matrix and addressing spatial correlation
#>             (Intercept)         x1
#> (Intercept)   0.5842566 -0.2430770
#> x1           -0.2430770  0.1095505
```

<sup>Created on 2025-02-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mmeleseg** [comment]
Thank you both for your detective work! 

Does fixest allow you to choose the kernel? The Bartlett kernel seems reasonable in a context where one may want to assign more weight to closer units.

**Comment by kylebutts** [comment]
This is not currently supported. It might be nice to add, but it's worth noting they are different estimators that are both valid under the same assumptions. Note that the choice of a uniform kernel does *not* imply that closer units can not have more correlation; it's just changing your local nonparametric estimator.

**Comment by mmeleseg** [comment]
That sounds good. Thanks!!

**Comment by amarbler** [comment]
Hi,

@kylebutts I’m having trouble reproducing the spatial HAC covariance matrix using your custom function (vcov_spatial_HAC) using conleyreg(). I can replicate the other covariance matrices (vcov_NW, vcov_conley, and vcov_HC1) correctly between fixest and conleyreg. The only discrepancy is with the spatial HAC matrix. 

Could you help clarify whether there might be an issue with conleyreg() itself or with the way vcov_conley, vcov_NW, and vcov_HC1 are combined to compute the spatial HAC covariance matrix?

Below is the full reproducible example:
```
library(fixest)
library(conleyreg)

# run your previous example:
set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10)) - 50, each = 20)
lon <- rep(matrix(runif(10)) + 40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon) * 500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y, X, unit, time, lat, lon)

## Conley
vcov_conley_fixest = vcov_conley(
  feols(
  y ~ X1 + X2 | unit,
  data = df), 
  cutoff = 10, 
  lon = "lon", 
  lat = "lat", 
  ssc = ssc(adj = F))

vcov_conley_conleyreg = conleyreg(
  y ~ X1 + X2 | unit, 
  data = df, 
  dist_cutoff = 10, 
  lon = "lon", 
  lat = "lat", 
  unit = "unit", 
  kernel = "uniform", 
  vcov = T)

vcov_conley_fixest; vcov_conley_conleyreg
           X1         X2
X1 0.15413445 0.04226258
X2 0.04226258 0.47335452
           X1         X2
X1 0.15413445 0.04226258
X2 0.04226258 0.47335452

## NW
vcov_NW_fixest = vcov_NW(
  feols(
  y ~ X1 + X2 | unit,
  data = df), 
  lag = 2, 
  unit = "unit", 
  time = "time", 
  ssc = ssc(adj = F, cluster.adj = F))

vcov_NW_conleyreg = conleyreg(
  y ~ X1 + X2 | unit, 
  data = df, 
  lag_cutoff = 2, 
  dist_cutoff = 0, 
  lon = "lon", 
  lat = "lat", 
  unit = "unit", 
  time = "time", 
  kernel = "uniform", 
  vcov = T)

vcov_NW_fixest; vcov_NW_conleyreg
           X1         X2
X1 0.21710911 0.02298383
X2 0.02298383 0.20730908
           X1         X2
X1 0.21710911 0.02298383
X2 0.02298383 0.20730908

## HC1
vcov_HC1_fixest = vcov(
  feols(
  y ~ X1 + X2 | unit,
  data = df), 
  "HC1", 
  ssc = ssc(adj = F, cluster.adj = F))

vcov_HC1_conleyreg = conleyreg(
  y ~ X1 + X2 | unit, 
  data = df, 
  lag_cutoff = 0, 
  dist_cutoff = 0, 
  lon = "lon", 
  lat = "lat", 
  unit = "unit", 
  time = "time", 
  kernel = "uniform", 
  vcov = T)

vcov_HC1_fixest; vcov_HC1_conleyreg
          X1        X2
X1 0.2531187 0.0449278
X2 0.0449278 0.1951640
          X1        X2
X1 0.2531187 0.0449278
X2 0.0449278 0.1951640

## Spatial HAC
vcov_spatial_HAC_fixest = vcov_conley_fixest + vcov_NW_fixest - vcov_HC1_fixest
vcov_spatial_HAC_conleyreg = vcov_conley_conleyreg + vcov_NW_conleyreg - vcov_HC1_conleyreg

vcov_spatial_HAC_fixest; vcov_spatial_HAC_conleyreg
           X1         X2
X1 0.11812483 0.02031861
X2 0.02031861 0.48549958
           X1         X2
X1 0.11812483 0.02031861
X2 0.02031861 0.48549958

# which is different from calling conleyreg spatial HAC directly::
conleyreg(
  y ~ X1 + X2 | unit, 
  data = df, 
  lag_cutoff = 2, 
  dist_cutoff = 10, 
  lon = "lon", 
  lat = "lat", 
  unit = "unit", 
  time = "time", 
  kernel = "uniform", 
  vcov = T)
           X1         X2
X1 0.21573498 0.02501011
X2 0.02501011 0.20528767
```

**Comment by kylebutts** [comment]
Prefacing this by saying I'm not an expert on `conleyreg`'s codebase.

``` r
library(fixest)
library(conleyreg)

# run your previous example:
set.seed(1)
unit <- rep(1:10, each = 20)
time <- rep(1:20, len = 100)
lat <- rep(matrix(runif(10)) - 50, each = 20)
lon <- rep(matrix(runif(10)) + 40, each = 20)

X <- matrix(rnorm(1000), nrow = 200)
Z <- (lat - lon) * 500 + matrix(rnorm(200, sd = 5))
y <- X %*% c(-2, 2, 4, 0, 0) + Z
df <- data.frame(y, X, unit, time, lat, lon)

vcov_conley(
  feols(
    y ~ X1 + X2 | unit,
    data = df
  ),
  cutoff = 10,
  lon = "lon",
  lat = "lat",
  ssc = ssc(adj = F)
)
#>            X1         X2
#> X1 0.15413445 0.04226258
#> X2 0.04226258 0.47335452

conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 10,
  lon = "lon",
  lat = "lat",
  unit = "unit",
  kernel = "uniform",
  vcov = T
)
#> Checking spatial attributes
#> Estimating model
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Estimating distance matrix and addressing spatial correlation
#>            X1         X2
#> X1 0.15413445 0.04226258
#> X2 0.04226258 0.47335452
conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 10,
  lag_cutoff = 0,
  lon = "lon",
  lat = "lat",
  unit = "unit",
  time = "time",
  kernel = "uniform",
  vcov = T
)
#> Checking spatial attributes
#> Balanced panel identified
#> Estimating model
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Estimating distance matrix and addressing spatial correlation
#> Not addressing serial correlation because lag_cutoff is zero
#>            X1         X2
#> X1 0.25174459 0.04695408
#> X2 0.04695408 0.19314262
conleyreg(
  y ~ X1 + X2 | unit,
  data = df,
  dist_cutoff = 10,
  lag_cutoff = 100,
  lon = "lon",
  lat = "lat",
  unit = "unit",
  time = "time",
  kernel = "uniform",
  vcov = T
)
#> Checking spatial attributes
#> Balanced panel identified
#> Estimating model
#> Warning: In fixest_env(fml = fml, data = data, weights = weig...:
#>  OpenMP not detected: cannot use 12 threads, single-threaded mode instead.
#> Estimating distance matrix and addressing spatial correlation
#> Addressing serial correlation
#>            X1         X2
#> X1 0.15565317 0.04148862
#> X2 0.04148862 0.43903610
```

It appears that what `conleyreg` is doing is combining the spatial distance and time-period distance into a single weight when creating the meat that way. This is different than ours that allows arbitrary *across-time-period* correlation with spatial decay. 

I think there isn't a single right answer, see VD of: https://cameron.econ.ucdavis.edu/research/Cameron_Miller_Cluster_Robust_October152013.pdf. I think it's similar to whether you should cluster at the unit level or do a Newey-West procedure in panel data

**Comment by amarbler** [comment]
That seems reasonable. Thank you for the quick reply!

**Comment by cdueben** [comment]
Hi. `conleyreg` author here. I just learned about this discussion.

Back when I wrote `conleyreg`, I made sure that my results are in line with those of earlier implementations (that does not include `fixest` because `fixest` did not have a Conley implementation at the time). I have not checked whether that still holds. Dependencies changing their output might affect `conleyreg` downstream.

Do I correctly conclude from this issue that `conleyreg` results are econometrically correct and only differ from `fixest` because of different assumptions?

Btw, I have no plans of conducting any work on `conleyreg`, beyond minor maintenance. Potential contributors are welcome to join the project and move it forward.

**Comment by kylebutts** [comment]
Hi @cdueben, thanks for jumping in

> It appears that what conleyreg is doing is combining the spatial distance and time-period distance into a single weight when creating the meat that way. This is different than ours that allows arbitrary across-time-period correlation with spatial decay.

This is correct about `conleyreg`, right? If so, then yes it’s econometrically correct. Just a different assumption on the spatial-temporal dependence

**Comment by cdueben** [comment]
Great. Thanks, for the confirmation.
