### ISSUE TITLE
Feature request: Binning with sunab interactions

### ISSUE THREAD

**Issue by imccart** [lrberge/fixest#181]
Is it possible to introduce some additional flexibility with the sunab interactions to allow for binning of treatment periods? e.g. if individuals are treated in years 2012-2018, but we want to group the 2016-2018 treatment years together for a single event study coefficient on those treatment periods.

I don't think this is possible via the existing ref.p or ref.c options.

**Comment by lrberge** [comment]
Hi, currently this is not possible, so you have to do it beforehand, in the data preparation stage.
But the on-the-fly binning (when using `i` or `sunab`) is in the to-do list for a while now, I'll try to implement it, I'll let you know.

**Comment by lrberge** [comment]
Hi, that's in the new version:

```R
data(base_stagg)
base = base_stagg
base$year = base$year + 2008
base$year_treated = base$year_treated + 2008

res = feols(y ~ x1 + sunab(year_treated, year, bin = 2016:2018), base)
etable(res)
#>                               res
#> Dependent Var.:                 y
#>                                  
#> (Intercept)       0.0219 (0.0550)
#> x1              1.004*** (0.0203)
#> year = -7        -0.2499 (0.3361)
#> year = -6        -0.2054 (0.2942)
#> year = -5         0.0037 (0.2629)
#> year = -4        -0.2301 (0.2410)
#> year = -3        -0.3033 (0.2245)
#> year = -2         0.1253 (0.2104)
#> year = 0         -4.269* (0.1595)
#> year = 1         -2.962* (0.2104)
#> year = 2          -1.208 (0.2241)
#> year = 3          0.3856 (0.2413)
#> year = 4          2.299. (0.2637)
#> year = 5          4.126* (0.2934)
#> year = 6          5.959* (0.3380)
#> _______________ _________________
#> S.E. type                     IID
#> Observations                  950
#> R2                        0.83463
#> Adj. R2                   0.82544
```

Just use `bin` and it should work.
