### ISSUE TITLE
Non-deterministic standard errors 

### ISSUE THREAD

**Issue by whitfillp** [lrberge/fixest#182]
I am running into a problem using feols where the standard errors are not the same every time you run a regression! You can run a regression, then immediately run the same regression and get different standard errors. The point estimates do not change. Let me be precise about the situation I am running into this problem since it only appears in this specialized case. 

I have a panel dataset. I have a time-varying Y, time-invariant D and a time-invariant Z. I am trying to run (Y ~ 1|year| year:D ~ year:Z) The coefficients on year:D have the changing standard errors. These standard errors move around and are sometimes all NAs.

I've attached the dataset where this error appears 
[error_df.csv](https://github.com/lrberge/fixest/files/7017616/error_df.csv)

Load this dataset into R, then run 
df$year <- as.factor(df$year)

results <- feols(data = df, y ~ 1|year| D:year ~ Z:year)
summary(results)

about 10 times. You can then verify that the standard errors are not the same in all 10 tries.

**Comment by lrberge** [comment]
Oooo, I confirm the very very odd bug. 

Thanks a lot for the reproducible example! I'll try to take care of it soon.

**Comment by lrberge** [comment]
Hi, finally got it. There was a race condition that I didn't spot in the parallel loop computing the standard-errors. Now fixed.

Thanks again for the clear report!
