### ISSUE TITLE
Predictions using predict.fixest with varying slopes after | (in FEs)

### ISSUE THREAD

**Issue by cseveren** [lrberge/fixest#187]
When running a model like `p1 <- feols(y ~ x1 | year[x2], combine_quick=FALSE)` and then using the newly added support for fixed effect predictions, e.g., `predict(p1, fixef=TRUE)`, the values saved to the output data frame are the year-varying coefficients on `x2`, not the predicted value of this coefficient multiplied by the appropriate value of `x2`.  Is this intended behavior? If so, it may be useful to clarify this in the documentation for `predict`.  I had initially assumed it would be the coefficient multiple by the appropriate value of `x2`. 

This post is closely related to issues #144 and #175, which were resolved in version [0.10.0](https://lrberge.github.io/fixest/news/index.html). As always, thank you for excellent work on this package!

**Comment by lrberge** [comment]
Hi! Just to mention that I've added an option when the data contained variables with varying slopes. 
By default you get the `coef*var` value but you can use `vs.coef` to just have the coefficient instead.
Hope this helps!

**Comment by cseveren** [comment]
Awesome, thanks!
