### ISSUE TITLE
Bias correction in two- and three-way fixed effects PPML models

### ISSUE THREAD

**Issue by ChristianDueben** [lrberge/fixest#189]
Hi Laurent,

I do not know, if you came across it, but there is a paper by [Weidner and Zylkin (2021)](https://www.sciencedirect.com/science/article/pii/S0022199621000933) who show that some fixed effects PPML models produce incorrect results. These authors also published a [Stata package](https://github.com/tomzylkin/ppml_fe_bias) correcting for that bias. Unfortunately, that package is, like many other Stata functions, pretty slow. Do you plan on adding that error correction to fixest?

Kind regards,
Christian

**Comment by lrberge** [comment]
Hi Christian, I apologize in advance for the disappointing answer:

Since I'm not really working with these kind of models I have no plan to implement it. 
But maybe someone from the community is willing to implement it?

Sorry again!
Laurent
