### ISSUE TITLE
fixef vs. plm::fixef and lfe::getfe for IV models

### ISSUE THREAD

**Issue by tappek** [lrberge/fixest#190]
I have just fixed a bug in `plm::fixef` in the development version of the package; `plm::fixef` errored for IV models. I wanted to check results vs. `fixest::fixef` and found diverging results for the IV case (for ordinary regression models, both packages match, also vs. `lfe::getfe`).

`plm::fixef` agrees with `lfe::getfe` for ordinary models and for balanced IV models, unbalanced one-way IV models, and balanced two-way IV models, but not for unbalanced two-way IV models. **Update**: `plm::fixef` and `lfe::getfe` agree also for unbalanced two-way IV models; it seems just that `lfe::getfe` chooses the reference categroy based on the unbalancedness pattern which makes it somewhat random for the user (https://github.com/sgaure/lfe/issues/52).

So, I think there is something a little fishy here between the packages but did not find the root cause for diverging results in IV cases vs. `fixest::fixef`.

Any ideas?

I have made an extensive test file for ordinary regression models and IV models one-way and two-way balanced and unbalanced cases.  It requiers plm development version rev. 1294 (or higher), https://r-forge.r-project.org/R/?group_id=406, install by:
`install.packages("plm", repos="http://R-Forge.R-project.org")`

test file (IV cases from line 207 onwards):
https://gist.github.com/tappek/3f8ccbe1eef4dc25632e5a2a4e373b4a#file-test_fixef-r

**Comment by lrberge** [comment]
Thanks a lot for reporting! Indeed, I didn't compute correctly the sum of the fixed-effects when IVs are present in the second stage, leading to erroneous FE coefficients. 
Thanks a lot again, that's an important bug -- and your issue was very clear, it's always pleasant!

**Comment by tappek** [comment]
I confirm results match with the current development versions of fixest and plm. Thank you for turning so quickly to this!
