### ISSUE TITLE
update on predicted CI

### ISSUE THREAD

**Issue by gbekes** [lrberge/fixest#193]
Hi Laurent,

I would like to ask if there has been an update on the standard errors/CIs to `predict.fixest`. As I have seen in the issues, there are some candidate solutions (e.g., the `relpred` function or `se.fit.fixest`), but none of them considers predicting newdata with any types of data (`relpred` is the closest, but it is not implemented in the newer versions and the available function can not handle non-numeric variables). 
I would be only interested in the predicted standard errors for feols() with simple x-sec setup, so nothing fancy...

Could this be part of 0.10.0 release?

Cheers
Gabor

**Comment by lrberge** [comment]
Hi Gábor, 
Could you detail what you have exactly in mind? 
For me this topic can be very confusing since everyone has something different in mind when looking at the SEs of the predictions. 
Could you mathematically express (like in https://github.com/lrberge/fixest/issues/22#issuecomment-792906531) what you have in mind so that we'll be sure to be on the same page?
Best,
Laurent

**Comment by gbekes** [comment]
Hi Laurent
I am after two things (related to my textbook, as I am updating the [code ](https://github.com/gabors-data-analysis/da_case_studies/tree/master/ch09-gender-age-earnings) from estimateR to fixest:

1. confidence interval (CI) of the predicted value 
	- this is mentioned in the forum, but I found no implementation
	- what I would like to have a measure on SE(E(y|x))=SE(x’b)
2.  prediction interval (PI) 
	- this is not mentioned in the forum or I have not seen it
	- what I would like to have a measure on SE(\hat{y}) = SE(x’b + u)

Hope it helps!

**Comment by gbekes** [comment]
Xsec I mean, simple cross section, no panel, no fixed effects.

**Comment by lrberge** [comment]
Ahh cross section -- sorry I didn't see it! 
It makes the request much more simple to deal with! :-)
I'll let you know! Thanks for clarifying!

**Comment by gbekes** [comment]
Yes, indeed. 
It's all part of Rstats code refcatoring, making fixest the default regression package for my [Data Analysis textbook](https://gabors-data-analysis.com/).
Cheers!

**Comment by lrberge** [comment]
Hi, I've just added it. Note that it's very limited though: only OLS and no fixed-effects.
Hope it's useful still!

**Comment by gbekes** [comment]
This is awesome, and works! Thanks!!!!
