### ISSUE TITLE
coefplot with lean=TRUE and clusters error

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#195]
Using the latest version my code throws the following error when trying to run a coefplot() on a fixest object estimated with the options cluster = c(...) and lean = TRUE set:

```
Error in coefplot_prms(object = object, ..., sd = sd, ci_low = ci_low,  :
  The first element of 'object' raises and error:
Error in vcov.fixest(object, vcov = vcov, ssc = ssc, forceCovariance = forceCovariance,  :
  VCOV of 'lean' fixest objects cannot be computed. Please re-estimate with 'lean = FALSE'.
```

Why is it trying to recompute VCOV?

**Comment by lrberge** [comment]
Could you send the lines before?

**Comment by adamaltmejd** [comment]
Awesome, that was fast! Thanks! :)

**Comment by lrberge** [comment]
The decision tree of when updating the vcov is actually not so straightforward. 

The previous code worked for user-level calls but not for calls within functions. That's not 100% corrected yet but the problems are restricted to very niche cases only.

**Comment by adamaltmejd** [comment]
Interesting. Seems to work for my use case at least, thank you!
