### ISSUE TITLE
Looping through multiple treatment variables in staggered DiD

### ISSUE THREAD

**Issue by vronizor** [lrberge/fixest#196]
Hi and thanks for the great package!

This is more of a question than a bug report—if there's a better place to file this please let me know.

I'm working on a project with multiple treatment definitions (9), using staggered difference-in-difference in both flavors you offer (TWFE and SA20). For each treatment definition and observation, I have years to treatment, whether it receives treatment (for the TWFE setup with `i()`) and treatment year (for the `sunab()` function). 

What would be the best way to loop through these treatment definitions in a code-efficient way? Below is my current solution, but it's quite wordy (edited for readability). `t#` is a single treatment definition.

```r
#---- Set up shortcuts ----#

## Controls ##

setFixest_fml(..cntrls = ~pop + income + educ)

## TWFE ##

setFixest_fml(..t1_twfe = ~ i(year.to_t1, ever.t_t1, ref = c(-1, -1000)))
setFixest_fml(..t2_twfe = ~ i(year.to_t2, ever.t_t2, ref = c(-1, -1000)))
setFixest_fml(..t3_twfe = ~ i(year.to_t3, ever.t_t3, ref = c(-1, -1000)))

## SA20 ##

setFixest_fml(..t1_sa = ~ sunab(t.year_t1, year))
setFixest_fml(..t2_sa = ~ sunab(t.year_t2, year))
setFixest_fml(..t3_sa = ~ sunab(t.year_t3, year))

#---- Estimation ----#

# I can only use the step-wise function once per part 
# --> repeat the treatment variable with controls in s()

e_twfe = feols(c(y1, y2) ~ 
                sw(..t1_twfe, ..t1_twfe +  ..cntrls,
                   ..t2_twfe, ..t2_twfe +  ..cntrls,
                   ..t3_twfe, ..t3_twfe +  ..cntrls) | 
                id + year, 
               cluster = ~cluster, panel)


e_sunab = feols(c(y1, y2) ~ 
                 sw(..t1_sa, ..t1_sa +  ..cntrls,
                    ..t2_sa, ..t2_sa +  ..cntrls,
                    ..t3_sa, ..t3_sa +  ..cntrls) | 
                 id + year, 
                cluster = ~cluster, panel)
```

1. Would there be a way to programmatically create the shortcuts?
2. Would there be a way to capture all the shortcuts in list and loop through them?
3. Another method entirely?

Not sure if I'm missing an important trick already available in the package or just R wizardry to make this more efficient... Thanks!

**Comment by lrberge** [comment]
Hi! 

The problem is that you have many specifications and they have to be spelled out at some point. So far, there is no way to do it in only one line of code.

Since the variable names are strongly formatted, the easiest way to deal with all estimations is a loop:

```R
setFixest_fml(..ctrl = ~pop + income + educ)

res = list()
for(method in c("twfe", "sunab")){
  res_sub = vector("list", 9)
  for(i in 1:9){
    var = switch(method,
                 twfe = "i(year.to_t.[i], ref = c(-1, -1000))",
                 sunab = "sunab(t.year_t.[i], year)")

    res_sub[[i]] = feols(c(y1, y2) ~ csw(.[var], ..ctrl), panel, ~cluster)
  }
  
  res[[method]] = res_sub
}
```

The previous code uses a new feature I've just introduced: the `.[]` operator for formulas. It fetches the values from the environment and plugs them in the formula.
For example:
```R
base = setNames(iris, c("y", "x1", "x2", "x3", "species"))
i = 2:3
z = "i(species)"
feols(y ~ x.[i] + .[z], base)
#> OLS estimation, Dep. Var.: y
#> Observations: 150 
#> Standard-errors: IID 
#>                      Estimate Std. Error   t value   Pr(>|t|)    
#> (Intercept)          3.682982   0.107403 34.291343  < 2.2e-16 ***
#> x2                   0.905946   0.074311 12.191282  < 2.2e-16 ***
#> x3                  -0.005995   0.156260 -0.038368 9.6945e-01    
#> species::versicolor -1.598362   0.205706 -7.770113 1.3154e-12 ***
#> species::virginica  -2.112647   0.304024 -6.948940 1.1550e-10 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 0.333482   Adj. R2: 0.832221
```

By the way, please note that the interacted variable `ever.t_t` is not needed in TWFE: the reference deals with it already (I've updated the example in the vignette [I actually kept it in the vignette only to make `coefplot` work, but since the introduction of `iplot` the interaction is not needed any more]).

In terms of efficiency, the function `csw` is faster than `sw` and so compensates the loop.

I don't know if it helps, but I hope so!

**Comment by vronizor** [comment]
Hi!

Thank you so much for your answer, as always extremely helpful! The `.[]` operator was just what I needed :-). And thanks for letting me know about the unnecessary `ever.t_t`—always good to get rid of superfluous code.
