### ISSUE TITLE
Rounding to 5 digits in output

### ISSUE THREAD

**Issue by hjuerges** [lrberge/fixest#197]
I noticed that the standard feols() output seems to round to 5 significant digits, which can be confusing if the output is compared with equivalent estimation procedures. The following example replicates the recent Wooldridge (2021) Stata code in R:

### load data
library(tidyverse)
library(fixest)

data("nsw_mixtape", package = "causaldata")

### turn to long
df <- nsw_mixtape |> mutate(ID = row_number()) |> 
  rename(x74 = re74) |> 
  pivot_longer(starts_with("re"),
               names_to = "year",
               names_prefix = "re",
               values_to = "inc")

### rename vars as in Wooldridge and use educ as single covariate
df$y <- df$inc
df$w <- ifelse(df$treat==1 & df$year==78,1,0)
df$x <- df$educ
df$d <- df$treat
df$f <- ifelse(df$year==78,1,0)
df$x_dm = df$x-mean(df[df$d==1,]$x)

### note how the coefs are rounded and trailing zeros added
feols(y ~ w + w:x_dm + f + f:x | ID, data = df)

        Estimate Std. Error   t value Pr(>|t|))    
    w      1529.8000     712.00  2.148600  0.032206 *  
    f      3311.7000    1814.80  1.824900  0.068689 .  
    w:x_dm  684.1900     321.55  2.127800  0.033907 *  
    f:x      -2.3635     178.88 -0.013213  0.989464    

### does not happen with coeftable()
feols(y ~ w + w:x_dm + f + f:x | ID, data = df) |> 
  coeftable()

          Estimate Std. Error     t value  Pr(>|t|))
    w      1529.804639   711.9998  2.14860249 0.03220609
    f      3311.735851  1814.7573  1.82489189 0.06868911
    w:x_dm  684.185842   321.5518  2.12776234 0.03390713
    f:x      -2.363467   178.8804 -0.01321255 0.98946415
      attr(,"type")
     [1] "Clustered (ID)"

**Comment by lrberge** [comment]
Indeed, that was weird. Now corrected, thanks.
