### ISSUE TITLE
Newey and West (1994) auto lag selection

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#198]
Glad to see that you have added the Newey and West (1987) adjusted standard error. Do you have any plan to implement the Newey and West (1994) auto lag selection feature? The sandwich::NeweyWest function has this feature.

**Comment by lrberge** [comment]
That's a timely comment.  I've discussed this issue with Achim recently (`sandwich`'s author). I won't code it up myself and will rely on sandwich's `bwNeweyWest`. I just need to take the time to make sure everything works fine. It's just a matter of weeks. I'll let you know!

**Comment by lrberge** [comment]
To let you know: In the current dev version, now the default is to use the `bwNeweyWest` function from `sandwich`.

**Comment by waynelapierre** [comment]
Gee, that's quick!
