### ISSUE TITLE
make etable not show footnote

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#199]
How to make etable not show footnote when style.tex = style.tex(main = "base")?

**Comment by lrberge** [comment]
You can use `tablefoot = FALSE` to remove the footnote. But then to keep the style consistent, you also need to provide the finishing line, which is `"\\midrule\\midrule\\tabularnewline"`.

So the following should work:
```R
style.tex(tablefoot = FALSE, line.bottom = "\\midrule\\midrule\\tabularnewline")
```

Agreed it's a bit complex. I may add another basic style which is "base" without footer, but I'm still in search of a name :-) ("base no footer"? "alt"? "base2"? not satisfied by any yet!)

**Comment by lrberge** [comment]
OK, I found a satisfying (to me ;-)) solution. If you choose style.tex("base", footnote = FALSE), then the table will have double lines at the bottom.
