### ISSUE TITLE
(very minor): etable TeX fixef size row contains unsanitized `#`, which breaks latex compilation 

### ISSUE THREAD

**Issue by apoorvalal** [lrberge/fixest#201]
Noticed a very minor issue that I didn't think would be worth opening a PR for (I fixed it in my fork but want to install your new goodies, so want to get merged in `master`).

This line
https://github.com/lrberge/fixest/blob/d8334bdfad3c4a5e71a352659f157ccf4815caf0/R/etable.R#L3959 and 10 lines below it
adds an unsanitized `#` to the tex export from etable, which in turn breaks compilation. Just needs to be escaped with "\\" to fix.

**Comment by lrberge** [comment]
Thanks! I don't know when I introduced the bug since it was working at some point.... I think before I was escaping ex post but I changed that later on. 
Anyway, now corrected!
