### ISSUE TITLE
Standard errors in fepois

### ISSUE THREAD

**Issue by simon-lowe** [lrberge/fixest#202]
Hi,

First of all, thanks for the amazing package and all the work, it's truly an amazing public service! So this is not really a bug, it's a question on the type of errors computed in fepois. Hopefully this is the right place to ask this question, I couldn't find any details anywhere else. The reason I'm asking is because I'm doing some simulations on a DGP for a paper and the standard errors don't work at all. It is possible that this is a DGP where Poisson does not work, but I first wanted to make sure that I'm not misunderstanding the errors that are computed.

So my question is: What standard errors are computed for fepois? 
A short extract from Wooldridge (2010):
![image](https://user-images.githubusercontent.com/57216897/135597873-a1df74b4-0989-4848-8b89-c15ec9131056.png)

Is it the robust standard error (which as far as I understand is supposed to be the generically correct one) or the "usual" ML? 

Thanks for your help and sorry for the annoying question,
Simon

**Comment by lrberge** [comment]
Hi Simon!

The "basic" VCOV (shown as IID) is in fact A<sup>-1</sup>, the inverse of the Hessian. But one should never use it.
The robust one referred to in the text is known as "hetero" in `fixest`.

Here's a small experiment that shows that the basic one shouldn't be used (that's super slow, sorry):
```R
N = 1000
n_rep = 1000
n_exp = 100

res = vector("list", n_exp)
res_robust = vector("list", n_exp)
for(e in 1:n_exp){
  cat(format(e, width = 3), ":")
  pvalues_all = numeric(n_rep)
  pvalues_robust_all = numeric(n_rep)
  for(r in 1:n_rep){
    if(r %% 500 == 0) cat("|") else if(r %% 100 == 0) cat(".")
    base = data.frame(y = exp(rnorm(N)), x = rnorm(N))
    est = fepois(y ~ x, base)
    pvalues_all[[r]] = est$coeftable[2, 4]
    pvalues_robust_all[[r]] = pvalue(est, vcov = "hetero", keep = "x")
  }
  cat("\n")
  res[[e]] = pvalues_all
  res_robust[[e]] = pvalues_robust_all
}

se_normal = sapply(res, function(x) sum(x < 0.05)) / 1000
se_robust = sapply(res_robust, function(x) sum(x < 0.05)) / 1000
```

The experiment is basic: two variables `x` and `y`, both randomly and independently generated. 
For 100,000 times, I create a sample of 1000 observations, run the Poisson estimation of `y` on `x` and count the number of times `x` is significant at the 5% level.

That's the result:
![image](https://user-images.githubusercontent.com/43536394/135711580-877cdcee-a679-4247-ae40-9d594e60c5fa.png)


Clearly the basic VCOV over-rejects. I guess it's the same phenomenon that you've encountered. 
But that's the way it is, it's not specific to the way `fixest` computes it (it's the same as the one defined in Wooldridge).

Hope it brings some clarifications.
Laurent

**Comment by simon-lowe** [comment]
Ok, thanks a lot! Sorry one more clarification (which is again dumb, just triple checking), the clustered standard errors are automatically robust?
That clarifies that I've found another issue, probably deeper in the applicability of Poisson regression with fixed effects, because I've been using clustered standard errors (and also tried hetero) and I still get egregious under-coverage (in the DGP I'm considering). Anyway that's for me to figure out the econometrics, just wanted to make sure that I wasn't calculating the wrong errors!
Again thanks so much for all the work on this and your very timely response!

**Comment by lrberge** [comment]
Closing then.
