### ISSUE TITLE
Error with weights and fixef.tol too small

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#207]
Hey!

Not sure if this is a bug or simply a feature of my data but thought I'd comment on it anyways cause it took a while for me to understand how to solve it.

When I run a specific RDD model with triangular weights I get the following error. The error disappears when i set fixef.tol to 1e-5 or lower. In the help file it says the default is 1e-5 in the text but it seems to be 1e-6 like in the list of arguments. Using no weights also makes the error disappear. Took a while to figure out I could solve it with the tolerance setting, could maybe me helpful with a more informative error message. Or is this a bug?

```
Error in if (any(opt_fe > 1e-04)) { : 
  missing value where TRUE/FALSE needed
```

Adam

**Comment by lrberge** [comment]
Hi Adam, that's imply a bug, could you share the call? Maybe I have enough hints from it to trace the bug. Otherwise, I would need a replicable example.

**Comment by adamaltmejd** [comment]
Regarding your side comment: The normal RDD specification (with a linear polynomial) would be: `y = b_1 * I(a >= 0) + b_2 * a + b_3 * I(a >= 0) * a` where `a` is the running variable centered at 0 and the coefficient of interest is `b_1`. Now, I'm pooling a large number cutoffs but in this specification I want to estimate a separate linear polynomial above and below the cutoff for each of `n` cutoffs, while still pooling the effect of `I(a >= 0)`:

`y = b_1 * I(a >= 0) + sum_i^n (d_i)  + sum_i^n (g_i * a) + sum_i^n (h_i * I(a >= 0) * a)`

With `d_i` being fixed effects for each cutoff. Do you see why I need to have both `id_cutoff[cutoff_distance]` and `id_cutoff^above_cutoff[[cutoff_distance]]` as the fe specification? If you have any thoughts on how I could make this setup more efficient I'd love to hear it.

**Comment by adamaltmejd** [comment]
Oh right! That makes a lot of sense, thank you. Would that then actually be the same as using only `id_cutoff + id_cutoff^above_cutoff[[cutoff_distance]]` as fe (instead of `id_cutoff[cutoff_distance] + id_cutoff^above_cutoff[[cutoff_distance]]`)? (two slopes per cutoff, one above and one below)
