### ISSUE TITLE
Comparison with `reghdfe`

### ISSUE THREAD

**Issue by Skumin** [lrberge/fixest#209]
Hello,

I'm trying to replicate the results of a paper that uses the Stata `reghdfe` command but keep running into collinearity issues. I've attached the dataset I'm using here: [sample_data.csv](https://github.com/lrberge/fixest/files/7330696/sample_data.csv)

My Stata DO file contains the following:
```
import delimited sample_data.csv, case(preserve)
xtset ID year
reghdfe y l(0/1).delta_t l(0/1).delta_p, absorb(i.fact i.year i.ID i.ID#c.year i.ID#c.year_sqr)
```
which results in the following coefficients:

- delta_t = -0.00243
- lag of delta_t = -0.00652
- delta_p = 0.00175
- lag of delta_p = 0.0195.

How should I specify this model in `fixest`? I've tried e.g.
```
data_fe <- data.table::fread('sample_data.csv')
data_fe_p <- panel(data_fe, ~ ID + year)
feols(y ~ l(delta_t, 0:1) + l(delta_p, 0:1) | fact + ID + year + ID ^ year + ID ^ year_sqr, data = data_fe_p)
```
but this results in `Error: in feols(y ~ l(delta_t, 0:1) + l(delta_p, 0:1) | fac...: All variables'delta_t', 'l(delta_t, 1)' and 2 others are collinear with the fixed effects. In such circumstances, the estimation is void`.

I'm using Stata 13 and R 4.1.1 with `fixest_0.10.0` on Windows 10. Thank you!

**Comment by Skumin** [comment]
Thank you for the response, @lrberge, I missed this in the doc. When I do `feols(y ~ l(delta_t, 0:1) + l(delta_p, 0:1) | fact + ID + year + ID[year], data = data_fe_p)`, I replicate the Stata equivalent call `reghdfe y l(0/1).delta_t l(0/1).delta_p, absorb(i.fact i.year i.ID i.ID#c.year)`, i.e., **without the year_sqr interaction**. Adding it back to the Stata call doesn't change the results there a lot (e.g. the delta_p coefficient goes up to the 0.00175 value from 0.00174), but doing `feols(y ~ l(delta_t, 0:1) + l(delta_p, 0:1) | fact + ID + year + ID[year, year_sqr], data = data_fe_p)` results in something pretty different:
- delta_t = -0.000833
- lag of delta_t = -0.004863
- delta_p = 0.002202
- lag of delta_p = 0.021593.

Any idea why this would be?

**Comment by lrberge** [comment]
Thanks a lot!!! That was really important. The results mean that `fixest`'s results are "right" (I'm relieved!). 

To be honest, it took me immense pains to get an algorithm that deals efficiently with variables with varying slopes (my C++ code was crystal clear before I implemented a new version VS-efficient, now it's a bog I don't penetrate anymore for fear of drowning!).

So I'm happy that this effort was useful! Before that I had convergence problems regarding VSs and `reghdfe` led to more precise results.

So I'm closing then. And thanks a lot for having checked!
