### ISSUE TITLE
Weird package dependency introduces error

### ISSUE THREAD

**Issue by statzhero** [lrberge/fixest#210]
This is probably not `fixest` fault or even its responsibility to solve it, but perhaps you have some insights. The first output works, the second throws an error after loading the additional library.

``` r
library(fixest)
feols(mpg ~ disp + hp, mtcars) |> etable()

library(logistf)
feols(mpg ~ disp + hp, mtcars) |> etable()

Error in as.character(x$fml)[[2]] : subscript out of bounds
```

**Comment by statzhero** [comment]
Yeah this is what I figured. 

Could you specify all instances in the package with `base::as.character`? There may be reasons why this is not wanted of course.

**Comment by tappek** [comment]
See also this issue in pkg `formula.tools` https://github.com/decisionpatterns/formula.tools/issues/11

**Comment by lrberge** [comment]
OK, OK, OK... I've added that one line in the code and it shouldn't conflict anymore.
