### ISSUE TITLE
Headers in etable

### ISSUE THREAD

**Issue by lrberge** [lrberge/fixest#215]
Original post by @bellodi92, migrated from issue #33.

> Thanks for the great package. It would be cool to have the possibility to group headers for multiple models. Something like the custom.header object from texreg. Here's the idea:
> 
> custom.header = list("header_name_for_models_1_2" = 1:2, "header_name_for_models_3_4" = 3:4)

**Comment by Oravishayrizi** [comment]
Hi,
Thx again for your fantastic package, I don't mind opening a new issue, but this one looks pretty related. 
Sometimes one needs more than one row of headers. Is there an easy way to make using `etable` ?

Here is an example from the latest issue of the AER:

![image](https://user-images.githubusercontent.com/30078665/140052887-2db010a4-e5cb-4d8d-8e5a-041ff13da7bb.png)

(BTW, I don't necessarily think of OLS/2SLS, another level of heading could help make two panels, for example. )

**Comment by bellodi92** [comment]
I think I can help with this. Just enter all the headers you want as elements of the headers list. 

![Screen Shot 2021-11-03 at 13 04 50](https://user-images.githubusercontent.com/42752167/140056848-f2c09213-d1b5-4e7d-8be4-263530d0e784.png)

**Comment by Oravishayrizi** [comment]
Fantastic, thank you!

**Comment by lrberge** [comment]
Thanks Luca!

Just a few comments:
1. Now `cmidrule` does not show up for empty columns any more (just noticed that, thanks!)
2. From 0.10.1, you can use `.()` as an alias for `list()` in `extralines` and `headers`.
3. In case you didn't know, I've recently (0.10.1) a powerful (IMO) way to write formulas, so all your estimations can be condensed into only one:
```R
est = feols(y ~ sw(x.[,1:3], x.[1:3]) | species, base)
# Which is equivalent to writing:
est = feols(y ~ sw(x1, x2, x3, x1 + x2 + x3) | species, base)
```
The magic happens in the `.[]` which is a new operator. Of course, the example here is super simple and doesn't really need it. But `.[]` handles variables from the global environment and hence enables to do many things... Anyway, my only point is that it may be worth a try! ;-)

-----

The same code incorporating the previous comments:


![image](https://user-images.githubusercontent.com/43536394/140077716-8e9f1e91-04f1-49b4-a5cc-a64576c8e22c.png)

**Comment by mmeleseg** [comment]
@lrberge Thanks for the above tips. 

In the example that @Oravishayrizi gave above, how would you break the column headers, such as "No controls" or "No Interactions", into multiple lines?

**Comment by lrberge** [comment]
@mmeleseg: this is a Tex question. Use `makecell`:

![image](https://user-images.githubusercontent.com/43536394/140761254-ceb5a376-6e1e-4ec6-93c2-db0414018ccf.png)

**Comment by mmeleseg** [comment]
@lrberge Thank you!
