### ISSUE TITLE
Anderson-Rubin CIs

### ISSUE THREAD

**Issue by NickCH-K** [lrberge/fixest#217]
I have had in the back of my mind for a while the project of adding Anderson-Rubin confidence intervals as an option for **fixest** IV output, or as a postestimation function. It has always been odd to me that there doesn't appear to be a single package that both lets you estimate IV and get AR CI's (and as far as I can tell there's no way to get `ivpack::anderson.rubin.ci()` to work with `feols()` output). And in general AR is too hard to get in all languages/packages!

I haven't even started on this, but would it be a welcome addition? If so, would an additional `se` setting in `feols()` be preferable, or a postestimation function?  (`se` would be kinda neat but since it's a nonsymmetric CI it might not make sense)

**Comment by lrberge** [comment]
Hi Nick! That looks interesting, I didn't know about it (not a big IV user though), but it seems that it's really a CI and not a type of VCOV?

If it is not yielding a VCOV then the integration benefit to `fixest` would be limited. I was thinking instead, maybe making `ivpack` compatible to `fixest` may be a way to go (and it may be simpler)? What do you think?

**Comment by NickCH-K** [comment]
Yes, it's a CI and not really a vcov. Making **ivpack** consistent with **fixest** would make sense then.

**Comment by lrberge** [comment]
Hi Nick, to let you know, we can access to many things that might be of interest with `model.matrix`; so the conversion wouldn't be too painful I think/hope.

Here's an example:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "fe1")
base$x_inst1 = 0.2 * base$x1 + 0.7 * base$x2 + rpois(150, 2)
base$x_inst2 = 0.2 * base$x2 + 0.7 * base$x3 + rpois(150, 3)
base$x_endo1 = 0.5 * base$y + 0.5 * base$x3 + rnorm(150, sd = 2)
base$x_endo2 = 1.5 * base$y + 0.5 * base$x3 + 3 * base$x_inst1 + rnorm(150, sd = 5)

res_iv2 = feols(y ~ x1 + x2 | x_endo1 + x_endo2 ~ x_inst1 + x_inst2, base)

# Regular RHS
head(model.matrix(res_iv2, type = "rhs"), 2)
#>      (Intercept)  x_endo1  x_endo2  x1  x2
#> [1,]           1 2.773595 27.25974 3.5 1.4
#> [2,]           1 4.134388 16.94369 3.0 1.4

# RHS of the 1st stage
head(model.matrix(res_iv2, type = "iv.rhs1"), 2)
#>      (Intercept) x_inst1 x_inst2  x1  x2
#> [1,]           1    5.68    3.42 3.5 1.4
#> [2,]           1    3.58    3.42 3.0 1.4

# RHS of the 2nd stage
head(model.matrix(res_iv2, type = "iv.rhs2"), 2)
#>      (Intercept) fit_x_endo1 fit_x_endo2  x1  x2
#> [1,]           1    1.897422    25.93182 3.5 1.4
#> [2,]           1    2.142116    18.06784 3.0 1.4

# Instruments only
head(model.matrix(res_iv2, type = "iv.inst"), 2)
#>      x_inst1 x_inst2
#> [1,]    5.68    3.42
#> [2,]    3.58    3.42

# Endo vars only
head(model.matrix(res_iv2, type = "iv.endo"), 2)
#>       x_endo1  x_endo2
#> [1,] 2.773595 27.25974
#> [2,] 4.134388 16.94369
```

Closing then. Let me know if there are specific things needed; if they are missing I can make changes to the estimations output accordingly.
