### ISSUE TITLE
signifCode parameter in setFixest_etable() does not work

### ISSUE THREAD

**Issue by mattysimonson** [lrberge/fixest#218]
The `signifCode` parameter can be set within an individual `etable` but it cannot be set globally, despite the fact that it is offered as a parameter in `setFixest_etable()`. Minimal working example:

```
library(fixest)

# set new signifCode
setFixest_etable(signifCode = "letters")

# run model
mod <- feglm(speed ~ dist, cars)

etable(mod)
```
Note that significance is still shown in stars, despite the fact that we set it to "letters". Now let's just check to see if `setFixest_etable` can do other things or if the entire function is broken:
```
setFixest_etable(signifCode = "letters", digits = 2)
etable(mod)
```
sure enough, the problem appears to be limited to the `signifCode` parameter. Does this parameter work within `etable`?

`etable(mod, signifCode = "letters")`

Yes, it does

**Comment by lrberge** [comment]
Hi Matthew, it's a quirk and not really a bug. But I agree it's too confusing so I'm dropping it. Now `tex` and `df` tables align when this parameter is set globally.
