### ISSUE TITLE
Feature Suggestion- view etable's latex output in Rstudio Viewer

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#227]
Hi Laurent,

When I prepare a regression table, I usually improve it by trial and error.
I found it challenging to save the tex file using `etable`, and then compile it outside R using some tex egein.

Recently I found a library that renders small chunks of tex codes within the rstudio viewer pane.

I don't know what's under the hood of the excellent `fixest` package, so I can't estimate the difficulty of implementing this kind of stuff in your library.

I'm attaching the way I implement it in my work, it may be of help for others, and perhaps one day will be implemented more robustly in the package itself.

````
library(texPreview)
library(fixest)

base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
est = feols(y ~ csw(x1, x2), base)

a<-etable(est, title = "This is a test",label="reg_results",
          tex = TRUE,style.tex = style.tex("aer",tabular="*"))

tex_preview(obj = texPreview::as.kable(a),
            usrPackages = "\\usepackage{tabularx} \\usepackage{amssymb} ")  #Latex preamble
````

**Comment by lrberge** [comment]
Hi, that's a good suggestion, and a good candidate for a postprocessing function.

Just run this handful of lines of codes:
```R
my_preview = function(x){
  tex_preview(paste0(x, collapse = "\n"))
  x
}

setFixest_etable(postprocess.tex = my_preview)
```

Now whenever you run `etable` with `tex = TRUE`, like in:
```R
base = setNames(iris, c("y", "x1", "x2", "x3", "species"))
est = feols(y ~ csw(x.[, 1:3]), base)

etable(est, tex = TRUE)
```

You'll get the preview popping. 
I'm not sure it should be internal to the package though (maybe yes), but I'll give it a thought, thanks.

**Comment by lrberge** [comment]
Just to say that I liked the suggestion very much! Now it's in the package, just use `view = TRUE`.
I didn't use `texPreview` in the end because it made my session buggy. To make the preview work, you need pdflatex (which you have), imagemagick and ghostscript. And it should work.

**Comment by Oravishayrizi** [comment]
Looking forward to using it, Thx!
