### ISSUE TITLE
Bug with model.matrix when no collinear fixed effects

### ISSUE THREAD

**Issue by kylebutts** [lrberge/fixest#229]
Small bug found in model.matrix. If there are no collinear fixed effects, this fails. A first check to make sure that there are collinear variables can fix this. Something like: `if(!"collin.var" %in% names(object))`

https://github.com/lrberge/fixest/blob/6c99dfef2653871c9e0f0ed16047b5f7900c828f/R/MiscFuns.R#L7887-L7894

Reprex:

``` r
library(palmerpenguins)
library(fixest)

est <- feols(bill_length_mm ~ 0 | species, data = penguins)
#> NOTE: 2 observations removed because of NA values (LHS: 2).

model.matrix(est)
#> Error in if (length(qui) == ncol(linear.mat)) {: argument is of length zero
```

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lrberge** [comment]
Thanks, fixed.
