### ISSUE TITLE
Issues with custom vcov when using sw containing an interaction term

### ISSUE THREAD

**Issue by sergiu-burlacu** [lrberge/fixest#231]
The issue is niche but if it only requires a small tweak, maybe it's useful to report it for future updates. I am trying to estimate a stepwise model that includes some fixed covariates in addition to the stepwise variables.  One of the stepwise terms is an interaction term. This works fine if: (i) I don't include a custom vcov; (ii) I don't include the other covariates; or (iii) I don't include an interaction term in the stepwise vector. 

Thanks!

```r
xs <- c("cyl", "disp * cyl")
covs <- c("hp", "vs")

feols(mpg ~ sw(.[, xs]) + .[covs], # with other covariates
      mtcars, 
      vcov = function(x)  sandwich::vcovHC(x, type = "HC2")
      ) %>%  etable() # does not compute se for 2nd model

feols(mpg ~ sw(.[, xs]) + .[covs], 
      mtcars, 
      "hetero"
      ) %>%  etable() # works fine without custom vcov

feols(mpg ~ sw(.[, xs]) , 
      mtcars, 
      vcov = function(x)  sandwich::vcovHC(x, type = "HC2")
      ) %>%  etable() # works fine without other covariates

# without the interaction term
xs <- c("cyl", "disp")

feols(mpg ~ sw(.[, xs]) + .[covs], 
      mtcars, 
      vcov = function(x)  sandwich::vcovHC(x, type = "HC2")
      ) %>%  etable() # works fine without the interaction term
```

**Comment by lrberge** [comment]
Hi, thanks for the report and the clear reproducible example.
In fact it was a problem regarding the order of variables in `model.matrix` output (used in `sandwich`'s VCOV).
Now fixed, thanks!
