### ISSUE TITLE
Degrees of freedom

### ISSUE THREAD

**Issue by ChristianDueben** [lrberge/fixest#232]
Hi Laurent,

I noticed something unexpected when using `fitstat` with the option `"g"`.
Consider the following example:
```
df <- data.frame(y = runif(10000000), x1 = runif(10000000), x2 = runif(10000000), x3 = runif(10000000), x4 = runif(10000000), x5 = runif(10000000), 
  z1 = sample(1:1000000, 10000000, replace = T), z2 = sample(1:100000, 10000000, replace = T), z3 = sample(1:500000, 10000000, replace = T))

outp <- fixest::feols(y ~ x1 + x2 + x3 + x4 + x5 | z1 + z2 + z3, data = df)

fixest::fitstat(outp, "g")
```
This produces the output `G: 999,939` in my case. Instead, I was expecting the number that e.g. `fixest::fitstat(outp, "wf")` produces. That would also be better aligned with the text in the function description: "When the VCOV is clustered, this value is equal to the minimum cluster size, otherwise, it is equal to the sample size minus the number of variables."

It appears that `fixest::fitstat(outp, "g")` simply uses the size of the first fixed effect, `outp$fixef_sizes[1]` in this case. Is that the intended behavior?

Thanks for looking into it.

Kind regards,
Christian

**Comment by lrberge** [comment]
Hi Christian,

It's normal, it's the minimum **cluster size** and not fixed-effects size. This number is *independent* of the fixed-effects.

```R
data(trade)
est = fepois(Euros ~ log(dist_km), trade)
fitstat(est, "g")
#> G: 38,323
fitstat(est, "g", cluster = ~ Origin)
#> G: 15
fitstat(est, "g", cluster = ~ Origin^Destination)
#> G: 210
fitstat(est, "g", cluster = ~ Origin^Destination + Product)
#> G: 20
```

hth!
Laurent

**Comment by ChristianDueben** [comment]
Thanks.
