### ISSUE TITLE
Enable recursive definition of macros

### ISSUE THREAD

**Issue by turbanisch** [lrberge/fixest#234]
Fixest's macros are a godsend to me, yet sometimes I wish I could recursively define them (e.g. when I am creating different versions of a formula depending on parameters). Is there a way to do so? So far I have not succeeded:

``` r
library(fixest)

# recursively define macros
setFixest_fml(..x = ~ vs + am)
setFixest_fml(..y = ~ ..x + hp)

# expand formula
f <- xpd(mpg ~ ..y)
attr(terms(f), "term.labels")
#> [1] "..x" "hp"
```

<sup>Created on 2021-11-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

On the same note, would it be possible for `xpd()` to expand formulas that only have a right- or left-hand side?

**Comment by lrberge** [comment]
Hi, that was not implement natively but you could by using `xpd()` in the definition of `..y`. 
Now I've enabled recursion natively. But beware: The evaluation is done at *run time* and not at *definition time*.

```R
# recursively define macros
setFixest_fml(..x = ~ vs + am)
setFixest_fml(..y = ~ ..x + hp)

xpd(mpg ~ ..y)
#> mpg ~ vs + am + hp

setFixest_fml(..x = ~ oop)
xpd(mpg ~ ..y)
#> mpg ~ oop + hp
```
I don't really understand the last comment. It is possible to expand all kind of formulas:
```R
xpd(rhs = "..y")
#> ~oop + hp

xpd(lhs = "..y")
#> oop + hp ~ 1
```

Am I missing something? Could you give an example?

**Comment by turbanisch** [comment]
Thank you so much for implementing this! You are absolutely right, I must have used xpd() incorrectly (perhaps by missing a ~ or quotation marks). Sorry for the false alarm!
