### ISSUE TITLE
`predict.fixest` with `i()` and `newdata`

### ISSUE THREAD

**Issue by vincentarelbundock** [lrberge/fixest#235]
Hi,

Quick questions about `predict.fixest`, prompted by [this issue](https://github.com/vincentarelbundock/marginaleffects/issues/136):

1. What happens under the hood when users call `i()` in formula and `newdata` does not include one of the original factor levels? 
2. What does the prediction mean? 
3. Should there checks to make sure that user-supplied levels are OK?

``` r
library(fixest)
mod1 = feols(mpg ~ hp + i(cyl), mtcars)
mod2 = feols(mpg ~ hp + factor(cyl), mtcars)
coef(mod1) == coef(mod2)
```

    ## (Intercept)          hp      cyl::6      cyl::8 
    ##        TRUE        TRUE        TRUE        TRUE

``` r
nd1 = nd2 = mtcars[1, ]
nd2$cyl = pi

predict(mod1, newdata = nd1)
```

    ## [1] 20.03819

``` r
predict(mod1, newdata = nd2)
```

    ## [1] 26.00585

``` r
predict(mod2, newdata = nd1)
```

    ## Error: in predict.fixest(mod2, newdata = nd1):
    ##  Error when creating the linear matrix: contrasts can be applied only to
    ## factors with 2 or more levels

``` r
predict(mod2, newdata = nd2)
```

    ## Error: in predict.fixest(mod2, newdata = nd2):
    ##  Error when creating the linear matrix: contrasts can be applied only to
    ## factors with 2 or more levels

**Comment by lrberge** [comment]
(Bonjour Vincent, et désolé de répondre si tard. Pour ma santé mentale, j'essaie de lever le pied sur GH et de m'en éloigner. Autrement j'ai l'impression d'être en plein mythe de Sisyphe : plus je réponds vite et plus les travaux reviennent nombreux. J'espère que tu comprendras.) 

Thanks for reporting! There are two bugs:
 1. `i()` working wrongly in predict with new, non existing values
 2. predict not working with factors when `newdata` having only 1 factor value

Bug 2 is fixed already in the current version. 
On bug 1: I'll take care of it and let you know, thanks!

**Comment by vincentarelbundock** [comment]
Thanks for the fixes, this is fantastic!

(Franchement, c'est une leçon que j'ai encore à apprendre: le OSS est un beau hobby, mais il est *essentiel* de le subordonner à la "vraie vie". Bonne chance!)

**Comment by lrberge** [comment]
OK, now Bug 1 is fixed too. You get a proper error message instead of stg working silently (it was simply considering the coefficients of non-included factor values as 0, but an error was preferable).

Btw I'm still not very happy with the `i()` thing because I realized  it does not play well with "typical values"... But I don't really know what to do about it. :-/

Anyway, thanks for reporting!

**Comment by vincentarelbundock** [comment]
> OK, now Bug 1 is fixed too. You get a proper error message instead of stg working silently (it was simply considering the coefficients of non-included factor values as 0, but an error was preferable).

Wonderful!

> Btw I'm still not very happy with the `i()` thing because I realized it does not play well with "typical values"... But I don't really know what to do about it. :-/

If there's an easy way to extract the list of factor variables in `i()` (parsing the formula?), I could easily include a check in `typical`. and treat known factors accordingly, taking their mode instead of mean.

**Comment by lrberge** [comment]
There's that slot `model_matrix_info` that I use internally:
```R
base = setNames(iris, c("y", "x1", "x2", "x3", "species"))
m = feols(y ~ x1 + i(species), base)
m$model_matrix_info
#> [[1]]
#> [[1]]$coef_names_full
#> [1] "species::setosa"     "species::versicolor" "species::virginica" 
#> 
#> [[1]]$items
#> [1] setosa     versicolor virginica 
#> Levels: setosa versicolor virginica
#> 
#> [[1]]$ref_id
#> [1] 1
#> 
#> [[1]]$ref
#> [1] setosa
#> Levels: setosa versicolor virginica
#> 
#> [[1]]$is_num
#> [1] FALSE
#> 
#> [[1]]$f_name
#> [1] "species"
#> 
#> [[1]]$is_inter_num
#> [1] FALSE
#> 
#> [[1]]$is_inter_fact
#> [1] FALSE
```
It is included only for "regular" factors so far. So sapplying on it to get `f_name` may work. 

But I don't know if it's worth the extra work. This `i()` thing is really accidental and due to path dependency. I may (*may*) change it to return a simple factor instead, but I still have to weight the pros and cons!
