### ISSUE TITLE
option "view" doesn't work with tinytex

### ISSUE THREAD

**Issue by etiennebacher** [lrberge/fixest#242]
Hello, I've tried to use the option `view = TRUE` in `etable` but it didn't detect pdflatex:
```r
library(fixest)
dict = c("(Intercept)" = "Constant", 
         Petal.Length = "Petal length", Petal.Width = "Petal width",
         Sepal.Length = "Sepal length", Sepal.Width = "Sepal width",
         note1 = dsb("*Notes*: This is a note that illustrates how to access notes ",
                     "from the dictionary."),
         source = "*Sources*: Somewhere from the net.")
setFixest_dict(dict)
nm = names(iris)
est = feols(.[nm[1]] ~ .[nm[2:4]], iris, fsplit = ~Species)
etable(est, view = TRUE)
```
```
Warning messages:
1: In system2("pdflatex", "-help", FALSE, FALSE) : '"pdflatex"' not found
2: In etable(est, view = TRUE):
 pdflatex could not be run: check install? 
3: In etable(est, view = TRUE) :
  The argument 'view' requires pdflatex to work. So they are currently ignored.
```
However, tinytex is installed and pdflatex too. If I have a file "test.tex" like that:
```
\documentclass{article}

\begin{document}

Hello

\end{document}
```
and if I use pdflatex on it, it works (the PDF file is correctly produced):
```r
tinytex::pdflatex("test.tex")
```
Is this because tinytex is not detected by fixest, or did it work for you and it's specific to me?

**Comment by lrberge** [comment]
Does 
```
pdflatex file.tex
```

work on the command terminal? That's what's needed, not `tinytex`. Maybe `pdflatex` isn't on the path?

**Comment by etiennebacher** [comment]
Indeed `pdflatex file.tex` doesn't work in terminal. How should I add `pdflatex` to the path?

**Comment by Oravishayrizi** [comment]
Maybe I can help here, 
[assuming you're using win10 or win11] you should find the location of pdflatex.exe and then simply add it to your environment variables.
You may find this tutorial helpful:
[link](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/)

**Comment by lrberge** [comment]
I've changed the code: there is no requirement with external software now. Everything should work with just R packages (`tinytex` and `pdftools`).

**Comment by etiennebacher** [comment]
Works perfectly, thanks
