### ISSUE TITLE
lag <formula> does not work in lagging a variable with data.table syntax

### ISSUE THREAD

**Issue by seawavevan** [lrberge/fixest#246]
I tried to run the code posted in the short intro of `fixest` like: 

```
base_lag_dt = as.data.table(base_did)
base_lag_dt[, x1.l1 := lag(x1 ~ id + period, 1)]
```

Error occured as: 
```
Error: Input must be a vector, not a <formula> object.
Run `rlang::last_error()` to see where the error occurred.
```

I've no idea the cause of this issue. Is it related to `data.table`?

**Comment by grantmcdermott** [comment]
@seawavevan Hard to troubleshoot without more information. E.g. Does the above code not work for you, or do you just run into problems with your own dataset? Can you post a [reprex](https://reprex.tidyverse.org/#usage) and your `sessionInfo()`?

**Comment by lrberge** [comment]
As Grant mentions, more information is needed to debug. Currently I cannot replicate.

What I know for sure is that it is not an error from `fixest`. The most likely reason is that other packages superimpose the `lag` method, leading to `fixest::lag.formula` to not be dispatched properly. But this is not a `fixest` problem per se.
