### ISSUE TITLE
etable, p-values

### ISSUE THREAD

**Issue by ylelkes** [lrberge/fixest#248]
Is it possible to base stars in etable on one-tailed p-values? i tried dividing the p-values in the coeftable object, but that doesn't seem to do the trick

set.seed(10)
x <- rnorm(100)
y <- .2*x + rnorm(100)
a <- feols(y~x,data.frame(x,y))
a$coeftable$`Pr(>|t|)` <- a$coeftable$`Pr(>|t|)`/2
etable(a)

**Comment by grantmcdermott** [comment]
Laurent might have an etable-specific answer. But FWIW the dev version of **multcomp** now supports **fixest** objects. It should be on CRAN after they get back from their holiday break, but you can install from source in the meantime.

```r
install.packages("multcomp", repos="http://R-Forge.R-project.org")
```

Once that's done, you can pass `multcomp::glht(...)` to `modelsummary::msummary(...)` to get a regression table. E.g.

``` r
library(fixest)
library(multcomp)
library(modelsummary)

set.seed(10)
x <- rnorm(100)
y <- .2*x + rnorm(100)
a <- feols(y~x,data.frame(x,y))

a1 = glht(a, 'x<=0')
summary(a1)
#> 
#>   Simultaneous Tests for General Linear Hypotheses
#> 
#> Fit: feols(fml = y ~ x, data = data.frame(x, y))
#> 
#> Linear Hypotheses:
#>        Estimate Std. Error t value Pr(>t)  
#> x <= 0   0.1402     0.1039    1.35 0.0901 .
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> (Adjusted p values reported -- single-step method)

msummary(list(a, a1), 
         statistic = 'p.value',
         coef_omit = 'Intercept',
         gof_omit = 'Adj|Within|Pseudo|IC|Log|Std')
```

|          | Model 1 | Model 2 |
|:---------|:-------:|:-------:|
| x        |  0.140  |         |
|          | (0.180) |         |
| x \<= 0  |         |  0.140  |
|          |         | (0.090) |
| Num.Obs. |   100   |   100   |
| R2       |  0.018  |  1.000  |

<sup>Created on 2021-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lrberge** [comment]
Hi @ylelkes, yes you can! 

The only thing you need to do is to apply `summary` (or use `vcov` during the estimation) before passing the model to `etable`:
```R
b = summary(a)
b$coeftable[, 4] = b$coeftable[, 4]/100
etable(a, b)
#>                                a                   b
#> Dependent Var.:                y                   y
#>                                                     
#> (Intercept)     -0.1031 (0.0983) -0.1031*** (0.0983)
#> x                0.1402 (0.1039)  0.1402*** (0.1039)
#> _______________ ________________ ___________________
#> S.E. type                    IID                 IID
#> Observations                 100                 100
#> R2                       0.01826             0.01826
#> Adj. R2                  0.00824             0.00824
#> ---
#> Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

That's because otherwise, `summary` is applied *within* `etable`, changing the information in `coeftable`.

----

The fact that `fixest` is now compatible with `multcomp` is great news (and Grant may have something to do with this! 😉).
