### ISSUE TITLE
Allow option for notes under table in "etable"

### ISSUE THREAD

**Issue by bgchamps** [lrberge/fixest#25]
It would be nice to directly include notes under the table, ala the "notes" option in stargazer.

**Comment by lrberge** [comment]
Sure, it's no big deal to implement it.

Note that recently a `broom` method has been implemented for `fixest` objects by @karldw (see #21). It allows to leverage generalist methods to export estimation results. Notably the excellent [modelsummary](https://vincentarelbundock.github.io/modelsummary/).

Currently, it's only included in `broom`'s development version, but before it gets to CRAN the following code should work:
```R
library(broom) ; library(dplyr) ; library(modelsummary)
source("https://github.com/tidymodels/broom/blob/master/R/fixest-tidiers.R?raw=true")
source("https://github.com/tidymodels/broom/blob/master/R/utilities.R?raw=true")

library(fixest)
est = feols(Sepal.Lengthy ~ Sepal.Width + Petal.Length | Species, iris)
modelsummary(est)
```

**Comment by lrberge** [comment]
Hi, it's done (note that I didn't implement the stars thing). The dev version is not yet stable, but `etable` has been pimped substantially.

**Comment by bgchamps** [comment]
Sweet thanks Laurent! Keep it up ... your package is great to use. 

Regards,
Bhargav

**Comment by karldw** [comment]
broom 0.7.0 is out today!

**Comment by shoonlee** [comment]
Hi! Thanks for the great package! 

I know that users can readily add notes under a table, but the formatting seems to be an issue (at least for me). I compile PDF directly from ```Rmd``` so it would be ideal to create a perfect table without having to fix them separately in a ```.tex``` file. Having said that, I found that under the current version, the alignment of the note text is governed by the alignment command for the table itself (so center aligned) and the font size seems to be identical to that of the main table body text, which could be too big for a note. I've quickly reviewed the tex output from other packages and it seems that implementing ```multicolumn``` can be a potential solution. Would it be possible to add this formatting feature to the ```notes``` argument? Thank you for your consideration!
