### ISSUE TITLE
Fixed effect interaction with function fails

### ISSUE THREAD

**Issue by statzhero** [lrberge/fixest#253]
I'm reporting this because the program told me so. Perhaps there is never a reason to apply a function for the fixed effects but I'm not sure what the requirements "under the hood" are.

``` r
library(fixest)
feols(y ~ x1 | post + factor(period), base_did) |> etable()
# works

feols(y ~ x1 | post^period, base_did) |> etable()
# works

feols(y ~ x1 | post^factor(period), base_did) |> etable()
Error in to_integer(..., add_items = TRUE, items.list = TRUE, internal = TRUE) : 
  All elements in '...' should be of the same length (current lenghts are 1080 and 1).
Error in feols(y ~ x1 | post^factor(period), base_did) : 
  Error in res[[2]] : subscript out of bounds
```

**Comment by grantmcdermott** [comment]
In general, and as you show in your MWE, you shouldn't have to specify `factor(x)` in the fixed effects slot. Doing so is redundant b/c all FE variables are automatically treated as "factors". We also want to avoid encouraging users from calling, say, `i(x)` in the FE slot b/c that will create a full design matrix, which is negates all of the algorithmic speedup. (IIRC it actually errors out.) Given that, I think we can probably close?

**Comment by lrberge** [comment]
Indeed, you're right Grant that we don't need it. But it's still a bug, alas.

Actually it was due to the specific parsing of the FEs and it was surprisingly difficult to solve, but now it should work fine.
