### ISSUE TITLE
Error in extracting "cd" and "kpr" from `fitstat`

### ISSUE THREAD

**Issue by YaoZhongwei** [lrberge/fixest#259]
Hi Laurent,

Thanks for the excellent package. I run into an error when trying to extract "cd" and "kpr" by `fitstat`. 

The error message for   `fitstat(feols(wt ~ qsec + drat | hp ~ disp, data = mtcars), ~  kpr)`:

`
Error in solve.default(K, meat) : 
  'b' (4 x 4) must be compatible with 'a' (1 x 1)
`

The error message for  `fitstat(feols(wt ~ qsec + drat | hp ~ disp, data = mtcars), ~  cd)`:

`
Error: $ operator is invalid for atomic vectors
`

**Comment by lrberge** [comment]
Hi, and glad that you like the package!

The current bugs that you are reporting should be fixed in the current dev version.
