### ISSUE TITLE
anyNA.data.frame induces an R version dependency

### ISSUE THREAD

**Issue by MichaelChirico** [lrberge/fixest#261]
https://github.com/wch/r-source/commit/f525a370e95101e1c59e0b6984be8759e9398ab1

https://github.com/lrberge/fixest/blob/447bdca4cbadea9066b0fec779caeb45dadd6dbb/R/fixest_env.R#L1847

We are on 3.6.3; it looks like `anyNA.data.frame` didn't make it into that release (though I don't see a NEWS item saying when exactly the method was added).

Why call `anyNA.data.frame` explicitly here?

**Comment by lrberge** [comment]
Ooooch, that's a big dependency introduced without noticing. 
Not needed indeed, I just used it for convenience (to avoid using `any(sapply etc`).
Fixed, thanks for the pointer.
