### ISSUE TITLE
issues with weights and multiple outcomes

### ISSUE THREAD

**Issue by sahilchinoy** [lrberge/fixest#263]
Hi, just wanted to flag this as a possible bug: when using the `c(outcome1, outcome2) ~ .` syntax for multiple outcomes in a weighted regression, I get different results from when I run separate regressions (i.e. `outcome1 ~ .` and `outcome2 ~ .`) I think this possibly has to do with one of the outcomes being missing for some observations, but the regression still using the full vector of weights that is non-missing for all observations. I haven't dug into this fully but just wanted to flag it and check whether I am missing something obvious! Thanks for your work on this package.

**Comment by sahilchinoy** [comment]
A quick example of what I'm talking about. The last call to `feols` gives different results for the `y2` model than the second one.

```
library(tibble)
library(fixest)

df <- tibble(
  y1 = c(1, 2, 3, 4),
  y2 = c(NA, 2, 3, 4),
  x1 = c(1, 2, 3, 5),
  w = c(1, 2, 3, 4)
)

feols(y1 ~ x1, weights = ~ w, data = df)
feols(y2 ~ x1, weights = ~ w, data = df)
feols(c(y1, y2) ~ x1, weights = ~ w, data = df)
```

**Comment by lrberge** [comment]
Hi and thanks a lot for the report and the minimal reproducible example!

Indeed, this was a major bug, now fixed (and specific tests were added).
