### ISSUE TITLE
Access to new 0.10.2 version?

### ISSUE THREAD

**Issue by matthewgson** [lrberge/fixest#267]
I'm happy to see that `etable()` now supports `adjustbox` among others on new version.  I'm eager to use the new feature, but currently CRAN has 0.10.1 version. 
Is there a way to install 0.10.2? And any plans for CRAN release? Thank you.

**Comment by s3alfisc** [comment]
Hi @matthewgson, You can always install development versions from github directly by running

```
# note: installation requires Rtools
library(devtools)
install_github("lrberge/fixest")
```
Note that you will have to compile the c++ code on your local computer, and for this, you will need to have Rtools installed (follow the instructions [here](https://cran.r-project.org/bin/windows/Rtools/rtools40.html)). 

As a sidepoint, ropensci has a relatively new project, [r-universe](https://r-universe.dev/maintainers/), which is an alternative package repository and which compiles development versions of R packages hosted on github for Windows and Mac - I think it's a cool project and maybe @lrberge might be persuaded to set up support for `fixest` at r-universe at at some point? :)

**Comment by matthewgson** [comment]
@s3alfisc Thank you very much for detailed instructions! @lrberge Please feel free to close this issue as you see fit.

**Comment by lrberge** [comment]
Thanks Alex for the weighting in giving detailed instructions!

I actually knew r-universe but only by name, I didn't really get it was a package repo. I need to investigate further but it looks like a cool project. I'll let you know if I get in at some point.
