### ISSUE TITLE
glm implementation of binomial cbind functionality

### ISSUE THREAD

**Issue by DrWillParry** [lrberge/fixest#269]
Hi Laurent,
Thanks for an amazing package, it's been great using it.
I noticed that you currently cannot specify a binomial model with the glm-style LHS formula: 

`cbind(successes, failures) ~ x1 + x2 | fe1 + fe2`

I realise that you can usually choose to model the proportion of successes and then weight the analysis. I am presuming this is also the way to do it currently with **feglm**? i.e. use total trials as the weight variable.

**Comment by lrberge** [comment]
Hi Will,
Thanks for the kind words, glad you like it!

Currently the point you're mentioning is indeed a limitation: this is not possible to replicate this feature of `glm`.
Internally this is at odds with how the package handles the dependent variable, and this is especially problematic regarding the fixed-effects algorithm.

On the replication without using success/failures: I don't know, but that's rather a stackoverflow question 😉
