### ISSUE TITLE
Offset in formula has no effect

### ISSUE THREAD

**Issue by DrWillParry** [lrberge/fixest#270]
Hi Laurent,
Another quick thing I have noted...
In {glm} and {glmmTMB} and perhaps more, you can specify a poisson offset in the formula as so:

`y ~ x1 + x2 + x3 + offset(log(Y))`

I attempted this using **feglm** and it did not appear to have any effect, whereas using the **offset = log(Y)** approach did.

**Comment by lrberge** [comment]
Hi, it's a version problem. It's possible since 0.10.0.
