### ISSUE TITLE
prune directories from files checked by is_fixest_used?

### ISSUE THREAD

**Issue by kyleam** [lrberge/fixest#271]
When loading the package on my end, I hit into the following error:

```
 Error in file(con, "r") : cannot open the connection
 In addition: Warning messages:
 1: In file(con, "r") : 'raw = FALSE' but 'lambda.r' is not a regular file
 2: In file(con, "r") : cannot open file 'lambda.r': it is a directory
```

`is_fixest_used` is seeing  a `lambda.r/` subdirectory (for the package) in my `lib/` subdirectory.  That's a bit of an odd arrangement needed to hit into this (and easy for me to work around), but perhaps `is_fixest_used` should make sure it's not trying to operate on directories.  Something like:

```diff
diff --git a/R/MiscFuns.R b/R/MiscFuns.R
index 8440ea1..cc484b1 100644
--- a/fixest/R/MiscFuns.R
+++ b/fixest/R/MiscFuns.R
@@ -11555,6 +11555,7 @@ is_fixest_used = function(){
     file_extra = grep("\\.Rprofile", list.files(all.files = TRUE), value = TRUE)^M
 ^M
     files = c(files, file_extra, sub_files)^M
+    files = files[!dir.exists(files)]^M
 ^M
     if(length(files) == 0) return(FALSE)^M
 ^M
```

**Comment by lrberge** [comment]
Hi, thanks a lot, that's clearly a bug!
Gosh I really thought that `list.files()` returned only... files. What a mistake! Thanks for the fix!

Changes should hit CRAN soon (<1 week).
