### ISSUE TITLE
adjustbox shrinks table in RMarkdown

### ISSUE THREAD

**Issue by matthewgson** [lrberge/fixest#272]
I've been trying to fit the table using new feature `etable(..., adjustbox=TRUE)`, but it shrinks the table instead in pdf.

I'm wondering what's causing the issue. Could I get some help here? 

Below is reproducible code in RMarkdown (I replaced backticks with ' for readability)

```
# This is RMarkdown Code
'''{r}
library(fixest)

model = feols(Sepal.Width ~ Sepal.Length + Petal.Length,
              fsplit = ~Species,
              data = iris)
etable(model, 
       tex = T,
       adjustbox = T,
       file = 'temp.tex')
'''

'''{r, child = 'temp.tex'}
'''
```

The output looks

![image](https://user-images.githubusercontent.com/46496637/154175891-3bb99c42-434d-48b4-bacb-f0dd4ecbf033.png)

**Comment by matthewgson** [comment]
I discovered this is related to Pandoc's default latex template that uses 
`\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}` 
Especially `height=\maxheight` part somehow making trouble with `adjustbox`.
I commented that out and use custom template to bypass this. Hope this may help some.

**Comment by eyayaw** [comment]
> I discovered this is related to Pandoc's default latex template that uses `\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}` Especially `height=\maxheight` part somehow making trouble with `adjustbox`. I commented that out and use custom template to bypass this. Hope this may help some.

Can you share your custom template? Simply commenting out that line didn't work for me.
https://github.com/jgm/pandoc-templates/blob/master/default.latex

**Comment by eyayaw** [comment]
For me, passing the adjustbox options directly worked. 

```markdown
```{r}
#| label: tbl-estimation
#| output: asis
tbl = etable(
  mods,
  headers = lapply(mods, length),
  fitstat = c("n", "r2"),
  tex = TRUE,
  fontsize = "small",
  adjustbox = TRUE,
  notes = r"(
\textit{Notes: }Robust standard errors in parentheses. Significance levels: *** p < 0.01, ** p < 0.05, * p < 0.1.
)"
)

# fix adjustbox conflict with pandoc default global Gin options
tbl[grep(r"(\\begin\{adjustbox)", tbl)] = r"(\begin{adjustbox}{width=\textwidth,totalheight=\textheight,keepaspectratio})"
cat(tbl)
```
```
