### ISSUE TITLE
Predict function doesn't return expected length when using character vector of dummies and NA values

### ISSUE THREAD

**Issue by ColinTB** [lrberge/fixest#273]
First of all, Thank you so much for the package, it is amazing!!
This is the small issue I found with the predict function:

```

# Create data and run regression
test.1 <- tibble(a = c(1:5),
                 b = c(3:6, NA),
                 c = as.factor(c("a", "b", "a", "b", "a")))

test.1b <- feols(a ~ b + c, data = test.1)

# Expect length 4 given 1 NA value
predict(test.1b)

# Expect length 5 since using the newdata argument, but on get back 4
predict(test.1b, newdata = test.1)
```

**Comment by lrberge** [comment]
Thanks a lot for the simple reproducible example! 
That's a bug I introduced relatively recently when I added new functionalities to predict. Now in the test file ;-)

Thanks again for reporting, now fixed.
