### ISSUE TITLE
year -1 missing for sunab staggered did

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#275]
https://lrberge.github.io/fixest/reference/sunab.html

The year -1 is missing for the sunab staggered did. I thought year 0 is the reference year.

**Comment by lrberge** [comment]
No, -1 is the most common. Here's a recent Acemoglu paper:
![image](https://user-images.githubusercontent.com/43536394/164795894-d88aa362-9254-426c-9e09-63e316b00dd2.png)
