### ISSUE TITLE
feature request: flip/transpose option for etable 

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#276]
https://cran.r-project.org/web/packages/stargazer/stargazer.pdf

Stargazer has a flip option that flips the vertical and horizontal axes when printing summary statistics. It would be great if it is also available in etable.

**Comment by lrberge** [comment]
Flipping won't be there, the table wouldn't be nice in 95% of the cases.

However in a recent project I had to work with dozens and dozens of dependent variables and hence I've been developing the function `tetable` (transpose of `etable`) which displays the dependent variable in rows, which looks very much like what you're suggesting. 

It's still in development however and I have to solve some technical difficulties before including it officially in the package. But it will be there.
