### ISSUE TITLE
`mvsw` returns slightly different statistics for the same models estimated individually

### ISSUE THREAD

**Issue by resulumit** [lrberge/fixest#278]
Hi,

I know I should be providing you with a reproducible example, but I have run into this problem while working on a dataset that I cannot share at this moment. I will be looking into creating an anonymised subset of the data. I cannot reproduce it with the mtcars dataset.

I use the new `mvsw` function to run a multiverse of (128) regression models with three fixed effects and a clustering variable, with one call. 

I have run some of these models individually to check and compare the results. The results (estimates, standard errors, t and p values) from most of the models match, but some don't. The differences are small, but perhaps the size is about my underlying data. For the record, this is not about rounding.

I just wanted to give you and everyone else a heads up, but feel free to close this issue as I cannot provide you with a reproducible example.

**Comment by resulumit** [comment]
Here is an example:

```
library(fixest) # version 0.10.2

df <- read.csv("https://www.dropbox.com/s/9aq8emls077x9qc/data.csv?dl=1")

multiple <- feols(dv ~ iv +
                      mvsw(var1, var2, var3, var4, var5, var6, var7)
                      | fe1 + fe2 + fe3, cluster = ~ cluster,
                      data = df
                      )

single  <- feols(dv ~ iv +
                       var1 + var2 + var3 + var4 + var5 + var6 + var7
                      | fe1 + fe2 + fe3, cluster = ~ cluster,
                      data = df)

multiple[[128]][["coeftable"]]["iv", 1]
single[["coeftable"]][[1, 1]]
```

This results in the following coefficients:

```
[1] -0.003668564
[1] -0.003666562
```
I know the differences are tiny, but I think this would raise a red flag during replication at an academic journal.

**Comment by lrberge** [comment]
Now all multiple results replicate exactly the individual estimations. 

The difference comes from numerical approximations out of difficult numerical convergence of the fixed-effects. One has to live with it, we rely on numerical methods in the end.

Thanks for the reproducible example.
