### ISSUE TITLE
etable: specifying cluster variables as a list

### ISSUE THREAD

**Issue by arielfri** [lrberge/fixest#280]
Running the code below worked perfectly in previous versions of fixest (e.g. version 0.9.0), however specifying the cluster variable as a list now returns an error.

``` r
library(fixest) #version 0.10.2

est <- feols(Ozone ~ Solar.R + Wind + Temp, data = airquality)
#> NOTE: 42 observations removed because of NA values (LHS: 37, RHS: 7).

etable(est, est, est, est, 
       cluster = list(c(), c("Month"), c("Day"), c("Day", "Month")))
#> Error in vcov.fixest(object, vcov = vcov, ssc = ssc, forceCovariance = forceCovariance, : To compute the Clustered VCOV, you need to provide variables with the same number of observations as in the original data set. Currently there are 0 instead of 153.
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lrberge** [comment]
I'm sorry but this is a breaking change and there will be no retro compatibility.

Only the argument `vcov` now supports a list of different VCOV-types. This becomes much more general than the argument `cluster`.

From the example, which can be extended to your code, please use `vcov = list("iid", ~Month, ~Day, ~Day + Month)` instead.
