### ISSUE TITLE
feNmlm: 'NL.fml' must be a formula

### ISSUE THREAD

**Issue by ZhihaoMa** [lrberge/fixest#281]
Thanks for your wonderful package.

This maybe not a standard issue.

I'm new to R. I wanna run a non-linear (logit) regression to estimate the effect of Y on X. My code is

feNmlm(Y ~ X | FE1 + FE2,data,family = logit)

Then R reports that 'NL.fml' must be a formula. But it seems that the logistic formation is hard to be written as a "linear" equation by take-log. 

Perhaps I misunderstood the error. Any suggestion about it?

Thanks.

**Comment by lrberge** [comment]
Hi, that's very likely a package version problem. I don't have any issue with logit estimation.

Btw, for simple logit models, use `feglm` with `family = "logit"` instead.

If needed, please reopen with a reproducible example.
