### ISSUE TITLE
F-test, fitstat and standard errors

### ISSUE THREAD

**Issue by fvillarroelm** [lrberge/fixest#282]
Hello,

Many thanks for such a great package. I am using the last version (‘0.10.3’) of fixest, and I have a question about F-test using fitstat and standard errors (SEs). Why the p-value is the same when using the "standard" and heteroskedasticity-robust SEs in feols? It does change when using clusters though.
Which p-value is really giving me fitstat? The ones under standard or heteroskedasticity-robust SEs?

Here a reproducible example:

```
if(!require("pacman")){install.packages("pacman")}
pacman::p_load(tidyverse, fixest)

data(mtcars)

formula <- reformulate(mtcars %>% names() %>% discard(. == "am"), response = "am")

feols(formula, mtcars, se = "standard") %>% fitstat(type = "f") 
# output: F-test: stat = 8.35985, p = 2.492e-5, on 10 and 21 DoF.
feols(formula, mtcars, se = "hetero") %>% fitstat(type = "f")
# output: F-test: stat = 8.35985, p = 2.492e-5, on 10 and 21 DoF.
feols(formula, mtcars, se = "cluster", cluster = "gear") %>% fitstat(type = "f")
# output: F-test: stat = 0.796176, p = 0.673889, on 10 and 2 DoF.
```

Many thanks in advance.

**Comment by lrberge** [comment]
Hi, that's normal, the F-test is based on the sum of the squared residuals and not on the VCOV: hence the VCOV has no effect.

What you are likely looking for is the Wald statistic (which is equivalent to the F-test in the case of the standard VCOV). The Wald stat depends on the VCOV and this is reminded in the display:

```R
est = feols(am ~ ..("^[^a]"), mtcars)

fitstat(est, type = "wald")
#> Wald (joint nullity): stat = 8.35985, p = 2.492e-5, on 10 and 21 DoF, VCOV: IID.
fitstat(est, type = "wald", vcov = "hetero")
#> Wald (joint nullity): stat = 13.1, p = 6.518e-7, on 10 and 21 DoF, VCOV: Heteroskedasticity-robust.
```
