### ISSUE TITLE
Organize vignettes on website

### ISSUE THREAD

**Issue by etiennebacher** [lrberge/fixest#285]
Hello, this is just a minor issue. 

On the website, the vignettes are a bit disorganized in the "Articles" dropdown, e.g the introductory vignette comes in third position, whereas it should be the first one. Also, there are several topics: estimation, standard errors, export the results... (maybe more vignettes in the future as well). I think it would improve the docs to reorganize the vignettes and maybe to put them into sections, like on the [dplyr website](https://dplyr.tidyverse.org/) for example.

**Comment by lrberge** [comment]
Thanks for the suggestion. Done.
