### ISSUE TITLE
Small bug with IV estimation

### ISSUE THREAD

**Issue by kylebutts** [lrberge/fixest#290]
Hi Laurent,

Small bug when there are no terms before IV terms, it says no parameter to be estimated. I could include an intercept, but in my setting, I'm using residuals and the intercept is estimated to be ~0. The error comes up in the `fixest_env()` call. 

``` r
base = iris
names(base) = c("y", "x1", "x_endo_1", "x_inst_1", "fe")
set.seed(2)
base$x_inst_2 = 0.2 * base$y + 0.2 * base$x_endo_1 + rnorm(150, sd = 0.5)
base$x_endo_2 = 0.2 * base$y - 0.2 * base$x_inst_1 + rnorm(150, sd = 0.5)

est_iv = fixest::feols(y ~ 0 | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, base)
#> Error in fixest::feols(y ~ 0 | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, : No parameter to be estimated.
```

<sup>Created on 2022-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Not a critical bug, but figured I would flag :-)

**Comment by lrberge** [comment]
Finally fixed. Thanks for reporting!
