### ISSUE TITLE
`predict.fixest(newdata = )` breaks on `feNmlm` model

### ISSUE THREAD

**Issue by vincentarelbundock** [lrberge/fixest#292]
Sorry for the multiples today...

``` r
library("fixest")
data(trade)

# works
mod_feols <- feols(Euros ~ log(dist_km) | Product, data = trade)
predict(mod_feols, newdata = head(trade))
#> [1] 169757634 169757634 261139439 261139439 197679491 197679491

# breaks
mod_feNmlm <- feNmlm(Euros ~ log(dist_km) | Product, data = trade)
predict(mod_feNmlm, newdata = head(trade))
#> Error: $ operator is invalid for atomic vectors
```

Not sure what the problem is as the traceback is uninformative.

Problem initially reported here: <https://github.com/vincentarelbundock/marginaleffects/issues/239>

**Comment by lrberge** [comment]
Thanks and I'm very sorry that bugs in my code do give you trouble.
Thanks again for the reports with reproducible examples!

**Comment by vincentarelbundock** [comment]
My code has caused more than its fair share of trouble for others ;-)

Thanks for the quick fixes!
