### ISSUE TITLE
`confint.fixest()` breaks when there is only one coefficient to report

### ISSUE THREAD

**Issue by joachim-gassen** [lrberge/fixest#296]
Hi there:

First of all, thank you very much for creating and maintaining this great package. It has become a real Swiss army knife for all my regression needs ;-)

Today I encountered what I believe is a small bug in `confint.fixest()`. When it is called for a model with only one coefficient, it breaks. Below is a reprex:

```
# R 4.1.3, both on CRAN version 0.10.4 and development version 0.10.5
library(fixest)

mod <- feols(Sepal.Length ~ Sepal.Width + Petal.Length | Species, iris)
confint(mod)

#                     2.5 %   97.5 %
#   Sepal.Width  -0.2618362 1.126271
#   Petal.Length  0.2311479 1.320111
#

mod <- feols(Sepal.Length ~ Sepal.Width | Species, iris)
confint(mod)

# [1] 2.5 %  97.5 %
# <0 rows> (or 0-length row.names)
```

I looked into the code and it seems as if the snippet below is the culprit.

```
# From MiscFuns.R (lines 10555 and following)

	# The proper SE
	sum_object = summary(object, vcov = vcov, se = se, cluster = cluster, ssc = ssc, ...)

	se_all = sum_object$coeftable[, 2]
	coef_all = sum_object$coeftable[, 1]

	# the parameters for which we should compute the confint
	all_params = names(coef_all)
```

it breaks because it relies on the extract call on `sum_object$coeftable`  to return a named vector. This seems to be default behaviour when the data frame extract returns a vector with multiple elements but when the extract returns a single scalar (like above) `[` returns an unnamed scalar. I do not know how often I have run into similar issues in my own code...

I added the following code below  the `all_params = names(coef_all)` line:

```
	# The above drops all dimensions including the row names when there
	# is only one coefficient and the code relies on working on a named
	# vector, so...

	if(is.null(names(coef_all))) {
	    names(coef_all) <- row.names(sum_object$coeftable)
	    names(se_all)  <- row.names(sum_object$coeftable)
	}
```

This seems to fix the issue but is surely not the most elegant aproach. I can issue a PR if you like. Anyway: Thanks a lot again for all your wonderful work!

Joachim

**Comment by lrberge** [comment]
Hi Joachim, thanks a lot for the clear bug report with the complete solution. 
You've just nailed a bug that was hanging there for years :-)

And thanks for the kind words!

**Comment by joachim-gassen** [comment]
Glad to hear that it was helpful. Thanks!
