### ISSUE TITLE
Issue with dsb and notes

### ISSUE THREAD

**Issue by tejendrapsingh** [lrberge/fixest#298]
Hey!

I am trying to use dsb to put notes in the dictionary. However, when I use notes argument in the table function, the export to latex treats significance star as italics. I am wondering if there is a way to escape star when using dsb? I am posting the code below

`dict_names <- c("any.complication" = "Any Complication",
                  "hypertension" = "Hypertension",
                  "hypertension.eclampsia" = "Eclampsia",
                  "ruptured.uterus" = "Ruptured Uterus",
                  "mean.pollution.pre.conception" = paste0('Mean $PM2.5$ Pre-conception'),
                  "mean.pollution.trimester1" = paste0('Mean $PM2.5$ Trimester 1'),
                  "mean.pollution.trimester2" = paste0('Mean $PM2.5$ Trimester 2'),
                  "mean.pollution.trimester3" = paste0('Mean $PM2.5$ Trimester 3'),
                  "mean.pollution.postbirth" = paste0('Mean $PM2.5$ Post-birth'),
                  "mother.race.black" = "Race(= Black)",
                  "mother.race.other" = "Race(= Other)",
                  "birth.month" = "Birth Month",
                  "birth.year" = "Birth Year",
                  "state.id" = "State",
                  "year" = "Year",
                  "county.id" = "County",
                  "note1" = fixest::dsb("Heteroskedasticity robust standard errors clustered by the county are in parentheses (* p$<$.10 ** p$<$.05 *** p$<$.01). "))
  
  fixest::etable(models,
                 cluster = "county.id",
                 dict = dict_names,
                 drop = c("Intercept", names(my.dat)[names(my.dat) %like% '.tp.|.t2m.'], "mother.age.recode.41", "mother.educ.below.school", "mother.educ.school", 
                          "%^mother.race.black$", '%^mother.race.other$'),
                 digits = "r5",
                 digits.stats = 2,
                 fitstat = c("n", "war2"),
                 style.tex = fixest::style.tex("qje",
                                               fixef.suffix = " FEs",
                                               fixef.where = "var",
                                               yesNo = c(paste0("$", gsub(pattern = "checkmark", replacement = "\\\\c", x = "checkmark"), "heckmark$"),
                                                         paste0("$", gsub(pattern = "xmark", replacement = "\\\\x", x = "xmark"), "mark$"))),
                 tex = T,
                 adjustbox = paste0('max width=', paste0(gsub(pattern = "textwidth", replacement = "\\\\t", x = "textwidth")), 'extwidth',
                                    ',totalheight=', paste0(gsub(pattern = "textheight", replacement = "\\\\t", x = "textheight")), 'extheight'),
                 tpt = TRUE,
                 notes = c("note1")) %>%
    write(here::here('output', 'tables', 'table3hetero.tex'))`

**Comment by lrberge** [comment]
Hey @tejendrapsingh!

In fact `dsb` is only used to concatenate, and make operations on, strings. In your case, it is not needed.

I changed the way the parser evaluates the markdown markup, so that your example should be working with the current version. By the way, if needed you can now 'escape' the markdown parsing by adding a backslash before the stars, like in `\**` (although it's not needed in your example).
