### ISSUE TITLE
`browser()` leftover

### ISSUE THREAD

**Issue by vincentarelbundock** [lrberge/fixest#299]
I assume this is a leftover from debugging:

https://github.com/lrberge/fixest/blob/master/R/fixest_env.R#L919

**Comment by lrberge** [comment]
Oh no!!! All my tests are turning red too, thanks! :-)  

Actually I'm developing a multi-sample `subset` and this commit should never have been in the main branch. Don't know how it ended up there,  most likely reason is that I need sleep :-)

**Comment by lrberge** [comment]
All (visible) problems are fixed now.
