### ISSUE TITLE
Request: predict.fixest retains NAs

### ISSUE THREAD

**Issue by karldw** [lrberge/fixest#3]
I noticed that `fixest.predict` drops observations if `newdata` contains NAs. Could It instead have NA values for the output vector?

Demo:
``` r
new_data <- mtcars
new_data[1, ] <- NA
library(fixest)
x <- feols(wt ~ cyl, mtcars)
pred <- predict(x, newdata=new_data)
nrow(new_data)
#> [1] 32
length(pred)
#> [1] 31
```

<sup>Created on 2019-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lrberge** [comment]
Thanks! This is indeed not the expected behavior. 

Actually this is also the case for the original data!
``` r
base <- mtcars
base[1, ] <- NA
library(fixest)
x <- feols(wt ~ cyl, base)
pred <- predict(x)
nrow(base)
#> [1] 32
length(pred)
#> [1] 31
```
I initially thought it was a good idea, but now not so much any more. It's an easy fix, I'll fix it in the next update.

**Comment by lrberge** [comment]
I also added that FE values not existing in the original estimation now don't throw an error any more but instead are treated as NAs. Again, thanks a lot!
