### ISSUE TITLE
Polynomial terms and prediction with **new** data

### ISSUE THREAD

**Issue by rfbressan** [lrberge/fixest#301]
I guess this is related to #109 but a bit different. I have a polynomial regression and want to make predictions on new (contractual) data. I got a _"model frame and formula mismatch in model.matrix()"_ error. The MWE follows below:

``` r
library(fixest)

data("base_did")
est_bis <- feols(y ~ poly(x1, 2) + i(period, treat, 5) | id, 
                 data = base_did)
pred1 <- predict(est_bis) # OK, no problems

# Modify data and make new predictions
new_data <- base_did
new_data$treat <- 0
predict(est_bis, newdata = new_data) # Error
#> Error: in predict.fixest(est_bis, newdata = new_data):
#>  Error when creating the linear matrix: 
#>   In model.matrix.default(fml, mf): model frame and formula mismatch in
#> model.matrix()

packageVersion("fixest")
#> [1] '0.10.4'
```

<sup>Created on 2022-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

PS: Thank you for the excellent package you put together @lrberge !

EDIT: I did the reprex outside my project and it was running v0.10.2. Updated to v0.10.4, the problem persists.

**Comment by lrberge** [comment]
Hi, indeed that's a bug (there were svl in fact) which was in fact due to `i()`. Now corrected.

Thanks for the reprex and the kind word!
