### ISSUE TITLE
etable better LaTex codes printing 

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#303]
I typically use etable to print LaTex codes on R console before copying them to a LaTex file. I noticed that sometimes `\&` is printed as `\   &`, which makes the LaTex codes fail to compile. Not sure how to solve this issue.

**Comment by lrberge** [comment]
Hi, indeed, that was a bug recently introduced (when I made the display of the table nicer) and is now corrected. Thanks.
