### ISSUE TITLE
Strange bug with i() and targets in latest github version

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#304]
Hey Laurent,

Just updated to the latest Github version and started running into a really strange bug with i() that seems to only happen within targets. In my targets pipeline, running any feols() estimation with a formula that includes a call to i() produces the following error:

```
Error: Evaluation of the right-hand-side of the formula raises an error: 
  In as.character(x[[1]]): cannot coerce type 'closure' to vector of type 'character'
```

Could it be that i() is trying to refer to a character vector in the global environment that is masked by a function made available via targets? This reproducible example seems to throw the error:

```
library(targets)
tar_dir({
    tar_script({
        fixest_test <- function() {
            library(fixest)
            data(airquality)
            aq = airquality
            aq$week = aq$Day %/% 7 + 1
            res_2F_bis = feols(Ozone ~ Solar.R + i(Month), aq)
        }
        list(
            tar_target(test, fixest_test())
        )
    }, ask = FALSE)
    tar_make(test)
})
```

**Comment by lrberge** [comment]
Hi Adam, yeah I made a rookie mistake in analyzing calls when I added new stuff. 
Fixed: and thanks for the reproducible example!
