### ISSUE TITLE
 style.tex("aer") checkmark 

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#305]
Is the \checkmark macro from the package amssymb?

**Comment by lrberge** [comment]
Yes.

> **yesNo**
> A character vector of length 1 or 2. Defaults to "Yes" if main = "base" and to "$\\checkmark$" if main = "aer" (from package amssymb). This is the message displayed when a given fixed-effect is (or is not) included in a regression. If yesNo is of length 1, then the second element is the empty string.

https://lrberge.github.io/fixest/reference/style.tex.html
