### ISSUE TITLE
Binaries through r-universe

### ISSUE THREAD

**Issue by SebKrantz** [lrberge/fixest#307]
Just FYI: I have created a [fastverse r-universe](https://fastverse.r-universe.dev/) as an alternative source for Mac / Windows binaries to CRAN (particularly for binaries of development versions not yet on CRAN). I have included fixest, so binaries of the development version on GitHub can be installed using

```
install.packages("fixest", 
    repos = c(ropensci = 'https://fastverse.r-universe.dev', 
              CRAN = 'https://cloud.r-project.org')) # Needed for dependencies
```
However your GH version [curently fails to build](https://github.com/r-universe/fastverse/actions/runs/2321401874) because of some test failure. Again this is not an issue, but perhaps an interesting possibility for your users.

**Comment by lrberge** [comment]
Thanks a lot Sebastian! It's something that I really wanted to do, so thanks a lot for doing it!

Since the package will now be automatically built, now I should be a little bit less careless in my workflow ;-) and really start using that dev branch!

Thanks again!

**Comment by lrberge** [comment]
Just added it in the README!

**Comment by SebKrantz** [comment]
Cool. Yeah I also use a development branch and have only stable releases in master. You can also include a badge: 

[![fixest status badge](https://fastverse.r-universe.dev/badges/fixest)](https://fastverse.r-universe.dev)

**Comment by lrberge** [comment]
Good idea!
