### ISSUE TITLE
Residuals in IV estimation with feols 

### ISSUE THREAD

**Issue by emmettsaulnier** [lrberge/fixest#312]
Hey Laurent,

Thank you for creating and maintaining such an incredible package. 

I noticed what I think is a bug in how R-Squared is calculated for IV models estimated with `feols`. Say we have a fixest object `est_iv`. The correct residuals look to be saved as `est_iv$iv_residuals`, but when you run `resid(est_iv)` it pulls `est_iv$residuals`. I couldn't find documentation on the difference between `est_iv$iv_residuals` and `est_iv$residuals`, but if I manually calculate what the residuals should be by subtracting the fitted values from the actual outcome, then the result is equal to `est_iv$iv_residuals`. 

The consequence is that it looks like `est_iv$residuals` are being used to calculate R-Squared (and other fit statistics) --- which would lead to incorrect calculations if the `est_iv$residuals` are in fact incorrect. 

Below is a reproducible example.

```
# IV example from fixest vignette
base = iris
names(base) = c("y", "x1", "x_endo_1", "x_inst_1", "fe")
set.seed(2)
base$x_inst_2 = 0.2 * base$y + 0.2 * base$x_endo_1 + rnorm(150, sd = 0.5)
base$x_endo_2 = 0.2 * base$y - 0.2 * base$x_inst_1 + rnorm(150, sd = 0.5)

est_iv = feols(y ~ x1 | x_endo_1 ~ x_inst_1 + x_inst_2, base)

# Pulling residuals and fitted values
resids = resid(est_iv)
fitted = fitted(est_iv)
resids_manual = base$y - fitted

# Calculating sums of squares
TSS = sum((base$y - mean(base$y))^2)
ESS = sum((fitted - mean(base$y))^2)
RSS = sum(resids^2)
RSS_manual = sum(resids_manual^2)

# What is reported r2?
r2(est_iv, type = "r2")
#>      r2 
#> 0.839079 
1 - (RSS/TSS) # Calculated using est_iv$residuals
#> 0.839079

# What I think is the correct R2, using manually calculated residuals
ESS/TSS
#> 0.7236363
1 - (RSS_manual/TSS)
#> 0.7236363

# Seems like we need iv_residuals 
iv_residuals = est_iv$iv_residuals
all.equal(iv_residuals, resids_manual)
#> TRUE
```
 
The reason I noticed this issue is because I was getting a negative R-Squared for some models that I had fit.

**Comment by lrberge** [comment]
Hi Emmett, don't you think that would have been a pretty obvious bug? ;-)
No, I know it feels weird but it's correct. The thing is that the R2 in the context of IVs does not make much sense. 
See this very nice [Stata FAQ for instance](https://www.stata.com/support/faqs/statistics/two-stage-least-squares/).
I may add a line in the doc on that issue because for sure it can be confusing.

> Thank you for creating and maintaining such an incredible package.

Thanks a lot! :-)
