### ISSUE TITLE
Use vendoring to avoid CRAN checks blah blah

### ISSUE THREAD

**Issue by pachadotdev** [lrberge/fixest#322]
It would be good to use **vendoring** to avoid installation failures.

Vendoring has advantages and drawbacks however. The advantage is that changes to the cpp11 project could never break your existing code. The drawbacks are both minor, your package size is now slightly larger, and major, you no longer get bugfixes and new features until you explicitly update cpp11. Reference: https://cpp11.r-lib.org/articles/motivations.html#vendoring-1

To use this, we would need to alter parts of the code, to use cpp11 instead of Rcpp. I already did a large part of that but my install doesn't work. See https://github.com/pachadotdev/fixest/tree/cpp11

**Comment by pachadotdev** [comment]
At the moment I have this error

```
/usr/lib/R/site-library/cpp11/include/cpp11/r_vector.hpp: In instantiation of ‘cpp11::writable::r_vector<T>::r_vector(Iter, Iter) [with Iter = int; T = int]’:
misc_funs.cpp:448:44:   required from here
/usr/lib/R/site-library/cpp11/include/cpp11/r_vector.hpp:680:15: error: invalid type argument of unary ‘*’ (have ‘int’)
  680 |     push_back(*first);
      |               ^~~~~~
make: *** [/usr/lib/R/etc/Makeconf:177: misc_funs.o] Error 1
ERROR: compilation failed for package ‘fixest’
```

And I'm not sure about this replacement for "colnames"
https://github.com/pachadotdev/fixest/blob/cpp11/src/misc_funs.cpp#L708

**Comment by waynelapierre** [comment]
cpp11 doesn't support OpenMP.
