### ISSUE TITLE
R/etable.R: Combining character and factor in older versions of R creates NA

### ISSUE THREAD

**Issue by michaelquinn32** [lrberge/fixest#327]
In earlier versions of R (say pre 4.0) this line produces a data frame of NA values:
https://github.com/lrberge/fixest/blob/680972c23bef24a18840b295d129d00629dc17a4/R/etable.R#L4729

I believe that this fix is to call format() on the data frame during rbind(), which should ensure all of the values are coerced to character. But please let me know if that isn't delivering the output that you want here.

Thanks!

**Comment by lrberge** [comment]
Thanks a lot: related to #353. One more piece of the puzzle!

**Comment by lrberge** [comment]
Hi, I've fixed various bugs with R 3.5.0, now it should work. Thanks for reporting.
