### ISSUE TITLE
Exponentiation option in `tidy` for `feglm` objects

### ISSUE THREAD

**Issue by abduazizR** [lrberge/fixest#329]
Hi,

I wanted to ask if the `exp` argument in the `broom::tidy()` function should work with `feglm` objects. I want to extract odds ratios but 

Here is a reproducible example

``` r
library(tidyverse)
library(fixest)
library(broom)
z <- feglm(am ~ cyl + hp + wt, data = mtcars, family = binomial)

z %>% tidy(conf.int = T, exp = T)
#> # A tibble: 4 × 7
#>   term        estimate std.error statistic p.value  conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>     <dbl>     <dbl>
#> 1 (Intercept)  19.7       8.54       2.31   0.0210   2.96      36.4   
#> 2 cyl           0.488     1.13       0.432  0.665   -1.72       2.70  
#> 3 hp            0.0326    0.0198     1.64   0.101   -0.00631    0.0715
#> 4 wt           -9.15      4.37      -2.09   0.0363 -17.7       -0.584
```

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Here is my `sessionInfo()` output
``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22000)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.utf8 
#> [2] LC_CTYPE=English_United States.utf8   
#> [3] LC_MONETARY=English_United States.utf8
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.29   withr_2.5.0     magrittr_2.0.3  reprex_2.0.1   
#>  [5] evaluate_0.15   highr_0.9       stringi_1.7.6   rlang_1.0.3    
#>  [9] cli_3.3.0       rstudioapi_0.13 fs_1.5.2        rmarkdown_2.14 
#> [13] tools_4.2.1     stringr_1.4.0   glue_1.6.2      xfun_0.31      
#> [17] yaml_2.3.5      fastmap_1.1.0   compiler_4.2.1  htmltools_0.5.2
#> [21] knitr_1.39
```

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thank you in advance.

**Comment by grantmcdermott** [comment]
Hi again @abduazizR.

The [`tidy.fixest`](https://broom.tidymodels.org/reference/tidy.fixest.html) method doesn't support an "exp(onentiate)" argument. This argument is only supported by [`tidy.glm`](https://broom.tidymodels.org/reference/tidy.glm.html) AFAIK.

I'd recommend closing this issue and instead raising it at the [**broom** repo](https://github.com/tidymodels/broom), where the methods are maintained. Note that it would be fairly trivial to implement, but the **broom** team recently decided to become very strict about adding new arguments to existing tidiers. So, fair warning that you might not be able to convince them.

PS. I know it's a bit of a pain, but you can always exponentiate the tidied DF manually.

```r
tidy(z, conf.int = TRUE) |>
  mutate(across(c(estimate, conf.low, conf.high), exp)
```

**Comment by abduazizR** [comment]
Problem was solved for me.
