### ISSUE TITLE
Would you have a plan to transfer this package into python form or offer a python API?  Thx

### ISSUE THREAD

**Issue by kennyzjc1994** [lrberge/fixest#331]
I am a student who has some experience about `reghdfe`  in Stata, and `LinearModels` in Python. I have little knowledge about how to use R. Your package `fixest` is very great to run `PanelOLS` and I hope this code can be used in Python as a pure python code as well, without the `rpy2` as a bridge. 

You know, run a fixed effect model with high performance in Python platform is hard. Python community/platform really needs a package like `fixest` to handle this embarrassed situation. 

I don't know how hard this work is, I just make some expectation and show how I love your work. Thanks for your excellent work on `fixest`.

**Comment by InaKrapp** [comment]
Hello, this is over a year old now and I'm not sure if it is still helpful, but I'd like to point out that [s3alfisc](https://github.com/s3alfisc/pyfixest/commits?author=s3alfisc) created a Python clone of the fixest package:
https://github.com/s3alfisc/pyfixest

**Comment by lrberge** [comment]
I have no plan at all to port `fixest` to python, but @s3alfisc is doing a great job!
