### ISSUE TITLE
Can I get the vcov matrix for the aggregated coefficients in the Sun & Abaham method? 

### ISSUE THREAD

**Issue by lzy318** [lrberge/fixest#332]
Can I get the vcov matrix for the aggregated coefficients in the Sun & Abaham method? By now, the command can only return the vcov matrix for the original regression.

**Comment by grantmcdermott** [comment]
Same underlying issue as https://github.com/lrberge/fixest/issues/295

if I’m not mistaken, this is how it’s calculated in the code. https://github.com/lrberge/fixest/blob/839fa9b451759463cd89a03f1ccae89eaf3d39dc/R/did.R#L491-L525
