### ISSUE TITLE
Trouble when extracting SEs / CIs

### ISSUE THREAD

**Issue by effedp** [lrberge/fixest#334]
Hi Laurent,

Thanks for your excellent work.

I am trying to export a very simple CSV file with the coefficients of a `feols` regression and the associated CIs (or SEs).
Still, I am struggling to do so.

I tried to use `coeftable', but I got the error

`Error in coeftable(avg.TFP.firmlevel): Sorry, the coeffficients table could not be extracted`

with no further information.

Similarly, when I try to use `confint`, I get

`Error in UseMethod("vcov"): no applicable method for 'vcov' applied to an object of class "fixest_multi"`

And neither `se` seems to work:

`Error in coeftable(object, vcov = vcov, ssc = ssc, cluster = cluster, : Sorry, the coeffficients table could not be extracted`

Do you have any clue about what is going on? Any workaround for extracting such a simple dataset?

Thank you very much for your help!

**Comment by grantmcdermott** [comment]
Hi @effedp, could you give a bit more information about your `sessionInfo()`? 

Note that a version of this CI issue has been cropping up elsewhere (e.g. #328). The good news is that it appears to be resolved by installing the latest dev version (10.5) of **fixest**.

```r
install.packages("fixest", repos = c(ropensci = 'https://fastverse.r-universe.dev'))
```

**Comment by effedp** [comment]
Hey @grantmcdermott, sorry for the late reply, but I am not working on my own machine.

I am using R 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64 bit)
Running under: Windows Server x64

Matrix products: default

I sadly cannot try the dev version on this machine!

**Comment by grantmcdermott** [comment]
Bummer. I think the only thing do is request your admin team to install the dev version as per the above. (It installs a binary version for Windows, so there should at least be no compiling requirement.) Otherwise just have to sit tight until the next CRAN release...

**Comment by lrberge** [comment]
@effedp: _coeftable_ hasn't been implemented for multiple estimations in versions <= 0.10.4. I've done it properly in the dev now, but well... it's the dev. (And thanks for the words ;-))

@grantmcdermott: Damn I feel bad.... this version is really getting a loooong time to get out... 
The big deal is that I've decided to streamline some parts of the code and hence I'm creating a new package on string manipulation (I'm really enthusiastic about it btw! [not available online yet though]). I'm +/- done with the code but I need to finish, and doc + vignette always take time. 
I also found a great algorithm that I want to adapt from collapse (thanks @SebKrantz!) to turn vectors into integers which may lead to speed gains on specific cases. 
And I'm also in the middle of a few big changes.
Grant, I'm waiting for 1.0.0 to start writing the paper. I'm afraid this paper will never get out :-/

**Comment by grantmcdermott** [comment]
Ha, no need to feel bad @lrberge. We're all in your debt for fixest anyway. (And strong endorse for collapse while we're at it.)

**Comment by SebKrantz** [comment]
As you are doing that (which you are very welcome to), please also give
credence to Morgan Jacob from {kit} which developed the hash function I
used to build this algorithm. I note that collapse::group() also provides
direct access to the algorithm, but I fully understand it if you‘d rather
copy the code/translate to C++ rather than importing collapse or using it
conditionally.

**Comment by lrberge** [comment]
Indeed, I should have given credit to Morgan Jacob (I was fast sorry!). 
I really like the idea of the algorithm, it's super smart. The hashing + handling collisions just like that, pretty cool.

I will not add a collapse dependency, I'll be taking the idea of the algorithm but adapt it to my specific needs. Don't worry I'll give full credit in the code! ;-)

Always cool to learn nice stuff from others' code. Open source rocks!
