### ISSUE TITLE
Same estimation, but different standard errors when using split vs fsplit in the presence of large amounts of interacted FEs

### ISSUE THREAD

**Issue by phenschke** [lrberge/fixest#335]
Hi, thanks for the great package!

I've encountered an issue where I obtain different standard errors from the same specification (only difference is the split vs fsplit argument to split the sample).
I couldn't get the bug to reproduce with randomly generated data, so no MWE, sorry.

I have three-dimensional panel data (country, year, tech) and I'm running regressions using a large amount of interacted fixed effects, namely tech^year + tech^country.

Specifically, the specification I am estimating is
```
with_fsplit <- feols(ltech_pc ~ tyr + log(gdppc) | tech^year + tech^country,
                    data = df, 
                    vcov = cluster ~ country, 
                    fsplit = ~rich)

etable(with_fsplit) 
                         model 1          model 2         model 3
Sample (rich)        Full sample            FALSE            TRUE
Dependent Var.:         ltech_pc         ltech_pc        ltech_pc
                                                                 
tyr                0.034 (0.037)   -0.020 (0.037)  0.116* (0.051)
log(gdppc)      0.487*** (0.107) 0.430*** (0.095) 1.05*** (0.249)
Fixed-Effects:  ---------------- ---------------- ---------------
tech-year                    Yes              Yes             Yes
tech-country                 Yes              Yes             Yes
_______________ ________________ ________________ _______________
S.E.: Clustered      by: country      by: country     by: country
G                            101               74              27
Observations              30,638           18,457          12,181
Adj. R2                  0.98717          0.98790         0.98925
Within Adj. R2           0.04163          0.03107         0.14899
```

Now the issue is that when I estimate the exact same specification using `split` instead of `fsplit`, the standard errors are different:
```
with_split <- feols(ltech_pc ~ tyr + log(gdppc) | tech^year + tech^country,
                   data = df, 
                   vcov = cluster ~ country, 
                   split = ~rich)

etable(with_split)
                         model 1        model 2
Sample (rich)              FALSE           TRUE
Dependent Var.:         ltech_pc       ltech_pc
                                               
tyr               -0.020 (0.041) 0.116. (0.059)
log(gdppc)      0.430*** (0.105) 1.05** (0.285)
Fixed-Effects:  ---------------- --------------
tech-year                    Yes            Yes
tech-country                 Yes            Yes
_______________ ________________ ______________
S.E.: Clustered      by: country    by: country
G                             74             27
Observations              18,457         12,181
Adj. R2                  0.98790        0.98925
Within Adj. R2           0.03107        0.14899
```
As you can see, the coefficient estimates are the same, but the standard errors differ.
This output might be helpful:
```
> with_fsplit[[3]]$fixef_sizes
 tech^year tech^country 
        2004         1009 
> with_split[[2]]$fixef_sizes
 tech^year tech^country 
        1009         2004 
> degrees_freedom(with_fsplit[[3]], "k")
[1] 3
> degrees_freedom(with_split[[2]], "k")
[1] 2902

```
Here is an upload of the data to allow reproduction:
[repro_fixest_bug.csv](https://github.com/lrberge/fixest/files/9124356/repro_fixest_bug.csv)

**Comment by s3alfisc** [comment]
Hi @phenschke, can you check if the differences vanish if you enforce the same small sample corrections via the 'ssc()' function? E.g. what happens if you set 'ssc(adj = FALSE, cluster.adj = FALSE)'?

**Comment by phenschke** [comment]
Just tried that:
If I use `ssc(adj = FALSE, cluster.adj = FALSE)` or `ssc(adj = FALSE, cluster.adj = TRUE)` the SE difference vanishes.
If I use `ssc(adj = TRUE, cluster.adj = FALSE)` or `ssc(adj = TRUE, cluster.adj = TRUE)` there is a difference.
Additionally, the difference only occurs if I `fixef.K = nested` is used (which is the default). 

So it must be due to differences in how the fixed effects that are nested in clusters are determined, which leads to different Ks in the small-sample correction.

Might be related to the number of tech^year and tech^country fixed effects being flipped when using split vs fsplit?
fixest also warns that the fixed effects are not regular when I call `fixef()`.
```
> with_fsplit[[3]]$fixef_sizes
 tech^year tech^country 
        2004         1009 
> with_split[[2]]$fixef_sizes
 tech^year tech^country 
        1009         2004 
```
I've checked and for 901 tech-country pairs (and for 90 tech-year pairs) there is only one observation. 
So these 991 almost make up the 995 (= 2004 - 1009) difference  between the number of fixed effects (there's probably 4 with more than one observation, but no variation?).

**Comment by lrberge** [comment]
Hi, it looks like a bug indeed. I couldn't check on my laptop yet. 
However, I have corrected something related in v. 0.10.5. Is it the version you're using? If not, could you update and see if it's still present?

**Comment by phenschke** [comment]
Hi, I was using 0.10.4 from CRAN. I updated to 0.10.5 and that fixed the issue. 
`with_fsplit[[3]]$fixef_sizes` now also yields 1009 tech^year and 2004 tech^country FEs. 

Thanks!
