### ISSUE TITLE
Acess Original DataFrame or/and panel.id columns from a fixest model

### ISSUE THREAD

**Issue by sondalex** [lrberge/fixest#337]
Hi, is there a way to access the `panel.id` columns of a fixest object ?

Method `model.matrix(...)` with type parameter value set to `"lhs"`, `"rhs"`, `"fixef"` gets transformed dependent variable, transformed regressors and  fixed effects columns respectively.
But there is no possibility of accessing `panel.id` columns if fixed effects do not include all `panel.id` columns.

## Use case example:

Adding a statistical tests  that requires accessing columns specified in `panel.id` because it uses a statistical function from an existing package (`plm` for example).

--------

Is it also possible to access the original dataframe from a fixest object ?

**Comment by grantmcdermott** [comment]
You can get the original data frame just by evaluating the model call. E.g.

```r
library(fixest)
mod = feols(y ~ l(x1, 0:1), base_did, panel.id = ~id+period)
eval(mod$call$data)
eval(mod$call$data)[, mod$panel.id]
```

(Aside: Note that you'd need to combine that above with `mod$call$subset` if this argument had been used to subset the data dynamically.)

**Comment by sondalex** [comment]
Thank you for your help :smile:

**Comment by lrberge** [comment]
Hi, there's no direct method to get the `panel.id` at the moment. Adding it to `model.matrix` is a good idea, and I'll follow the suggestion.

In the meantime, to complete the answer from Grant: you can get the data with `fixest:::fetch_data()` and you can get the observations used for the estimation with `obs()`.

Example:

```R
base = setNames(iris, c("y", "x1", "x2", "x3", "species"))
base$y[1:5] = NA
est = feols(y ~ x.[1:3], base, subset = ~x3 < mean(x3))
#> NOTE: 5 observations removed because of NA values (LHS: 5).
db = fixest:::fetch_data(est)
db = db[obs(est), ]
dim(db)
#> [1] 55  5
head(db)
#>      y  x1  x2  x3 species
#> 6  5.4 3.9 1.7 0.4  setosa
#> 7  4.6 3.4 1.4 0.3  setosa
#> 8  5.0 3.4 1.5 0.2  setosa
#> 9  4.4 2.9 1.4 0.2  setosa
#> 10 4.9 3.1 1.5 0.1  setosa
#> 11 5.4 3.7 1.5 0.2  setosa
```

**Comment by sondalex** [comment]
Thank you for completing the answer
