### ISSUE TITLE
`fitstat` and `model.matrix` unexpected results with complex data structures 

### ISSUE THREAD

**Issue by sondalex** [lrberge/fixest#339]
Hi,

I have noticed a use case where the `fitstat` statistics which depend on
`model.matrix` return wrong results.

**Reproducible example:**

``` r
library(fixest)
data(Wages, package='plm')
library(dplyr)

fml <- lwage ~ exp + wks + ed | ind + south + smsa + sex + married + black + union


# Convert labels to Dummy variables
Wages[, c("bluecol", "south", "married", "smsa", "sex", "union", "black")] <- sapply(Wages[, c("bluecol", "south", "married", "smsa", "sex", "union", "black")], as.numeric) - 1


data1 <- Wages
data2 <- Wages %>% group_by(ind, sex, black, smsa, union, south) %>% summarize(across(everything(), ~ mean(.))) # aggregate dataset

(nrow(data1))
```

    ## [1] 4165

``` r
(nrow(data2))
```

    ## [1] 47

Joining arguments in a list for further iteration creates wrong results.

``` r
arguments_1 <- list(fml, data1)
arguments_2 <- list(fml, data2)

arguments <- list(arguments_1, arguments_2)

models <- vector(mode="list", 2)

for (i in 1:length(models)) {
  models[[i]] <- feols(arguments[[i]][[1]], data=arguments[[i]][[2]])
}

custom_stat <- function(x) {
  y_transformed <- model.matrix(x, 'lhs')
  number_rows <- length(y_transformed)
  return(list(n = number_rows))
}

fitstat_register("custom_rows", custom_stat, "Number of rows", c("n"))
print(etable(models, fitstat = ~ custom_rows.n + my))
```

    ##                             model 1          model 2
    ## Dependent Var.:               lwage            lwage
    ##                                                     
    ## exp                0.0108. (0.0010)  0.0008 (0.0067)
    ## wks                 0.0046 (0.0043)  0.0155 (0.0516)
    ## ed                0.0713** (0.0010) 0.0650* (0.0010)
    ## Fixed-Effects:    ----------------- ----------------
    ## ind                             Yes              Yes
    ## south                           Yes              Yes
    ## smsa                            Yes              Yes
    ## sex                             Yes              Yes
    ## married                         Yes              Yes
    ## black                           Yes              Yes
    ## union                           Yes              Yes
    ## _________________ _________________ ________________
    ## S.E.: Clustered             by: ind          by: ind
    ## Number of rows, n                47               47
    ## Dep. Var. mean               6.4610           6.4610
    ## ---
    ## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

The custom statistic and internal statistic “my” yields the same result
in both columns. This should not be the case. This behaviour is due to
`model.matrix` retrieving the last data element in the `arguments` list.

This can be confirmed by reversing arguments:

``` r
arguments  <- rev(arguments)
for (i in 1:length(models)) {
  models[[i]] <- feols(arguments[[i]][[1]], data=arguments[[i]][[2]])
}
print(etable(models, fitstat = ~ custom_rows.n + my))
```

    ##                            model 1           model 2
    ## Dependent Var.:              lwage             lwage
    ##                                                     
    ## exp                0.0008 (0.0067)  0.0108. (0.0010)
    ## wks                0.0155 (0.0516)   0.0046 (0.0043)
    ## ed                0.0650* (0.0010) 0.0713** (0.0010)
    ## Fixed-Effects:    ---------------- -----------------
    ## ind                            Yes               Yes
    ## south                          Yes               Yes
    ## smsa                           Yes               Yes
    ## sex                            Yes               Yes
    ## married                        Yes               Yes
    ## black                          Yes               Yes
    ## union                          Yes               Yes
    ## _________________ ________________ _________________
    ## S.E.: Clustered            by: ind           by: ind
    ## Number of rows, n            4,165             4,165
    ## Dep. Var. mean              6.6763            6.6763
    ## ---
    ## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

The statistics are normally :

``` r
model1 <- feols(arguments_1[[1]], data=arguments_1[[2]])
model2 <- feols(arguments_2[[1]], data=arguments_2[[2]])

etable(list(model1, model2), fitstat = ~ custom_rows.n + my)
```

    ##                             model 1          model 2
    ## Dependent Var.:               lwage            lwage
    ##                                                     
    ## exp                0.0108. (0.0010)  0.0008 (0.0067)
    ## wks                 0.0046 (0.0043)  0.0155 (0.0516)
    ## ed                0.0713** (0.0010) 0.0650* (0.0010)
    ## Fixed-Effects:    ----------------- ----------------
    ## ind                             Yes              Yes
    ## south                           Yes              Yes
    ## smsa                            Yes              Yes
    ## sex                             Yes              Yes
    ## married                         Yes              Yes
    ## black                           Yes              Yes
    ## union                           Yes              Yes
    ## _________________ _________________ ________________
    ## S.E.: Clustered             by: ind          by: ind
    ## Number of rows, n             4,165               47
    ## Dep. Var. mean               6.6763           6.4610
    ## ---
    ## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Down below we see that the issue comes from `model.matrix`.

``` r
(length(model.matrix(models[[1]], "lhs")))
```

    ## [1] 4165

``` r
(length(model.matrix(models[[2]], "lhs")))
```

    ## [1] 4165

-------

This behaviour can be problematic in cases where multiple columns with different formulas and data should be joined in the same table
. Iterating through a list of arguments can result in "cleaner" code rather than writing multiple `feols` calls.

```
m1 <- feols(...)
m2 <- feols(...)
m3 <- feols(...)
...
m7 <- feols(...)
etable(list(m1, m2, m3, ..., m7))
```

**Comment by lrberge** [comment]
Hi, this is a known problem affecting loops. Solutions are being worked out. I'm moving this issue to #340.
