### ISSUE TITLE
Error message with feols.fit and vcov

### ISSUE THREAD

**Issue by grlju** [lrberge/fixest#341]
Hi, 

First, thanks for the amazing package!

I am getting the following error message, and I am not sure it is desired behavior. 

Below is a quick example using the trade dataset: 

This works fine:
```
library(fixest)
data(trade)
feols(Euros ~ dist_km, trade, vcov = "hetero")
```
But when I try to use the `vcov` argument with `feols.fit`, to estimate the same model:  
```
feols.fit(y = as.matrix(trade["Euros"]), X = as.matrix(trade["dist_km"]), vcov = "hetero")
Error in feols.fit(y = trade["Euros"], X = trade["dist_km"], vcov = "hetero") : 
  Problem in the VCOV:

  object 'fe_vars' not found

# same for iid 
feols.fit(y = as.matrix(trade["Euros"]), X = as.matrix(trade["dist_km"]), vcov = "iid")
```

Works without the 'vcov' argument:
```
feols.fit(y = as.matrix(trade["Euros"]), X = as.matrix(trade["dist_km"]))
```

If I include fixed effects, it works as well: 
```
feols.fit(y = as.matrix(trade["Euros"]), X = as.matrix(trade["dist_km"]), fixef_df = as.matrix(trade["Destination"]), vcov = "hetero")
```

I may be missing something, and the `vcov` argument needs to be used differently with `feols.fit`. 

Thanks!
Greg

**Comment by lrberge** [comment]
Hi Greg, and thanks for reporting!
It's indeed a bug that occurred only when fixed-effects were absent. Now corrected in the dev branch.
Thanks again!
