### ISSUE TITLE
Interaction with endogenous variables

### ISSUE THREAD

**Issue by ik4Rus** [lrberge/fixest#344]
Hi, 

I have two questions about interaction with endogenous variables. 
I am interested in a multi-interaction. In the following you will find a minimal example: 
```
library(fixest)
data_example <- iris
data_example$bool_var <- sample(c(F, T), replace = T, nrow(iris))
res = feols(Sepal.Length ~ Sepal.Width * Petal.Length * bool_var, data_example)
```

- **Specification of interaction**: Am I allowed to write the model like this (without `i` notation)? If not, how to write it with three interaction variables?
- **Adding endogeneity to interaction**: How can I model that bool_var is endogenous (assuming `bool_var` is endogenous with instrument `Petal.Width `)? 
```
res_end = feols(Sepal.Length ~ Sepal.Width * Petal.Length * bool_var| bool_var ~ Petal.Width, data_example)
```
This produces an error, that makes sense - but I can't see how to write it correctly. 
```
Error in feols(Sepal.Length ~ Sepal.Width * Petal.Length * bool_var | : 
                 Endogenous variables should not be used as exogenous regressors. The variable 'bool_varTRUE' was found in the first part of the multipart formula: it should not be there.
```  

I can't really use other libraries as I also have fixed effects with very high cardinality. If you know another way, that would help a lot too. 

Thank you very much for the support!
Ingo

**Comment by grantmcdermott** [comment]
1. Yes, it's totally fine to use base interaction operators like `*` in `feols()`. See https://github.com/lrberge/fixest/issues/166 for more on threeway interactions using `i()`.
2. Unless I'm missing something, I think you just want to writing out the full interaction in the IV slot.

```r
# Imagine Petal.Length is endogenous
ols = feols(Sepal.Length ~ Sepal.Width * Petal.Length, iris) 
iv  = feols(Sepal.Length ~ 1 | Sepal.Width * Petal.Length ~ Sepal.Width * Petal.Width, iris) 
etable(ols, iv)
```

**Comment by grantmcdermott** [comment]
@ik4Rus Were you able to test the above solution? If it works, please let us know and then close this issue to reduce dev clutter.

**Comment by lrberge** [comment]
Hi, and thanks Grant for weighting in!
It seems it is a conceptual problem and not a problem with the software. So I'm closing.
