### ISSUE TITLE
Problem with multiple dependent variables

### ISSUE THREAD

**Issue by jc-castillo** [lrberge/fixest#347]
@lrberge, thanks for the great package!

I either found a bug, or there's something in the documentation I'm getting terribly wrong. Here's a minimal working example:

```
library(fixest)

n <- 10000
df <- data.frame(x=runif(n), y=runif(n), w1=runif(n), w2=runif(n), z1=runif(n), z2=runif(n), g=round(5*runif(n)))
feols(y ~ x | g | c(w1, w2) ~ z1 + z2, df)
```

Here's the output:
```
Error in feols(y ~ x | g | c(w1, w2) ~ z1 + z2, df) : 
  Evaluation of the left-hand-side of the IV part (equal to c(w1, w2)) raises an error: 

  In dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
```

**Comment by jc-castillo** [comment]
I think I realized what's going on. The syntax should be
```
feols(y ~ x | g | w1 + w2 ~ z1 + z2, df)
```

But that's not what the documentation suggests. Under **Arguments**, it says "To add IVs, insert the endogenous vars./instruments after a pipe, like in `y ~ x | c(x_endo1, x_endo2) ~ x_inst1 + x_inst2`". That should be changed to `y ~ x | x_endo1 + x_endo2 ~ x_inst1 + x_inst2`

**Comment by lrberge** [comment]
Thanks a lot: it was a vicious and important documentation error! Now fixed. Thanks for reporting.
