### ISSUE TITLE
Feature suggestion for  `etable` - add information about dependencies 

### ISSUE THREAD

**Issue by Oravishayrizi** [lrberge/fixest#349]
Hi Laurent!

Sometimes when I export latex tables using `etable` I can't compile it as the output uses a package I didn't use.
I think that users might benefit from comments in the beginning of the tex output that specifies all latex dependencies. 

To fix Ideas, when I run the following code:

```
library(fixest)
lm1<-feols(Sepal.Length~Petal.Width|Species,data=iris)
etable(lm1,tex = TRUE)
```

I would like to see something like that:

```
%\usepackage{booktabs}       - I add this line which specifies a package that is used to compile this table in LATEX

\begingroup
\centering
\begin{tabular}{lc}
\tabularnewline \midrule \midrule
Dependent Variable: & Sepal.Length\\  
Model:              & (1)\\  
\midrule
\emph{Variables}\\
Petal.Width         & 0.9169$^{*}$\\   
& (0.2766)\\   
\midrule
\emph{Fixed-effects}\\
Species             & Yes\\  
\midrule
\emph{Fit statistics}\\
Observations        & 150\\  
R$^2$               & 0.66937\\  
Within R$^2$        & 0.13286\\  
\midrule \midrule
\multicolumn{2}{l}{\emph{Clustered (Species) standard-errors in parentheses}}\\
\multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup
```

**Comment by etiennebacher** [comment]
FYI this is mentioned at the beginning of the doc for `etable()`:

![image](https://user-images.githubusercontent.com/52219252/189666486-6ebb4fde-af77-41f3-92b2-5e28575caa97.png)

**Comment by Oravishayrizi** [comment]
Hi, thx for the reply.
This was just an example to illustrate my point, don't take it too literally.

Different setups require different packages; while they all may appear in the doc, I think that people may find it useful to get an explicit list of the required packages at the beginning of the table. 

Other examples are:
- `style.tex("aer")` that uses `amssymb` for the `\checkmark`
- adjustbox
- threeparttable 
- I think that highlighting cell depend on `colortbl` and `xcolor`

**Comment by lrberge** [comment]
Hi Or, indeed, it depends on which feature is used.
Why not! Noting it down in the to-do list.
Thanks for the suggestion (I'm closing now, but will reply in this thread when done).
