### ISSUE TITLE
spatial HAC errors

### ISSUE THREAD

**Issue by osamasajid1** [lrberge/fixest#350]
Hello,

I was wondering if you are planning to include spatial HAC st. errors for panel data estimation? The package currently has 'Conley' errors but they can only be used in the case of cross sectional data, not panel data.

**Comment by lrberge** [comment]
Hi, spatial HAC is planned and will be there in version 1.0.0. Hopefully in the first half of 2023.

**Comment by jcvdav** [comment]
Hi - are there any updates on this? I know @kylebutts and @lrberge (and others) have done a ton of work on this and, at the risk of not understanding this repo's structure, I can see the `dev` branch has some work towards implementing something like `vocov_conley_hac()` [here](https://github.com/lrberge/fixest/blob/dev/R/VCOV.R#L1708), but not quite exported yet.

I am happy to contribute, mostly to the R-side of the code, but I have some limited experience with Rcpp-side of things too.

**Comment by kylebutts** [comment]
Hi @jcvdav, two short-term fixest:

1. You can use this: https://gist.github.com/kylebutts/c289044c3233f9f0c3edfd14bee164e4

2. You can calculate it from fixest using: `vcov_conley_hac = vcov_conley + vcov_hac - vcov_robust` (calling each vcov seperately and then adding/subtracting them). You can store this back into the fixest object for use by doing `est = summary(est, vcov = vcov_conley_hac)`.

**Comment by jcvdav** [comment]
Thanks @kylebutts - I tried using opt 1 yesterday, but was having some never-ending compiler issues. But option 2 does the trick. Thamks!
