### ISSUE TITLE
Adding empty row between coefficients 

### ISSUE THREAD

**Issue by jyf29** [lrberge/fixest#355]
Hi, thank you for creating this great package! I'm having trouble figuring out how to include an empty row between the SE and the coefficient. Specifically, I'd like one row to be the estimate, next row is the SE, a blank row, and then the next estimate, etc. I've attached an example of the type of formatting I'm looking for. Is there a way to do that with etable? Thanks. 

 <img width="511" alt="Screen Shot 2022-09-13 at 9 09 24 PM" src="https://user-images.githubusercontent.com/4098017/190036253-d1707a1c-9afa-460d-bf0e-fda0bf18e193.png">

**Comment by lrberge** [comment]
Hi, thanks for the words! :-)

Currently, this is not possible. 

And to be honest, I'm not sure it will ever be... I need to find a design to allow adding blank lines without adding to the argument clutter of `etable` (there are too many arguments in `etable`). Further, the fact that there's no blank line after the constant means that there needs to be conditional execution which complicates the user-level design... 

I've noted the request, it may be there some day, but that's low priority sorry.
