### ISSUE TITLE
fitstat ivwald: "missing value where TRUE/FALSE needed"

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#358]
I'm getting the following error message when trying to get ivwald fitstat for a regression:

```
Error in if (any(diag(vcov) < 1e-10)) { :
missing value where TRUE/FALSE needed
```

Guessing its a bug with the ivwald code. Getting IV F-stats yields:

```
Browse[1]> fitstat(fit[[1]], type ="ivf")    
F-test (1st stage), enrolled                              : stat =    2,439.4, p < 2.2e-16, on 3 and 841,730 DoF.
F-test (1st stage), predicted_earnings_t10_t20_pt         : stat = NaNe+Inf  , p < 2.2e-16, on 3 and 841,730 DoF.
F-test (1st stage), enrolled:predicted_earnings_t10_t20_pt: stat =    3,865.2, p < 2.2e-16, on 3 and 841,730 DoF.
```

So I would guess its related to the F stat for `predicted_earnings_t10_t20_pt` being undefined.

**Comment by adamaltmejd** [comment]
Hello Laurent, sorry to bother you about this but I'm still running in to this error. Tell me if I can help somehow to get it fixed?

**Comment by lrberge** [comment]
Hi Adam, sorry for the long delay. I can't really help without a reproducible example. Does this still occur with the current version?

**Comment by adamaltmejd** [comment]
Hehe I don't even know how to reproduce it anymore :). I'll close this. Thanks!

**Comment by lrberge** [comment]
Actually I think this bug was fixed recently :-)
