### ISSUE TITLE
Unable to successfully save plots produced by coefplot() or iplot()

### ISSUE THREAD

**Issue by vicenteg8a** [lrberge/fixest#360]
Does anyone know how to save plots produced by `coefplot()` or `iplot()`? My understanding was that these functions were ggplot2 wrappers, so, in theory, I could save them with `ggsave()`. Whenever I try this, the plots are apparently saved but nowhere to be found. Has anyone experienced this before? Here is a reproducible example: 

`library(fixest)
library(ggplot2)
data("cars")
cars
reg <- 
  feols(speed ~ dist, 
        data = cars)
coefplot(reg)

ggsave(filename = "cars.png")`

**Comment by s3alfisc** [comment]
Hi @vicenteg8a, `coeftplot()` and `iplot()` aren't wrappers around `ggplot2` - you were probably thinking of the [ggiplot package](https://github.com/grantmcdermott/ggiplot), which ports both functions to `ggplot2`. Plots created by `fixest::coefplot` can be saved by base methods, e.g. the `png()` function as
```
png(filename = "example plot.png")
coefplot(reg)
dev.off()
```

**Comment by vicenteg8a** [comment]
Awesome. Thanks for your response, Alexander. It was very helpful.

**Comment by grantmcdermott** [comment]
Just to add that unfortunately I haven't ported `coefplot` over to ggiplot yet (although it might work in certain situations). OTOH you can use something like `modelsummary::modelplot()` to get nice coefficient ggplot objects.

@vicenteg8a If you feel your original question has been answered, do you mind closing this issue?

**Comment by vicenteg8a** [comment]
Sure! Thanks for the recommendation, @grantmcdermott.
