### ISSUE TITLE
OLS vs `feols()`

### ISSUE THREAD

**Issue by statzhero** [lrberge/fixest#363]
You write in the [documentation](https://lrberge.github.io/fixest/reference/feols.html) that the problem is equivalent for OLS and maximum likelihood based on the assumption of normal errors. I assume that `feols()` uses an ML estimator. Of course, asymptotically OLS and MLE should also coincide, but I was wondering if there is a subtle difference in a small or empirically finite sample? Please let me know if this question makes no sense for the `fixest` context.

**Comment by s3alfisc** [comment]
Hi @statzhero - I did not find the section in the documentation that you were referring to. I would guess that what it tries to say is that the ML estimator of a normal regression model is identical to the least squares solution? As far as I know, `feols()` does not use a ML estimator but a method called '[alternating projections](http://scorreia.com/research/hdfe.pdf)' to sweep out the fixed effects before estimating OLS on the 'demeaned' X and Y. For ML estimation, it uses a method called 'concentration likelihood', which @lrberge describes [in this paper](https://ideas.repec.org/p/luc/wpaper/18-13.html).

**Comment by statzhero** [comment]
I was referring to this: 

> The method used to demean each variable along the fixed-effects is based on Berge (2018), since this is the same problem to solve as for the Gaussian case in a ML setup.

**Comment by lrberge** [comment]
Hi, actually there is a misunderstanding: feols is pure OLS. 

It is feols's *demeaning algorithm* which is equivalent to the step to obtain the fixed-effects in a Gaussian ML estimation as described in section 2.2 of Berge (2018). There it's a perfect equivalence.
