### ISSUE TITLE
compatibility with stargazer / texreg

### ISSUE THREAD

**Issue by alanpaulkwan** [lrberge/fixest#37]
Here is some texreg code (written by my PhD student). Not sure 100% compatible going forward, but works for me.

```R
 

extract.feols <- function(model, include.nobs = TRUE, include.rsquared = TRUE,
                            include.adjrs = TRUE, include.fstatistic = FALSE, ...) {
    
    s <- summary(model, ...)
    nam <- rownames(s$coeftable)
    co <- s$coeftable[, 1]
    se <- s$coeftable[, 2]
    pval <- s$coeftable[, 4]
    
    gof <- numeric()
    gof.names <- character()
    gof.decimal <- logical()
    
    if (include.nobs == TRUE) {
      gof <- c(gof, s$nobs)
      gof.names <- c(gof.names, "Num.\ obs.")
      gof.decimal <- c(gof.decimal, FALSE)
    }
    if (include.rsquared == TRUE) {
      gof <- c(gof, fixest::r2(s, "r2"), fixest::r2(s, "wr2"))
      gof.names <- c(gof.names, "R$^2$ (full model)", "R$^2$ (proj model)")
      gof.decimal <- c(gof.decimal, TRUE, TRUE)
    }
    if (include.adjrs == TRUE) {
      gof <- c(gof, fixest::r2(s, "ar2"), fixest::r2(s, "war2"))
      gof.names <- c(gof.names, "Adj.\ R$^2$ (full model)",
                     "Adj.\ R$^2$ (proj model)")
      gof.decimal <- c(gof.decimal, TRUE, TRUE)
    }
    
    #     TODO: fixest does not have builtin F-stat. Will have to calculate ourselves
    #     
    #     if (include.fstatistic == TRUE) {
    #         gof <- c(gof, s$F.fstat[1], s$F.fstat[4],
    #             s$P.fstat[length(s$P.fstat) - 1], s$P.fstat[1])
    #         gof.names <- c(gof.names, "F statistic (full model)",
    #             "F (full model): p-value", "F statistic (proj model)",
    #             "F (proj model): p-value")
    #         gof.decimal <- c(gof.decimal, TRUE, TRUE, TRUE, TRUE)
    #     }
    
    tr <- texreg::createTexreg(
      coef.names = nam,
      coef = co,
      se = se,
      pvalues = pval,
      gof.names = gof.names,
      gof = gof,
      gof.decimal = gof.decimal
    )
    return(tr)
  }

``

**Comment by lrberge** [comment]
Thanks for the code. Not sure I would include it in the package though, but I can set a link to this code. 

Maybe your PhD student could set a Github account (if s/he hasn't have one) and include that code in it. Then I can make a link from the help pages to this code. The user would just have to copy paste  `source("link  to the code")` to get it running.

**Comment by lrberge** [comment]
And by the way, in the next version I'll include the f-stat!

**Comment by poliquin** [comment]
I also wrote similar code recently. This should be included in [`texreg`](https://github.com/leifeld/texreg) with the other `extract` functions.

By the way, `texreg` uses the class name to determine which `extract` method to use for creating tables. I notice `fixest` gives all objects the same class (e.g. both `feols` and `fepois` return an object of class `fixest`). One possibility is to update `fixest` to make the class name of these objects match the method call so that other packages can have separate methods like `extract.feols` and `extract.fepois`. In the meantime, I am registering the method like this...

```r
extract.feols <- function(...) {
    # see above
}

extract.fixest <- function(model, ...) {
    if (model$method == 'feols') {
        tr <- extract.feols(model, ...)
    } else if (model$method == 'fepois') {
        # TODO: write extract method for poisson models
        tr <- NULL
    }
    else {
        # not implemented, TODO: use texreg default (broom)
        tr <- NULL
    }
    return(tr)
}

# register method for fixest
setMethod("extract", signature = className("fixest", "fixest"), definition = extract.fixest)
```

I would be happy to submit a pull request to [`texreg`](https://github.com/leifeld/texreg) with `extract` methods for `fixest`, although I can't promise it will get done quickly.

**Comment by lrberge** [comment]
Thanks for the effort @poliquin! it could be great if it could get into **texreg**. Don't hesitate to ask me if you want specific stuff out of the models.
 
On the classes: Indeed, the class is only **fixest**. I must say that I'm not really in for adding new classes to each model though. It's not really handy for me (in my current code), and I don't see a clear advantage of doing it. But it up to discussion!

**Comment by lrberge** [comment]
I'm closing the issue. Feel free to create a new one if needed.

**Comment by MatthieuStigler** [comment]
Thanks @poliquin for the code! It seems your pull request is waiting there?

Also, note that the `extract.felm` method contains also an argument `include.groups`, showing the number of groups for each FE. Here would be the corresponding code to add that for extract.feols:


```
  if (include.groups == TRUE && length(s$fixef_sizes) > 0) {
    grp <- s$fixef_sizes
    grp.names <- paste0("Num. groups: ", names(grp))
    gof <- c(gof, grp)
    gof.names <- c(gof.names, grp.names)
    gof.decimal <- c(gof.decimal, rep(FALSE, length(grp)))
  }
```

**Comment by leifeld** [comment]
Added to the `texreg` master now: https://github.com/leifeld/texreg/commit/16e133c31f72d06770f36a0a63d0d4f96a2123c0
