### ISSUE TITLE
Wald test for equality of coefficients 

### ISSUE THREAD

**Issue by sonalichowdhry** [lrberge/fixest#387]
Is there a way to run Wald tests on the equality of estimated coefficients?

**Comment by kennchua** [comment]
As far as I know `fixest::wald()` only conducts tests of (joint) coefficient nullity.

For other linear (and non-linear) hypothesis tests, I highly recommend the `marginaleffects` package which is compatible with `fixest`.

```
library(fixest)
library(marginaleffects)

reg <- feols(mpg ~ wt + am, data = mtcars)

marginaleffects::hypotheses(reg, "wt = am") # test coef_wt = coef_am

```

**Comment by sonalichowdhry** [comment]
Excellent suggestion! Thanks @kennchua.
