### ISSUE TITLE
Does 2SLS Endogenous Interactions Use Fitted Values?

### ISSUE THREAD

**Issue by Garcese** [lrberge/fixest#420]
Hi! I'll try to keep this short. I have the following regression that I've simplified for the example:

`feols(y ~ x1 + i(x1, x2, "reference") | x2 ~ instrument, data = myData)`

Basically, I am running a 2SLS, where I am using "instrument" as an instrument for one of my variables, x2, but I also want to interact the fitted values for x2 against another variable, x1. When I run this code, the output calls x2 "fit_x2" like normal, but it only says "x2" for the interaction terms. I'm unsure if the function is actually using the fitted values for x2 from the 1st stage for the interaction terms, and I wish to have this clarified.

Econometrically, I'm 90% sure it is OK to have interactions with an instrumented variable, so I believe I am seeking out sane results. But, if I am mistaken, and it simply does not make sense, please excuse me, and just politely let me know! 

Thanks!

**Comment by kylebutts** [comment]
I understand where the logic is coming from, but all instruments are used for each endogenous variable. So for example, you predict x2 using all 4 instruments. That's just the mechanics of IV.

BTW, you don't need to include x2 if you don't include a reference value in x1.

**Comment by Garcese** [comment]
@kylebutts Ahh, I see, thank you for the reply. For some reason, I was having a difficult time understanding that. I sort of suspected the function was doing the right thing all along, and I was making a mistake!

Many thanks for your help. I'm a huge fan of the fixest package, it makes working with regressions such a breeze!
