### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by tmieno2** [lrberge/fixest#431]
Hi authors,

I am citing this package for my article, and when I run `citation("fixes)`. This is what I get.

```
  @Article{,
    title = {Efficient estimation of maximum likelihood models with
      multiple fixed-effects: the {R} package {FENmlm}},
    author = {Laurent Berg\'e},
    year = {2018},
    journal = {CREA Discussion Papers},
    number = {13},
  }
```

I am not sure if this is really the desired citation information any more. If this is okay, I will just use this. But, if not, please update it.

**Comment by lrberge** [comment]
Hi, as weird as it seems, this is the correct cite. Thanks for enquiring.
There will be a proper paper at some point but I don't know when! :-)
