### ISSUE TITLE
2SLS regression fit stats

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#445]
Is there a plan to provide p-value for cd (The Cragg-Donald test) and kpr (The Kleibergen-Paap test)? Also, the Sargan test results do not show, could you please check this issue?

**Comment by lrberge** [comment]
Please provide replicable examples.

Hi KPR is broken and I don't know how to fix.

Here's CD:
```R
base = setNames(iris = c("y", "x1", "x_endo_1", "x_inst_1", "fe"))
set.seed(2)
base$x_inst_2 = 0.2 * base$y + 0.2 * base$x_endo_1 + rnorm(150, sd = 0.5)
base$x_endo_2 = 0.2 * base$y - 0.2 * base$x_inst_1 + rnorm(150, sd = 0.5)

est_iv = feols(y ~ x1 | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, base)

fitstat(est_iv, "cd.p")
```

For [Sargan](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html#instrumental-variables):
> Note that the Sargan statistic appears only when relevant (i.e. when # instr. > # endo. vars., not the case here).

```R
est_iv = feols(y ~ x1 | x_endo_1 ~ x_inst_1 + x_inst_2, base)
fitstat(est_iv, "sargan")
#> Sargan: stat = 6.4626, p = 0.011017, on 1 DoF.
```
