### ISSUE TITLE
Error with coefplot

### ISSUE THREAD

**Issue by phisherblack** [lrberge/fixest#45]
Hi,
I am trying to plot a model with coefplot and I get this error:

Error in coefplot_prms(object = object, ..., sd = sd, ci_low = ci_low,  : 
  Internal error regarding the lengths of vectors of coefficients. Could you report to the author of the fixest package?

Do you have any idea what is going on?

**Comment by lrberge** [comment]
Hi, I have a small idea, but I need confirmation. Could you send me data/code that leads to this error?

**Comment by phisherblack** [comment]
Thanks,
here is the code i am trying to run that is throwing the error.

mod1.full<-feols(log.gdp ~ success::year(1981)+log.gdppc+log.pop+bmr_dem+ armed_conflict| ccode + year, data = kcoup)

coefplot(mod1.full).

is this a bug with the software?

**Comment by lrberge** [comment]
Aren't there coefficients that are removed from the estimation because of collinearity?

Could you make me a link to (or dm me) the data, so that I can run it on my computer and replicate the problem?

**Comment by phisherblack** [comment]
Thank you.
I have DM'ed you with the dataset.

**Comment by lrberge** [comment]
Thanks, that was a bug when interacted coefficients were removed from the estimation due to NAness. Now fixed.

The dev version should work.

**Comment by phisherblack** [comment]
Awesome! thank you some much! i'll get the Dev version.
