### ISSUE TITLE
Missing plot in a vignette

### ISSUE THREAD

**Issue by etiennebacher** [lrberge/fixest#464]
Hi, in the [staggered DiD section](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html?q=sunab#staggered-difference-in-differences-sun-and-abraham-2020), a plot is supposed to be displayed but instead there's this message:

![image](https://github.com/lrberge/fixest/assets/52219252/5e7bc0f2-f946-4f10-ae06-3fa7cec43117)

**Comment by lrberge** [comment]
Fixed, thanks!
