### ISSUE TITLE
[Documentation] Warning instead of code

### ISSUE THREAD

**Issue by raffaem** [lrberge/fixest#467]
Hello,

thanks very much  for this package.

In reading the documentation, I noticed that [in this example](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html#423_Staggered_difference-in-differences_(Sun_and_Abraham,_2020)) it says:

> Warning: package 'ggplot2' was built under R version 4.2.3

instead of the code needed to plot the below plot.

**Comment by lrberge** [comment]
Thanks! I'll remove the ugly warning in the next release. 
BTW the code to generate the plot is not intended to be displayed in the document, but you can find it here:
https://github.com/lrberge/fixest/blob/206661df3b709d1eddd8eaac6b6c1f8496a29934/vignettes/fixest_walkthrough.Rmd#L629
