### ISSUE TITLE
est_slopes model missing from exporting vignette

### ISSUE THREAD

**Issue by Zedseayou** [lrberge/fixest#47]
I'm not sure if I'm being very dense since I don't know how the document would have successfully knit without it, but I don't see the definition of the `est_slopes` model in the exporting table vignette. As written it doesn't run for me since it can't find `est_slopes`. I assume it was there at some point and is now missing, since the table displays 5 models and only 4 are estimated. However, I didn't see it show up in the commit history.

https://github.com/lrberge/fixest/blob/40c1fe5e4a57220e722d3b43d525494ba6405a18/vignettes/exporting_tables.Rmd#L36-L50

**Comment by lrberge** [comment]
Corrected. Thanks again!
