### ISSUE TITLE
data scope issue when using cluster in summary()

### ISSUE THREAD

**Issue by chenwang** [lrberge/fixest#52]
Hi there,

Thanks for the excellent `fixest`! I really enjoy it and try to use it in my production work. However, I've noticed there's a scope issue when I use clustered standard errors. Here's an MWE that replicates the problem I encountered. 

```r
library(fixest)
data(trade)
mdl <- feols(Euros~dist_km, trade)
summary(mdl, cluster='Year')
test <- function(.data){
  mdl <- feols(Euros~dist_km, .data)
}
mdl2 <- test(trade)
summary(mdl2, cluster='Year')
```
`summary(mdl2, cluster='Year')` gives the following error:
```
Error in vcov.fixest(object, se = se, cluster = cluster, dof = dof, forceCovariance = forceCovariance,  : 
  Cannot apply 1-way clustering with current 'cluster' argument. Variable Year was not used as fixed-effects in the estimation. We tried to fetch this variable in the original database in the parent.frame -- but the data doesn't seem to be there anymore (btw it was .data). Alternatively, use a list of vectors. [note: 1-way clustering deduced by cluster length.]
```
When comparing `mdl$fml` and `mdl2$fml`, I notice `mdl2$fml` contains an environment, which suggests it might be a scope problem.
```
# mdl2$fml
Euros ~ dist_km
<environment: 0x7ffd559cb5f0>
```
Here's my `sessionInfo()`:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fixest_0.7.0

loaded via a namespace (and not attached):
 [1] zoo_1.8-8           compiler_3.6.3      sandwich_3.0-0      tools_3.6.3         dreamerr_1.2.1     
 [6] Rcpp_1.0.5          nlme_3.1-150        grid_3.6.3          Formula_1.2-4       numDeriv_2016.8-1.1
[11] lattice_0.20-41    
```

**Comment by lrberge** [comment]
Hi, and thanks for using it!

I'm afraid it is not an issue but rather a perfectly valid behavior. 

### Why it _shouldn't_ work (at least directly)

As a package developer, my biggest fear is that my functions return **wrong** results without error nor warning.
Had I implemented a way to do what you suggest, then many wrong results would go unnoticed.

If `feols` & co are to be used inside functions, then it is the responsibility of the person writing that function to ensure consistency. In particular, if you wish to cluster the SEs _ex post_, the data used for the estimation should be identical to the original data.

It's actually very easy to fix the function to behave as you want, we just have to change the _call_. 

Here's an example of the situation I fear the most, as well as a valid behavior:
```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

est = feols(y ~ x1 + x2, base)

ok_fun = function(fml, .data){
    # We don't touch .data
    res = feols(fml, .data)
    # we reframe the call
    res$call$data = match.call()$.data
    res
}

problematic_fun = function(fml, .data){
    # Do stuff with .data
    # eg: reordering
    .data = .data[order(.data[[1]]), ]
    res = feols(fml, .data)
    res$call$data = match.call()$.data
    res
}

# estimations
est_ok = ok_fun(y ~ x1 + x2, base)
est_pblm = problematic_fun(y ~ x1 + x2, base)

# note the different SEs in est_pblm without error message
etable(est, est_ok, est_pblm, cluster = "species")
#>                                       est               est_ok           est_pblm
#> (Intercept)              2.249** (0.1626)     2.249** (0.1626)   2.249** (0.2097)
#> x1                     0.5955** (0.05173)   0.5955** (0.05173) 0.5955** (0.05419)
#> x2                   0.4719*** (0.006873) 0.4719*** (0.006873)  0.4719* (0.04841)
#> ___________________  ____________________ ____________________ __________________
#> S.E. type: Clustered          by: species          by: species        by: species
#> Observations                          150                  150                150
#> R2                                0.84018              0.84018            0.84018
#> Adjusted R2                         0.838                0.838              0.838
```

As you can notice, in the function `problematic_fun` the data is modified before the estimation. The clustering still works _ex post_, but the results are wrong. This is not the case for the function `ok_fun`.

From my viewpoint, if I implement an automatic way to find the right call (e.g. by possibly saving the call stack and climbing up the ladder to find the right data), then I would be responsible for possible wrong results which are beyond my control. I hope you understand that I don't want to take that route! :-)

#### Workaround

So far, my comments apply a bit as if you wanted to develop a package that uses my functions. 
But maybe you just want to automatise some processing inside loops for example. Like in:
```R
res = list()
for(i in 1:10){
    est = fun(i, data, etc)
    res[[i]] = summary(est, cluster = stuff)
}
```
If so, I would suggest to do the clustering inside the function directly, and not ex post. I'm actually not sure it is even possible to implement an ex post clustering in that kind of situation (or it would require to keep an imprint of all the data sets used in the estimations which is not recommended).

If you use `summary` inside the function, it will work:
```R
fine_fun = function(fml, .data, ...) summary(feols(fml, .data), ...)

est_fine = fine_fun(y ~ x1 + x2, base, cluster = "species")
etable(summary(est, cluster = "species"), est_fine)
#>                      summary(est, clust..             est_fine
#> (Intercept)              2.249** (0.1626)     2.249** (0.1626)
#> x1                     0.5955** (0.05173)   0.5955** (0.05173)
#> x2                   0.4719*** (0.006873) 0.4719*** (0.006873)
#> ___________________  ____________________ ____________________
#> S.E. type: Clustered          by: species          by: species
#> Observations                          150                  150
#> R2                                0.84018              0.84018
#> Adjusted R2                         0.838                0.838
```

**Important note:** there was a bug in the code leading to `summary` not working inside the function `fine_fun`. I've corrected it but it's not yet on GH.

I hope it answers your question!

**Comment by chenwang** [comment]
thanks for pointing out the potential caveats; this is very helpful!

I think the solution you suggested solves my problem.

**Comment by lrberge** [comment]
Indeed, now it's corrected in the dev version. As you can see in the commit, the fix was just about adding "..." that I forgot.

Thanks again, I'm closing then!
