### ISSUE TITLE
Supporting interactions in second stage of 2SLS IV

### ISSUE THREAD

**Issue by a-reck** [lrberge/fixest#521]
Hi! First of all I really love the package and all its functionalities, thank you for that.

In our current project, we are trying to experiment with interactions in only the second stage of a Two-Stage Least-Squares (2SLS) regression. As far as I can see, there is no direct implementation of this in the feols function. Here an example with a random interaction variable and the workaround I am currently using:

```
library(fixest)

# Loading data
base = iris
names(base) = c("y", "x1", "x_endo", "x_inst", "fe")
set.seed(2)
base$interact = rnorm(150, sd = 0.5)

# Simple model (no interactions) with IV and fixed effects
est_iv_fe = feols(y ~ x1 | fe | x_endo ~ x_inst, base)

# This is NOT what we want, because this will use the interacted term as the dependent variable in the first stage
est_iv_interact = feols(y ~ x1 | fe | x_endo:interact ~ x_inst, base) 

# Workaround
stage_1 = feols(x_endo ~ x_inst + x1 | fe, base)
resid_1st_stage <- residuals(stage_1)
base_predicted <- subset(base, select = -x_endo)
base_predicted["x_endo"] <- predict(stage_1, base, vcov=~fe)
stage_2_wrong_SE = feols(y ~ x_endo + x1 | fe, base_predicted)
env <- feols(y ~ x_endo + x1 | fe, base_predicted, only.env=TRUE)
stage_2_adjusted_SE = feols(env=env, resid_1st_stage = list(resid_1st_stage), iv_call=TRUE)
env_interact = feols(y ~ x_endo:interact + x1 | fe, base_predicted, only.env=TRUE)
stage_2_interact = feols(env=env_interact, resid_1st_stage = list(resid_1st_stage), iv_call=TRUE)

etable(est_iv_fe, stage_2_wrong_SE, stage_2_adjusted_SE, stage_2_interact)
```
I believe that ```stage_2_interact``` gives the result we want, but it would be great if this could be achieved directly somehow.

**Comment by kylebutts** [comment]
What you're describing is not a two-stage least squares regression. Instead, it is a non-standard two-step estimation procedure whose properties are unknown. 

I think the standard procedure is to do something like this:
```
est_iv_interact = feols(y ~ x1 | fe | x_endo + x_endo:interact ~ x_inst + x_inst:interact, base) 
```

**Comment by a-reck** [comment]
Hi kylebutts, thank you very much for your reply. 
I think the standard procedure is not applicable in our case, because ```interact``` does not fulfill the IV validity assumption. We were instead looking for a way to investigate the heterogeneity of the effect in the second stage. But considering what you said in your answer, maybe splitting the dataset is a better approach. Thanks again!
