### ISSUE TITLE
bug in check_conv

### ISSUE THREAD

**Issue by kendonB** [lrberge/fixest#53]
I have encountered an error at line 609 below. I haven't been able to work out how to get a reprex to end up here.

https://github.com/lrberge/fixest/blob/422546949cb49791188e69b41c4712da0f8ac04a/R/ESTIMATION_FUNS.R#L602-L620

In my example, slope_vars is a _named list_ of vectors for which I am asking for varying slopes. In this code, I believe it is treated as if it is a concatenated vector. Changing line 607 to `var = unlist(unname(slope_vars))[index_var]` seems to run, but I'm not sure if that's what the code is trying to do.

**Comment by lrberge** [comment]
Hi, thanks for the report. 

Indeed, I have completely changed the internal demeaning algorithm when it comes to variables with varying slopes... but I forgot to update `check_conv` and it passed through my tests. I'll fix that, thanks!
