### ISSUE TITLE
Bug with predict.fixest when a data frame is included 

### ISSUE THREAD

**Issue by jurojas5** [lrberge/fixest#54]
I’m facing a bug when trying to predict the values of a _feglm_ model in the version 0.7 of _fixest_. When a data frame is included in the _newdata_ argument of the _predict_ function, incorrect predicted values are returned. This happens even if the original data frame used to estimate the _feglm_ model used in the _newdata_ argument.

I include an example of this bug, using the _Trade_ data from the _fixest_ package to estimate a simple gravity model with fixed effects. When the _predict_ function includes the original data frame, the predictions are different from the fitted values stored in the _feglm_ regression. However, the _predict_ function returns the same fitted values when no data frame is included in it.

```
library(fixest)

#Poisson GLM model
fit_glm <- feglm(fml = Euros ~ log(dist_km) | Origin + Destination + Product,
                 data = trade)

#Fitted values
fitt_val <- fit_glm$fitted.values

#Predictions with the original data
pred_with_data <- predict(fit_glm, newdata = trade)

#Predictions without data
pred_no_data <- predict(fit_glm)

#Values
head(cbind(fitt_val, pred_with_data, pred_no_data))

#         fitt_val   pred_with_data    pred_no_data
#[1,]     10618851     1004280494         10618851
#[2,]     5633453       374743169           5633453
#[3,]     43673276     4130410976         43673276
#[4,]     23169301     1541246003         23169301
#[5,]     20462308     1935227842         20462308
#[6,]     10855548     722122373           10855548

#Plot: fitt_val vs pred_with_data
plot(fitt_val, pred_with_data)

#Plot: fitt_val vs pred_no_data
plot(fitt_val, pred_no_data)

```

**Comment by lrberge** [comment]
Thanks a lot for the clear report!

It's a bug that I introduced in the last version when I decided to reorder the fixed-effects in the function `fixef`.

Now I added tests related to the `predict` function, so hopefully such bugs won't be re-introduced.
