### ISSUE TITLE
Specifying interactions for clusters

### ISSUE THREAD

**Issue by edrubin** [lrberge/fixest#55]
First off, thank you for a fantastic package.

I'm running into an unanticipated error when I attempt to specify interactions for the level of clustering using the "formula" method for the `cluster =` argument in `summary`.

The scenario that I have in mind is that I might want to define the level of clustering as the interaction between two existing variables (for example, a group interacted with a unit of time).

**Working example:**

```r
# Load 'fixest'
library(data.table)
library(fixest)
library(magrittr)
# Create data
set.seed(123)
tmp = data.table(
  x = rnorm(20),
  i = rep(1:5, each = 4),
  g = rep(1:5, each = 4),
  t = rep(1:4, 5)
)
tmp[, y := x + i + g + t + rnorm(20)]

# Create an interaction between group (g) and time (t)
tmp[, gt := interaction(g,t)]

# Works:
feols(y ~ x | i + t, data = tmp) %>% summary(cluster = "gt")

# Does not work:
feols(y ~ x | i + t, data = tmp) %>% summary(cluster = ~g:t)
# Does not work:
feols(y ~ x | i + t, data = tmp) %>% summary(cluster = ~interaction(g,t))
# Does not work:
feols(y ~ x | i + t, data = tmp) %>% summary(cluster = ~i(g,t))
```

The specification that "works" is just one-way clustering on a created variable that exists in the dataset.

I thought it would be convenient to avoid creating the variable and just use the formula notation as the value of `cluster`, but it throws the error:
```
Error in parse(text = value_text) : object 'value_text' not found
```

Is this error intended? It would be great to be able to create the interaction within the `summary` call, but I understand if that is not the goal of the project.

Thanks!

**Comment by lrberge** [comment]
Hi! I like the questions for which I don't have extra work to do ;-)

Actually it is covered but you have to use the internal syntax for interactions, i.e. `^`:
```R
a = feols(y ~ x | i + t, data = tmp) %>% summary(cluster = "gt")
b = feols(y ~ x | i + t, data = tmp) %>% summary(cluster = "g^t")
c = feols(y ~ x | i + t, data = tmp) %>% summary(cluster = ~g^t)
etable(a, b, c)
#>                                     a                b                c
#> x                    0.814** (0.2366) 0.814** (0.2366) 0.814** (0.2366)
#> Fixed-Effects:       ---------------- ---------------- ----------------
#> i                                Yes              Yes               Yes
#> t                                Yes              Yes               Yes
#> ___________________  ________________ ________________ ________________
#> S.E. type: Clustered           by: gt          by: g^t          by: g^t
#> Observations                       20               20               20
#> R2                            0.97338          0.97338          0.97338
#> Within R2                     0.59331          0.59331          0.59331
```
It surely isn't clear enough so I'll amend the help to describe it better.

By the way 1: thanks for reporting the ugly error messages. As a package developer, my duty is to catch any possible user-level error and clearly state what the problem is. You've caught an internal bug: so thanks a lot, I'll fix it!

By the way 2: in the next version I'll include `cluster` in the estimation calls to avoid using `summary` ex post.

By the way 3: the internal way to do interactions, with `^`, is much faster than `interaction()`. The function `to_integer` is the user-level function:
```R
a = sample(2e3, 1e5, TRUE)
b = sample(2e3, 1e5, TRUE)
system.time(m1 <- to_integer(a, b))
#>   user  system elapsed 
#>      0       0       0 
system.time(m2 <- interaction(a, b))
#>   user  system elapsed 
#>   3.78    0.08    3.86 
length(unique(m1))
#> [1] 98720
length(unique(m2))
#> [1] 98720
```

**Comment by edrubin** [comment]
Thank you, @lrberge! The operator `^` and `to_integer()` are both awesome additions. 

I see `^` in the discussion of fixed effects, but I agree that adding it to the standard-error section would help.

Thanks again for your work and this fantastic package.
