### ISSUE TITLE
IV

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#57]
Hi! Would love to use fixest, it seems really awesome, but need to run instrumental variables models. Is that anything you are working on? Any way one could help?

**Comment by lrberge** [comment]
Well, I'm actually finishing the design of the code. 
I'm planning to have a (CRAN) version with IVs by mid/end December. The dev IVs will likely be ready by the end of November.

**Comment by adamaltmejd** [comment]
Very cool! Will happily test.
