### ISSUE TITLE
Error when regressing on a constant with NA in fixed effects

### ISSUE THREAD

**Issue by zozotintin** [lrberge/fixest#58]
# Problem
`feols` produces `Error in if (useModel.matrix) { : argument is of length zero` when regressing on a constant with `NA` in fixed effects in GitHub version 6a174eb2eb1d374290a502852dd22d0d52609a37, but the same sets of fixed effects work fine in version `0.7.1`. I suspect that `feols` accidentally changes `useModel.matrix`  to `NULL` when removing observations with `NA` fixed effects.

# Environment
```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /home/poyu/anaconda3/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_HK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_HK.UTF-8        LC_COLLATE=en_HK.UTF-8    
 [5] LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_HK.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.13.2 fixest_0.8.0     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        lattice_0.20-41     arrow_2.0.0        
 [4] zoo_1.8-8           assertthat_0.2.1    grid_4.0.3         
 [7] R6_2.5.0            nlme_3.1-150        magrittr_1.5       
[10] rlang_0.4.8         dreamerr_1.2.1      vctrs_0.3.4        
[13] sandwich_3.0-0      Formula_1.2-4       tools_4.0.3        
[16] bit64_4.0.5         glue_1.4.2          purrr_0.3.4        
[19] bit_4.0.4           numDeriv_2016.8-1.1 compiler_4.0.3     
[22] tidyselect_1.1.0 
```
# Summary Statistics
```r
> str(panel)
Classes ‘data.table’ and 'data.frame':  768417260 obs. of  4 variables:
 $ fe_n: Factor w/ 24 levels "11","21","22",..: 7 7 7 7 7 7 7 7 7 7 ...
 $ fe_t: Factor w/ 61 levels "24185","24186",..: 54 54 54 54 54 54 54 54 54 54 ...
 $ fe_d: Factor w/ 98813 levels "0","1","2","3",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ dep : num  0 2 1 0 2 1 1 1 3 0 ...
 - attr(*, ".internal.selfref")=<externalptr> 
```
```r
> head(panel)
  fe_n  fe_t fe_d dep
1   33 24238    0   0
2   33 24238    0   2
3   33 24238    0   1
4   33 24238    0   0
5   33 24238    0   2
6   33 24238    0   1
```
```r
> panel[, length(unique(fe_n))]
[1] 25
> panel[, length(unique(fe_t))]
[1] 61
> panel[, length(unique(fe_d))]
[1] 98813
> panel[, summary(dep)]
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.5635  1.0000  4.0000 
```

# Code that Produces Errors
```r
> system.time(model <- feols(dep ~ 1 | fe_n^fe_t, data = panel))
NOTE: 15,133 observations removed because of NA values (LHS: 0, RHS: 0, Fixed-effects: 15,133).
Error in feols(dep ~ 1 | fe_n^fe_t, data = panel) : 
  Error in if (useModel.matrix) { : argument is of length zero
This error was unforeseen by the author of the function feols. If you think your call to the function is legitimate, could you report?
Timing stopped at: 188.7 131.5 302.9
```
However, the following sets of fixed effects work fine
```r
> system.time(model <- feols(dep ~ 1 | fe_d, data = panel))
   user  system elapsed 
 78.812  48.589 107.764 
> system.time(model <- feols(dep ~ 1 | fe_d^fe_t, data = panel))
   user  system elapsed 
115.377  63.386 162.622 
```

**Comment by zozotintin** [comment]
I found a way to reproduce this error in `iris`. The bug seems to happen when regressing on a constant with `NA` in fixed effects.
```r
> base = iris
> names(base) = c("y", "x1", "x2", "x3", "species")
> base[1, 'species'] = NA
> head(base)
    y  x1  x2  x3 species
1 5.1 3.5 1.4 0.2    <NA>
2 4.9 3.0 1.4 0.2  setosa
3 4.7 3.2 1.3 0.2  setosa
4 4.6 3.1 1.5 0.2  setosa
5 5.0 3.6 1.4 0.2  setosa
6 5.4 3.9 1.7 0.4  setosa
```
```r
> fixest::feols(y ~ 1 | species, data = base)
NOTE: 1 observation removed because of NA values (LHS: 0, RHS: 0, Fixed-effects: 1).
Error in fixest::feols(y ~ 1 | species, data = base) : 
  Error in if (useModel.matrix) { : argument is of length zero
This error was unforeseen by the author of the function feols. If you think your call to the function is legitimate, could you report?
```
```r
> fixest::feols(y ~ x1 | species, data = base)
NOTE: 1 observation removed because of NA values (LHS: 0, RHS: 0, Fixed-effects: 1).
OLS estimation, Dep. Var.: y
Observations: 149 
Fixed-effects: species: 3
Standard-errors: Clustered (species) 
   Estimate Std. Error t value Pr(>|t|)    
x1 0.803404   0.071558  11.227  0.00784 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-likelihood: -86.88   Adj. R2: 0.71872 
                       R2-Within: 0.28102 
```

**Comment by lrberge** [comment]
Hi, thanks again for the report!

#### The general problem

Hmm, I think I need to reorganize the way I'm doing things... I'm relatively new to git and am not familiar with users really using the development code. I'm a bit old style and apply all changes on Master, as I would have done without git. I tried branches but I found it to be a waste of time because of the handling of the merge conflicts -- especially that it's not uncommon that I make changes that trickle down to many functions.

In the current version I'm applying massive changes in the code: on top of new features, I'm cleaning, reorganizing, rationalizing. 
In particular, at some point, I would have gotten rid of the problematic `useModelMatrix` mechanism that led to the bug you describe.

#### Back to the bug

Coming back to the bug: I kindly ask for your patience. I cannot get rid of it right now because I have many major changes under way that need to be checked. Once they're checked, it should be OK (but again, I may have introduced new bugs).

#### Conclusion?

For sure I need to improve the way I'm handling the development version. 
Maybe I could work on a branch and only fix bugs separately in Master, before merging for release?  
My only issue with this way of doing is that it's double work if I have to fix the bug in both Master and the branch (especially that I tend to apply many changes in the branch, likely affecting the bug itself).... 

Do you have any suggestion?

**Comment by zozotintin** [comment]
Thank you for your active development. I totally understand that `0.8.0` is still in development stage, and I can totally feel the pain in managing multiple branches with `git`. I reported this bug just let you know its existence in case you are not aware of it. This bug is not that devastating as #56, and as a user I can easily bypass it by removing `NA` from fixed effects directly in the data. So please take your time to remove `useModel.matrix`.

I have limited software development experience. But In terms of managing both a growing master and a growing development branch, what I would do is that once there are new commits to the master branch besides my development branch (can be ad hoc fixes or other collaborators' work), I will try to `git rebase` my development branch to the `HEAD` of the master branch. Of course if the ad hoc fixes are not compatible with the development branch, then I might just delay the bug fix and work on the development branch first.

BTW, I found this interactive website https://learngitbranching.js.org especially useful for learning `git`.

**Comment by lrberge** [comment]
The link you've posted is amazing--the tutorial is really great: thanks!

It looks like a matter of habit in the end: I'll try harder branching!

**Comment by lrberge** [comment]
I've just pushed the changes, I think it should be working now.

**Comment by zozotintin** [comment]
Thank you for your hard work. I just installed snapshot f62014dd27b6b1a4175187ce694e2562c09a1b86. Unfortunately there are now new bugs.
```r
> base = iris
> names(base) = c("y", "x1", "x2", "x3", "species")
> base[1, 'species'] = NA
> head(base)
    y  x1  x2  x3 species
1 5.1 3.5 1.4 0.2    <NA>
2 4.9 3.0 1.4 0.2  setosa
3 4.7 3.2 1.3 0.2  setosa
4 4.6 3.1 1.5 0.2  setosa
5 5.0 3.6 1.4 0.2  setosa
6 5.4 3.9 1.7 0.4  setosa
```
```r
> fixest::feols(y ~ 1 | species, data = base)
NOTE: 1 observation removed because of NA values (Fixed-effects: 1).
Error in fixest::feols(y ~ 1 | species, data = base) : 
  Error in linear.mat[-obs2remove, , drop = FALSE] : 
  incorrect number of dimensions
This error was unforeseen by the author of the function feols. If you think your call to the function is legitimate, could you report?
```

The same error happens on both the small `iris` dataset as well as my big panel dataset.

**Comment by lrberge** [comment]
Thanks for quickly checking. Bottom line: I really need to revise my battery of tests! and I will!

It was easily fixed, but I can't push on GH since my repo is corrupted (!). So I need to fix that first, I'll let you know.

**Comment by lrberge** [comment]
Tests have been added, and now the dev version is stable! 

Following this bug, in the future I'll only work on branches, it's really the way to go.  Thanks for the link to git branching, it was really useful. 

So I'm closing the issue, thanks again for the report!

**Comment by lrberge** [comment]
Just to say that the new version is just out on CRAN.

I also wanted to thank you for the link on branching. I just realized that I wasn't using GIT at all and regret I didn't take a class on git before using it!

Now I'm branching all over the place, and it completely changes the way you work! Thanks again!

**Comment by zozotintin** [comment]
`fixest` really helped me a lot by having 4x speed in running regressions, so I am glad that the `git` tutorial link helped you. Thank you for your amazing work!
