### ISSUE TITLE
[bug] Combining fixed effect not working when using l() f() or d()

### ISSUE THREAD

**Issue by SuperMayo** [lrberge/fixest#59]
Hi, thanks again for this amazing library!

I recently identified a bug that is pretty much summed up in the title. I guess there is a parsing issue when you use both l/d/f and the interaction character `^`.

## Reproduction
```r
library("fixest")
data(base_did)
base_did$x2 <- as.numeric(rnorm(nrow(base_did)) >= 0)

# working:
feols(y ~ x1 | id^x2, data = base_did) # Works as expected

# not working:
feols(y - l(y) ~ x1 | id^x2, data = base_did, panel.id = c("id", "period"))
#>> Error in feols(y - l(y) ~ x1 | id^x2, data = base_did, panel.id = c("id",  : 
#>>  Problem in the formula regarding lag/leads: Error in terms.formula(formula(x_FML, lhs = 1, rhs = 2)):
#>> invalid power in formula
```

### misc
<details>
  <summary>sessionInfo</summary>

  ```
  R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] fixest_0.7.1

loaded via a namespace (and not attached):
 [1] zoo_1.8-8           compiler_4.0.3      sandwich_2.5-1      tools_4.0.3         dreamerr_1.2.1      Rcpp_1.0.5         
 [7] nlme_3.1-149        grid_4.0.3          Formula_1.2-3       numDeriv_2016.8-1.1 renv_0.12.0         lattice_0.20-41    
  ```
</details>

**Comment by lrberge** [comment]
Thanks a lot for the report! Indeed a parsing error it is! (I'm actually paying the price for implementing non-standard parsing...)

I've corrected it but it's not yet pushed because it's in the middle of massive changes that I need to check.

By the way, I didn't know that we could add drop down sections in the posts: ace! Thanks!

**Comment by lrberge** [comment]
I've pushed some changes, the dev version should be working now.

**Comment by lrberge** [comment]
Now the dev version is stable (I'll be adding only minor things) and I've added a test on this issue specifically: it should never happen again!

Thanks again for the report!
