### ISSUE TITLE
Display of factor values (fixed effects)

### ISSUE THREAD

**Issue by gbekes** [lrberge/fixest#65]
Hi

Thanks again, still amazed by the speed. I realized this could be great for a case when I'm actually interested in the values of a factor variable with many values. Like trade data and simple one-way country FE. 

I'm wondering about options to display fixed effects (factor values).  In particular, I would:

1. print a table of only fixed effect values (for single FE case)
2. country fixed effects treated as factor, ie having a country as base, and display factor values (=fixed effects) accordingly. Like when you use in lm stg like `+relevel(country, ref = "England")`
3. plot all coefficients with CI (ideally after rebase) not just low and high.

I looked thru documentation, could not figure them out, but most likely they are all easy.

Thanks!

**Comment by lrberge** [comment]
Hi!

Is it something like that?
```R
library(fixest)
data(trade)

res = feols(log(Euros) ~ log(dist_km) + i(Origin, ref = "FR") | Destination, trade)

etable(res, keep = "Origin")
#>                                res
#> Dependent Var.:         log(Euros)
#>                                   
#> Origin = AT     -3.146*** (0.1886)
#> Origin = BE     -1.124*** (0.1271)
#> Origin = DE       0.3701* (0.1721)
#> Origin = DK     -1.786*** (0.2623)
#> Origin = ES       -0.1101 (0.1752)
#> Origin = FI     -3.668*** (0.2845)
#> Origin = GB     -1.122*** (0.2703)
#> Origin = GR     -2.566*** (0.1766)
#> Origin = IE     -3.006*** (0.1336)
#> Origin = IT      -0.2806* (0.1191)
#> Origin = LU     -5.923*** (0.2513)
#> Origin = NL      -0.09276 (0.2523)
#> Origin = PT     -2.375*** (0.2285)
#> Origin = SE     -2.213*** (0.3046)
#> Fixed-Effects:  ------------------
#> Destination                    Yes
#> _______________ __________________
#> S.E.: Clustered    by: Destination
#> Observations                38,325
#> R2                         0.50428
#> Within R2                 0.444888

coefplot(res, horiz = TRUE, keep = "Origin")
```

![image](https://user-images.githubusercontent.com/43536394/101188955-b2377b80-3656-11eb-8b80-d1c58f5e7691.png)



The main issue is that when you are interested in the fixed-effects' standard-errors, you have to treat them like factor variables. That's what is done with the function `i()`.

Is it what you wanted to do?

**Comment by gbekes** [comment]
Yes. OMG. So simple. i() like stata. Respect. 

Did i miss it in documentation? It would be work pushing this, cause it's super.

**Comment by lrberge** [comment]
OK, great!

No that's not in the introduction, but I'll include a section on it! (it's also relatively recent)

Thanks!

**Comment by gbekes** [comment]
Sorry to reopen. Three minor questions (the last is kind of a comment)

Q1: do coefplot stuff like ,decreasing = TRUE, sort = "magnitude" work? (not for me)
I'd like to sort my fixed effects by coeff size (but could also do that by size of CI band)

Q2: Is there any way to increase image size such that all coeff labels are shown? Ie if you have 100 countries, coeffs for all will be on the graph, but not labels. Especially for markdown/html, length is not an issue. 

Q3 This is more of a comment. When I add i() to the model, all other factors are requested to be added like this

```
reg_m1<- feols(ln_count~binary + ln_value + feature, data=data1)
reg_m2<- feols(ln_count~binary + ln_value + feature+i(country, ref = "England") , data=data1)
reg_m3<- feols(ln_count~binary + ln_value + i(feature)+i(country, ref = "England") , data=data1)
```
So `reg_m1` is fine, and `reg_m3` works too. But m2 would say
```
Error in feols(ln_count~binary + ln_value+  : 
  Evaluation of the right-hand-side of the formula raises an error: Error in eval(predvars, data, env) : object 'y' not found
```

No biggie, just a heads up. 
 (sry can't share code is long, data is prop)

Thanks!

**Comment by lrberge** [comment]
The function `coefplot` is inadequate in many aspects, I've added it in the package but there are *many* things that I want to implement (like there's no automatic legends, split graphs, etc). At least it has the merit of existing! :-) 
The problem is that its development is kind of low priority for me so I won't change it before a while... (and I'm also taking a coding break following a quite unreasonable coding frenzy!)
That said:

Q1: Ordering by value doesn't exist yet, but I've added it in my `coefplot` to-do list, so it will be there at some point! Note that the increasing/decreasing is not so obvious when you display multiple estimations at the same time (should it be according to the coefs of the 1st estimation? Of the median/average coef across all estimations?).
By the way, maybe modelsummary works for what you want to do (I know you can plot coefs although I've never used it)?

Q2: If the problem is due to the figure height, I think it can be done directly in Rmd with `fig.height = x`. Or is it something else?

Q3: Actually I can't replicate the bug, so it may be specific to your setup (that's really weird)!
```R
library(fixest)
base = iris ; names(base) = c("y", "x1", "x2", "x3", "species")
base$fe = sample(letters[1:5], 150, TRUE)

feols(y ~ x1 + x2 + species + i(fe, ref = "a"), base)
#> OLS estimation, Dep. Var.: y
#> Observations: 150 
#> Standard-errors: Standard 
#>                    Estimate Std. Error   t value  Pr(>|t|)    
#> (Intercept)        2.390800   0.263165  9.084800   8.5e-16 ***
#> x1                 0.439127   0.084159  5.217800  6.34e-07 ***
#> x2                 0.771947   0.064970 11.882000 < 2.2e-16 ***
#> speciesversicolor -0.937483   0.218382 -4.292900   3.3e-05 ***
#> speciesvirginica  -1.355600   0.290684 -4.663400  7.15e-06 ***
#> fe::b             -0.142694   0.094113 -1.516200  0.131709    
#> fe::c             -0.038874   0.076366 -0.509046  0.611516    
#> fe::d              0.032620   0.077412  0.421377  0.674121    
#> fe::e             -0.041743   0.078708 -0.530356  0.596699    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 0.301099   Adj. R2: 0.859344
```

**Comment by gbekes** [comment]
Thanks, and for sure. None if these are essential, but got used to adding an issue if stg comes up...

Q1. I see possible quirks, but most folks wanna do simple stuff. I have only ever imagined three types of coef plots in my life 
1. standardized (beta) coeffs, where coeff comparison makes sense
2. FE, where again comparison makes sense
3. single coeff from multiple models 

Will try modelsummary.

Q2: Maybe. it basically needs pre-processing, like filtering top largest coeffs, and showing them only (aka my laziness). Will try your suggestion. 

Q3. My data is 2 million rows, FE: 100 values, other factor is 5 values. Size could be an issue. 

Cheers

**Comment by lrberge** [comment]
On Q1: (later) there will be an integration with the multiple estimations thing. I'll definitely include the sort by value.
On Q2: that could be nice to also include a filter per value in the code => it'll be there!
On Q3: the error message is very.... weird. Not sure it's a size problem. Btw (later) I'll include sparse regressions when you use factors with `i()`, so it should be super fast and memory light (but later, really --> although I already designed it, it entails so much code to change, it gives me headaches! :-)). 

Thanks for the suggestions!
