### ISSUE TITLE
[Feature Request] IV Regression in fixest 

### ISSUE THREAD

**Issue by elchorro** [lrberge/fixest#68]
Both lfe (felm) and reghdfe implement iv regression and, at least in Economics, they seem to be heavily used. Both are also quite slow when there is a lot of data/fixed effects.

What would it take to implement IV in fixest? In OLS the performance gains vs lfe/reghdfe are remarkable (thank you so much for the package!). Even if a fraction of the gains could be achieved in IV, that would be a game changer.

I'm not a C++ programmer, co I can't really contribute myself, but I thought opening an issue may help gauging interest in fixestIV.

**Comment by elchorro** [comment]
Apologies, I noticed in the closed Issues that it was raised several times and it's being developed. Thanks a lot.

I would also be happy to contribute to testing!

**Comment by lrberge** [comment]
No worries. The code is done, the dev version is ready to go (I'm just finishing small things). 

The IVs are explained in the walkthrough vignette (look at the raw Rmd).

Please do check it, I'd be happy to get feedback before submission to CRAN (end of the week) or for future releases.

**Comment by lrberge** [comment]
Ooops, just realized I didn't push the changes to the vignette! Now it's done!

**Comment by elchorro** [comment]
I had the pleasure of testing it today. Fantastic work! Across specifications, I was getting 10-15 times speedup versus felm. The `fml` specification is very clear too.  I am going to try to rewrite my existing project to use fixest now.

**Comment by lrberge** [comment]
Fantastic news! Thanks for the feedback!
