### ISSUE TITLE
stepwise with a pre-defined list of variables

### ISSUE THREAD

**Issue by tcovert** [lrberge/fixest#69]
I love the new `sw` features in the fixest modeling language.  Is there a way to predefine the left hand side variables that can feed into `sw` outside of a formula context?

For example, I might run
```
feols(y ~ x + sw(z1, z2 + z3, z4) | fe, data)
```
What if I had another data set that I'd like to run the same specifications on?  Ideally I'd define the `sw(z1, z2+z3, z4)` call outside of the `feols` call and then substitute it in, but I can't seem to find a way for it to work.  This, for example, does not work:
```
temp <- sw(z1, z2+z3, z4)
```
because `sw` is not exported (I think?).  

I am aware of the `setFixest_fml` command, but that still requires manually specifying each macro in argument to `sw`.
I realize this is a minor problem, but I wondered if I was missing something obvious...

Thanks again for writing this great package.

**Comment by lrberge** [comment]
Hi! Glad you like it! Given the time and energy I've spent on it it's always pleasant to receive positive feedback! :-)

Indeed you're right, `sw` is not exported, the feature of multiple estimations is "only" based on formula manipulation. 

So far it is not possible to have comma separated/or pure verbatim macros (e.g. `..vars = "z1,  z2"`). I wanted to implement it but I'm still struggling with the optimal design. Actually I find it error-prone from the user side (it can easily lead to parsing errors) so I may not implement it... we'll see!

Anyway, as a workaround you could do:
```R
setFixest_fml(..vars = ~sw(z1, z2+z3, z4))
xpd(y ~ x + ..vars | fe)
#> y ~ x + sw(z1, z2 + z3, z4) | fe
```

Wouldn't that be OK for the current purpose?

**Comment by tcovert** [comment]
Ah, I hadn't realized you could put `sw` into a macro definition inside `setFixest_fml()`.  This is exactly what I needed!  Thank you.

**Comment by lrberge** [comment]
Actually you can put in the macro anything that fits in a formula:

```R
setFixest_fml(..v1 = ~ x1, 
              ..v2 = ~ x1 | fe, 
              ..v3 = "x1 | fe | a ~ b")

xpd(y ~ x + ..v1)
#> y ~ x + x1
#> <environment: 0x000001bec9eec4f8>
xpd(y ~ x + ..v2)
#> y ~ x + x1 | fe
#> <environment: 0x000001bec9f21c88>
xpd(y ~ x + ..v3)
#> y ~ x + x1 | fe | a ~ b
#> <environment: 0x000001bec9f409e8>
```

Note that if you want to add a formula into a formula (`..v3`), you need to use text input.
