### ISSUE TITLE
Partial Match Warning

### ISSUE THREAD

**Issue by JordiPosthumus** [lrberge/fixest#7]
When you run the following in R:

options("warnPartialMatchDollar" = TRUE)

And the you use the feglm() function in this package to fit a model which you assign to, say, m1.

Then when you call:

summary(m1)

you get the following warning message:

Warning message:
partial match of 'score' to 'scores'

**Comment by lrberge** [comment]
Ohh the nasty typo! Thanks a lot! Fixed.
