### ISSUE TITLE
Standard-errors can be different from lfe

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#70]
Currently, the lfe package is temporarily removed from CRAN, I am trying to replace lfe with this great package fixest. However, I noticed that the regression result using fixest is different from that using lfe.  

```
require(foreign)
require(lfe)
require(fixest)

df.petersen <- read.dta("http://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/se/test_data.dta")

 # firm + year fixed effects
summary(felm(y ~ x | firmid + year | 0 | 0, data=df.petersen))
summary(feols(y ~ x|firmid + year, data = df.petersen))

# fixed effects with clustering
summary(felm(y ~ x | firmid + year | 0 | firmid + year, data=df.petersen)) 
summary(feols(y ~ x|firmid + year, data = df.petersen), cluster = ~firmid + year)

```

**Comment by lrberge** [comment]
Ahh standard-errors... the perennial issue! :-)

That's perfectly normal behavior. The art of computing standard-errors is fraught with boring details. Please have a look at the dedicated vignette: [On standard-errors](https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html).

And here is the fixed example:
```R
# firm + year fixed effects
sum1_lfe = summary(felm(y ~ x | firmid + year | 0 | 0, data=df.petersen))
sum1_feols = summary(feols(y ~ x|firmid + year, data = df.petersen), 
                     se  = "standard")

# fixed effects with clustering
sum_2_lfe = summary(felm(y ~ x | firmid + year | 0 | firmid + year, data=df.petersen)) 
sum_2_feols = summary(feols(y ~ x|firmid + year, data = df.petersen), 
                     cluster = ~firmid + year, dof = dof(cluster.df = "conv"))


rbind(se(sum1_lfe), se(sum1_feols))
#>              x
#> [1,] 0.0297662
#> [2,] 0.0297662
rbind(se(sum_2_lfe), se(sum_2_feols))
#>               x
#> [1,] 0.02947619
#> [2,] 0.02947619
```

**Comment by lrberge** [comment]
Thanks for the question and the example. Actually I think it can be very useful for other persons interested in comparing the two software. 
I'm pinning it for a month. Thanks again!

**Comment by helix123** [comment]
In case you are interested: Here is an explanation how to align `plm` to Stata's user contributed `xtscc`. It should work for Stata`s own `xtreg` as well: https://stackoverflow.com/questions/65223905/driscoll-and-kraay-standard-errors-in-fe-regression-reproducing-stata-xtscc-out/65270193#65270193

**Comment by waynelapierre** [comment]
Thanks so much for the clarification!

**Comment by waynelapierre** [comment]
```
require(foreign)
df.petersen <- read.dta("http://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/se/test_data.dta")

summary(feols(y ~ x|firmid + year, cluster = ~firmid + year, data = df.petersen), dof = dof(cluster.df = "conv"))
summary(feols(y ~ x|firmid + year, data = df.petersen), cluster = ~firmid + year, dof = dof(cluster.df = "conv"))

```
I don't understand why the results are different when I put the cluster parameter inside the feols function.

**Comment by lrberge** [comment]
Thanks for the comment. 

The difference:
 1. estimation is done and VCOV is clustered by firm + year. Then `summary` is called, `dof` is provided but se/cluster fall back to their default (which is VCOV clustered by firm).
 2. estimation is done without clustering the VCOV. Then `summary` is called and VCOV is clustered by firm+year.

I think the main issue is that I didn't think the `dof` argument would really be used... so I didn't include it in the estimation--I'll correct that. Further, the fact that the default values of se/cluster are triggered when `dof` is provided and the VCOV is already clustered is confusing.  I think I'll change that too.

**Comment by lrberge** [comment]
Just to say that in the dev branch (and hence next version), I added `dof` as an argument of the estimation functions and now there's a memory of how the SEs were computed so that the SEs would be computed as you would expect in your example.
