### ISSUE TITLE
Syntax Stability

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#71]
I would like to ask whether the basic syntax of this package has stabilized. By basic, I mean OLS with fixed effect and clustering. I hope new features in the future would not break the current working code.

**Comment by lrberge** [comment]
That's actually why it takes me so much time & headaches to develop the package: I don't choose the syntax/function names/arguments lightly. I try many things before settling on a definition. So bottom line: most of the package is definitive.

Occasionally I may change existing stuff with no backward compatibility, but it's only when it's obviously substantially better (the only example I have in mind is the recent change I made to argument `style` in `etable` => but it was a marginal argument).

So be reassured, regarding the estimation functions, the syntax won't change in the years to come (I don't like saying never though ;-)).
