### ISSUE TITLE
Replicate plm Regression

### ISSUE THREAD

**Issue by waynelapierre** [lrberge/fixest#73]
```
require(foreign)
df.petersen <- read.dta("http://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/se/test_data.dta")

require(plm)
summary(pmg(y ~ x, data=df.petersen, index=c("year", "firmid")))

```

How can I replicate this plm regression using fixest?

**Comment by lrberge** [comment]
Sorry, I have no clue!

**Comment by helix123** [comment]
In my reading of package `fixest` description, I do not see CCE models models implemented. If you aim for speed: The development version of package "plm" should be considerably faster than the current CRAN version as it can make use of package "collapse" (if the fast mode is enabled).

**Comment by lrberge** [comment]
I didn't know that. The switch to `collapse` is great news for `plm`!

**Comment by waynelapierre** [comment]
It seems fixest and collapse have initiated a move to faster econometrics packages in R... Data are getting larger, and it makes perfect sense to rewrite those highly used R packages in C/C++.

**Comment by helix123** [comment]
So, if CCE models are not implemented by fixest (I did not read a confirmation but it seems like this), replication will not be possible. I guess we can close this issue then?

**Comment by lrberge** [comment]
You're right, it's not covered! Closing then!
