### ISSUE TITLE
panel() and data.table not behaving well inside a function

### ISSUE THREAD

**Issue by tcovert** [lrberge/fixest#76]
Is there a reason why this code shouldn't work?
```
tempdt <- data.table(Firm = c("A", "A", "B", "B"),
                     Year = c(1, 2, 1, 3),
                     Y = c(5, 6, 7, 8))

temp <- function(dt) {
  dt2 <- panel(dt, ~Firm + Year)
  dt2[, lag_y := l(Y)]
  return(dt2)
}
```

When I run `temp(tempdt)` I get the following error:
```
> temp(tempdt)
Error in `[.data.table`(x = dt2, j = `:=`(lag_y, l(Y))) : 
  object 'dt2' not found
```

Thanks in advance for any suggestions.

**Comment by lrberge** [comment]
That's a bug, thanks for reporting! It should be solved now. 

Otherwise, an alternative is to use `dt2[, lag_y := lag(Y ~ Firm + Year)]` without setting up a panel.
