### ISSUE TITLE
Bug checking weights length in demean. 

### ISSUE THREAD

**Issue by SebKrantz** [lrberge/fixest#80]
Hi Laurent, happy new year! I just discovered another bug in demean, in line 3553 of MiscFuns.R, the check:
```
check_arg_plus(weights, "NULL numeric conv vector len(data) GE{0}", .data = X)
```
is wrong as it compares the length of the weight vector to the number of columns in the data. Example:

```
fixest::demean(mtcars, mtcars$cyl, weights = mtcars$wt)
## Error: in fixest::demean(mtcars, mtcars$cyl, weig...:
##  The (nullable) argument 'weights' must be a numeric vector of the same length as argument 'X' (11)
## with positive values. Problem: it is of length 32 instead of 11.
```
This seems to be the case because `X` is not a data frame anymore but a plain list. The thing is that X could also be a matrix. In collapse I have a function `fnrow <- function(x) if(is.list(x)) length(.subset2(x, 1L)) else dim(x)[1L]` . Maybe this needs to be defined and passed to `check_arg_plus`  ?.

Cheers,

Sebastian

**Comment by lrberge** [comment]
Happy new year Sebastian!

Indeed, now `X` can be a plain list! Thanks for this very clear bug report!
