### ISSUE TITLE
Incorporating f-stats into regression results.

### ISSUE THREAD

**Issue by clandinq** [lrberge/fixest#83]
I know the f-stat can be summoned using the fitstat argument. However, when combining fixest with table-production packages (stargazer, modelsummary), the lack of f-stats in the model objects becomes problematic. Are you planning on incorporating this into future editions of fixest?

**Comment by lrberge** [comment]
I'm sorry but that's absolutely out of my control. Whatever I do in `fixest`, there needs to be some manual changes in the software you mention. But you can write a PR to `modelsummary`, for instance, to include this functionality.

**Comment by lrberge** [comment]
Actually, the best would be to include it to [`broom`](https://github.com/tidymodels/broom/blob/master/R/fixest-tidiers.R#L215) first; since it's the backend used by modelsummary and others.
