### ISSUE TITLE
Confused about pvalue function

### ISSUE THREAD

**Issue by lyifa** [lrberge/fixest#85]
Let's say that I have a simple regression: 
est <- feols(y ~ x, mydata)

Are the p values from summary(est) the same as pvalue(est)?

**Comment by lrberge** [comment]
Yes...

```R
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

est = feols(y ~ x1, base)

rbind(pvalue(est), summary(est)$coeftable[, 4])
#>       (Intercept)        x1
#> [1,] 6.469702e-28 0.1518983
#> [2,] 6.469702e-28 0.1518983
```

Although I, myself, am confused about the question. What is the problem/issue? Do you have an example in mind?

**Comment by lyifa** [comment]
I encountered a case where the pvalue(est) and summary(est) have slightly different results. I will double-check my data and code.

**Comment by helix123** [comment]
(different) rounding in printing is a typicall pitfal which could be the case on your side here?

**Comment by lyifa** [comment]
That is what I am thinking. I think this issue can be closed.

**Comment by lrberge** [comment]
OK, closing then. 

Thanks for reporting, but please be more specific next time :-)
