### ISSUE TITLE
feols - NaNs returned when multiple FEs and varying slopes

### ISSUE THREAD

**Issue by adamtheising** [lrberge/fixest#89]
Hi Laurent,

Believe I may have come across a minor and fairly isolated issue the other night, and on a quick skim did not see it on the list of closed issues.

When estimating an OLS model with many fixed effects _and_ varying slopes, feols() sometimes returns me a set of NaN estimates. 

Since by construction there isn't a collinearity issue (see example below), I suspect this is happening when the count of "singleton"-like observations is relatively high. I started reading through your posted code to check whether these observations are dropped since they don't provide any identifying variation, but I quickly gave up the attempt to find the needle in the haystack :)

**A small, reproducible example:**
```
library(data.table)
library(fixest)
library(splitstackshape)
library(purrr)

set.seed(112112)
expander <- c(rep.int(1,20),1:50)
group <- 1:length(expander)

parameters <- c(0.1, 0.5, 0.2, 0.8) # true parameter values
data <- setDT(expandRows(data.frame(group, expander), 'expander')
              )[, x1 := runif(.N,0,1)
                ][, x2 := runif(.N,0,1)
                  ][, x3 := rdunif(.N,0,1)
                    ][, group2 := rdunif(.N,1,5)
                      ][, y := parameters[1] + group/10 + group2/5 + # fixed intercepts
                          parameters[2]*x1*(group/25) + parameters[3]*x2*(group/50) + # group-varying slopes
                          parameters[4]*x3 + # parameter of interest
                          rnorm(.N,0,.1) # noise
                        ][, within_gr_count := .N, by = group]

> feols(y ~ x3 | group[x1, x2] + group2, data)
OLS estimation, Dep. Var.: y
Observations: 1,295 
Fixed-effects: group: 70,  group2: 5
Varying slopes: x1 (group: 70),  x2 (group: 70)
Standard-errors: NA (not-available) 
   Estimate Std. Error t value Pr(>|t|) 
x3      NaN        NaN     NaN       NA 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
                                     
Warning message:
Standard errors are NA because of likely presence of collinearity. Use function collinearity() to detect collinearity problems. 

> collinearity(feols(y ~ x3 | group[x1, x2] + group2, data))
[1] "No visible collinearity problem. (Doesn't mean there's none!)"
```

I'll also note that there's no apparent problem when including just FEs or just a single FE + varying slopes:

```
> feols(y ~ x3 | group[x1, x2], data)
OLS estimation, Dep. Var.: y
Observations: 1,295 
Fixed-effects: group: 70
Varying slopes: x1 (group: 70),  x2 (group: 70)
Standard-errors: Clustered (group) 
   Estimate Std. Error t value  Pr(>|t|)    
x3 0.785037   0.015531  50.546 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.279542     Adj. R2: 0.962225
                 Within R2: 0.640012

> feols(y ~ x3 | group + group2, data)
OLS estimation, Dep. Var.: y
Observations: 1,295 
Fixed-effects: group: 70,  group2: 5
Standard-errors: Clustered (group) 
   Estimate Std. Error t value  Pr(>|t|)    
x3 0.813667   0.016505  49.299 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.332054     Adj. R2: 0.952642
                 Within R2: 0.587349
```

Lastly, things also appear to run fine if I manually drop the singletons from the data sample:

```
> feols(y ~ x3 | group[x1, x2] + group2, data[within_gr_count > 1])
OLS estimation, Dep. Var.: y
Observations: 1,274 
Fixed-effects: group: 49,  group2: 5
Varying slopes: x1 (group: 49),  x2 (group: 49)
Standard-errors: Clustered (group) 
   Estimate Std. Error t value  Pr(>|t|)    
x3 0.806262   0.006191  130.23 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.093687     Adj. R2: 0.995272
                 Within R2: 0.944066
```

Thoughts?

Merci bcp pour ton package -- ce que tu a developpe est super!

Cheers,
Adam

**Comment by lrberge** [comment]
Thanks a lot for the reproductible example!!! In all honesty, these variables with varying slopes are a #$@!

I don't have the time to do anything for a month now, but I'll correct the problem as soon as I can. 
Btw the argument `fixef.rm = "singleton"` should, well... remove the singletons :-)

Thanks again for the clear report!
Laurent

**Comment by adamtheising** [comment]
Thanks for the fixef.rm note -- that's quite helpful to know.

Absolutely zero rush at all; it seems simple enough to work around manually, but just thought i would point it out. 

Good luck with your other deadlines!

**Comment by lrberge** [comment]
Hi, finally fixed! It was a special case hiding deep in the c++ code.

Thanks again for the clear report!
