### ISSUE TITLE
Issue when formula is of the form Z ~ X + Y + (X==1)

### ISSUE THREAD

**Issue by JordiPosthumus** [lrberge/fixest#9]
Hi Mr Berge ! 

Loving your package, thanks for releasing it into the wild.

There are times when it useful to do a dummy encoding in the formula itself, such as I have outlined in the title of this post.

(This approach works with lm(), glm(), model.matrix(), etc)

When I do that with feglm(), we get this error message:

 ClassType + FaceAmountBand +  : 
  Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:115: unexpected '=='
1: lhs ~ X + Y + X == 1
                                ^
This error was unforeseen by the author of the function feglm. If you think your call to the function is legitimate, could you report?

**Comment by lrberge** [comment]
Hello, thanks for using it and for reporting!

Unfortunately, I cannot replicate the error, these kind of formulas work fine for me. 

Could you add a minimal working example?

**Comment by JordiPosthumus** [comment]
On it !  Thought I had it, but now the minimal example is not working.  Will try again.

**Comment by lrberge** [comment]
Hi, should I close the issue then?

**Comment by JordiPosthumus** [comment]
Go for it! Thank you!
