### ISSUE TITLE
The covariance is not defined

### ISSUE THREAD

**Issue by pachamaltese** [lrberge/fixest#92]
I got this warning and unexpected NAs:

```
m3 <- fixest::feglm(trade ~ log_dist + cntg + lang + clny + exp_year + imp_year,
               family = quasipoisson(link = "log"),
               data = ch1_application1_2
)

Variables 'imp_yearZAF1990' and 'imp_yearZAF2002' have been removed because of collinearity (see $collin.var).
Warning message:
Absence of convergence: Maximum number of iterations reached (25). Final deviance: 1.103e+9. Residual collinearity was found after the weighted-OLS stage. The covariance is not defined. (This should not happen. If possible, could you send a replicable example to fixest's author? He's curious about when that actually happen.) 
```

```
> m3
GLM estimation, family = quasipoisson(link = "log"), Dep. Var.: trade
Observations: 28,152 
Standard-errors: NA (not-available) 
                  Estimate Std. Error t value Pr(>|t|) 
(Intercept)       4.133900         NA      NA       NA 
log_dist         -0.241002         NA      NA       NA 
cntg              0.339740         NA      NA       NA 
lang              0.038459         NA      NA       NA 
clny             -0.008534         NA      NA       NA 
exp_yearARG1990   0.511826         NA      NA       NA 
exp_yearARG1994 -48.000000         NA      NA       NA 
exp_yearARG1998  41.438000         NA      NA       NA 
... 821 coefficients remaining (display them with summary() or use argument n)
... 2 variables were removed because of collinearity (imp_yearZAF1990 and imp_yearZAF2002)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
                                           
  Squared Cor.: 2.912e-4                   
# Evaluations: lhs: 25 -- no convergence: Maximum number of iterations reached 
Warning messages:
1: Standard errors are NA because of likely presence of collinearity. Use function collinearity() to detect collinearity problems. 
2: The GLM algorithm did not converge, the results are not reliable. (no convergence: Maximum number of iterations reached) 
```

The complete test can be found at https://github.com/pachamaltese/boostedglm/blob/main/dev/test-fglm-with-yotover-data.R#L78-L88. In that example, m1 and m2 already fully reproduce the Stata example Yotov, et al (2016, ISBN: 978-92-870-4367-2) before applying vcovCL for the std error.

**Comment by lrberge** [comment]
Thanks for the report and reproductible example, now I know when this happens!

It has to do with the collinearity problem stemming from the dummies. If you use `collin.tol = 1e-4`, it should work fine. At least the results were replicated on my machine.
I think I'll increase the default value for `collin.tol` which seems too low from the feedback I'm getting. 
I will also add a better warning message telling precisely the user how to overcome the problem (now that I know why it happens).

Btw, also I think you know but just in case, it's much much faster to add the dummies in the fixed-effects part of the formula.

**Comment by pachamaltese** [comment]
> Thanks for the report and reproductible example, now I know when this happens!
> 
> It has to do with the collinearity problem stemming from the dummies. If you use `collin.tol = 1e-4`, it should work fine. At least the results were replicated on my machine.
> I think I'll increase the default value for `collin.tol` which seems too low from the feedback I'm getting.
> I will also add a better warning message telling precisely the user how to overcome the problem (now that I know why it happens).
> 
> Btw, also I think you know but just in case, it's much much faster to add the dummies in the fixed-effects part of the formula.

thank you !! btw, I've restores the dev/ folder which I accidentally deleted
would you be interested in contributing to boostedglm?
