### ISSUE TITLE
etable not showing properly in Rmarkdown

### ISSUE THREAD

**Issue by kdzhang** [lrberge/fixest#93]
Hi, I found that the `etable` does not work properly in Rmarkdown. If I run the following chunk, I got a column full of `<chr[1]>`:

```r
gravity_pois = fepois(Euros ~ log(dist_km) | Origin + Destination + Product + Year, trade)
etable(gravity_pois)
```
![image](https://user-images.githubusercontent.com/4772818/104864825-39d80180-5908-11eb-9a2e-1cba1f74a7fd.png)

But doing this in R console works as expected:

```
> etable(gravity_pois)
                      gravity_pois
Dependent Var.:              Euros
                                  
log(dist_km)    -1.528*** (0.1157)
Fixed-Effects:  ------------------
Origin                         Yes
Destination                    Yes
Product                        Yes
Year                           Yes
_______________ __________________
S.E.: Clustered         by: Origin
Observations                38,325
Squared Cor.              0.612021
Pseudo R2                 0.764032
BIC                      1.405e+12
```

Is this the expected behavior or I actually mis-configured something? Thank you!

**Comment by adamtheising** [comment]
I can't replicate the output you're getting in Rmarkdown, but maybe try (?):

```
library(pander)
gravity_pois = fepois(Euros ~ log(dist_km) | Origin + Destination + Product + Year, trade)
etable(gravity_pois, postprocess.df = pandoc.table.return, style = 'rmarkdown')
```

See here for more: https://lrberge.github.io/fixest/articles/exporting_tables.html

**Comment by kdzhang** [comment]
Thank you! `etable(gravity_pois, postprocess.df = pandoc.table.return, style = 'rmarkdown')` works well! I think I am good with this for now.

For future users who have the same problem: I am having the display problem with R/4.0.3, with `fixest/0.8.0` and `Rmarkdown/2.6`. The same problem occured in my  M1 chip Macbook Pro as well as Windows PC.

**Comment by lrberge** [comment]
Hi, and thanks @adamtheising for giving a solution!

@kdzhang: `etable` returns a plain `data.frame`. So the way it is rendered in rmarkdown completely depends on the `print.data.frame` method. And (almost for sure) it turns out that this `print.data.frame` has been modified in your rmarkdown document.

Maybe in the future I'll add a specific method to deal with this, and which will also allow to display extra information on the table.

Thanks again @adamtheising!

**Comment by lrberge** [comment]
Actually I was wrong: `print` was not faulty. The culprit was the behavior of `as.data.frame` that changed for some unknown reason (it's used within `etable`). I've just pushed changes that should make it work as normal.
