### ISSUE TITLE
Summary of fixest_multi with lean = T is still very large

### ISSUE THREAD

**Issue by elchorro** [lrberge/fixest#96]
Hi there,

Saving the results seems problematic. When I apply summary( fit, lean = T) this does not appear to do anything. The object still contains objects such as residuals. In my application it makes it unsuitable for saving. Is this intended behaviour? A method that saves only estimation results and keeps the files small (such as the one in lfe) would be very helpful. 

Many thanks

**Comment by lrberge** [comment]
Hi, thanks for opening an issue but *please always provide a reproductible example* (see #33). 

What do you mean by *does not appear to do anything*? Here's an example, I cannot replicate what is suggested in your post:
```R
library(fixest)

base = iris
names(base) = c("y", "x1", "x2", "x3", "species")

# Estimation
res = feols(c(y, x1) ~ sw(x2, x3) | sw0(species), base)
res_lean = summary(res, lean = TRUE)

# Maximum object size per estimation
sapply(as.list(res), function(x) max(lengths(x)))
#> [1] 300 300 150 150 300 300 150 150
sapply(as.list(res_lean), function(x) max(lengths(x)))
#> [1] 4 4 4 4 4 4 4 4
```

**Comment by lrberge** [comment]
I'm closing the issue, please reopen it with a replicable example if the problem persists.
