### ISSUE TITLE
Programmatic construction of formulas

### ISSUE THREAD

**Issue by pdeffebach** [lrberge/fixest#98]
If I want to to write a function which takes in strings for the outcome variable and the independent variables, potentially also using more complicated things like `i()`, is there a way to construct a formula? 

Preferably without creating a big string and parsing it with `as.formula` or equivalent.

**Comment by lrberge** [comment]
Use `xpd`?

```R
library(fixest)
xpd(lhs = "y", rhs = c("x1", "x2"))
#> y ~ x1 + x2
#> <environment: 0x000001a0ae1260e8>
```

Could you provide more examples of uses that you have in mind (by giving examples of user-level calls)?

**Comment by adviksh** [comment]
@pdeffebach if xpd isn't flexible enough, I recently did something like this using the `glue` package and some custom code.

```
add = function(x) { paste(x, collapse = '+') }

formulate = function(y_nm, tmt_nm, inst_nm, x_nm, fe_nm) {
    f = glue::glue('{y_nm} ~ {add(x_nm)} | {fe_nm} | {tmt_nm} ~ {add(inst_nm)}')
    formula(f)
}

# example:
form = formulate(y_nm = 'mpg', tmt_nm = 'hp', inst_nm = c('vs', 'am'), fe_nm = 'cyl', x_nm = 'disp')
feols(form, data = mtcars)

# omit X or fixed effects by passing '1' 
form2 = formulate(y_nm = 'mpg', tmt_nm = 'hp', inst_nm = c('vs', 'am'), fe_nm = '1', x_nm = '1')
feols(form2, data = mtcars)

```

You might have to get more creative to include interactions.

**Comment by lrberge** [comment]
Adding to the previous answer, here's another example:
```R
library(fixest)
xpd(~ ..rhs + i(..var, ..fact), ..rhs = c("x1", "x2"), ..var = "x_cont", ..fact = "x_fact")
#> ~x1 + x2 + i(x_cont, x_fact)
#> <environment: 0x0000028633614590>
```

I'm closing, feel free to reopen with concrete examples if that's not sufficient.

**Comment by pdeffebach** [comment]
Sorry about the non-reply!

This final answer was exactly what I needed. Thank you!
