### ISSUE TITLE
Using i() with instrumented variable

### ISSUE THREAD

**Issue by adamaltmejd** [lrberge/fixest#99]
Hey! Finally starting to explore your package and already loving it! Was trying to run an IV estimation with an interacted instrumented variable and getting a strange error. Is i() simply not implemented for instrumented variables or is it a bug?

```
data(base_did)
base_did$takeup <- rbinom(nrow(base_did), 1, 0.5)
est_did = feols(y ~ x1 | id + period | i(takeup, period, 5) ~ i(treat, period, 5), base_did)
```

results in:

```
Error in str2lang(x) : <text>:1:16: unexpected numeric constant
1: takeup:period::1
```

**Comment by lrberge** [comment]
Hi, indeed so far it is not possible to instrument factor variables. It implies a lot of technical problems. I'll see what I can do and keep you posted.

**Comment by adamaltmejd** [comment]
Thanks! Feel free to close this then.

**Comment by lrberge** [comment]
Actually I applied a small patch that should make it work, but there may be other unexpected problems down the road.

Closing then :-)

**Comment by adamaltmejd** [comment]
Awesome!
